### DISCUSSION TITLE
How to use variant in set_text_variables preflight

### DISCUSSION THREAD

**Discussion by cdwilson** [INTI-CMNB/KiBot#233] [Q&A] [answered]
I'd like to set a text variable named `${VARIANT}` in the KiCad schematic title block with the value of the `variant` global.

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/14631/180144229-53acf6b9-b243-45bc-aeae-083283fc09eb.png">

I have a KiBot config similar to the following:

```yaml
preflight:
  set_text_variables:
    - name: VARIANT
      text: '%V'

variants:
  - name: my_variant
    comment: "a comment"
    type: kibom
    file_id: _my_variant
    variant: my_variant
    pre_transform: _var_rename
  - name: another_variant
    comment: "another comment"
    type: kibom
    file_id: _another_variant
    variant: another_variant
    pre_transform: _var_rename

outputs:
  - name: schematic_pdf
    comment: Export the schematic to PDF
    type: pdf_sch_print
    dir: +/Schematic
    options:
      # [string|list(string)='_none'] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: _kibom_dnf_BOM
      # [boolean=true] Include the frame and title block
      frame: true
      # [boolean=false] Generate a monochromatic PDF
      monochrome: false
      # [string='%f-%i%I%v.%x'] Filename for the output PDF (%i=schematic, %x=pdf). Affected by global options
      output: '%f-%i%I%v.%x'
```

However, when I output the schematic PDF with the CLI option `-g variant=my_variant`, the `${VARIANT}` value does not appear to be set:

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/14631/180144946-70c8fa53-3e23-4857-b512-d16c19b2b008.png">

Is it possible to pass the variant into KiCad as a text variable?
