### DISCUSSION TITLE
How to use custom values in KiBot output file names?

### DISCUSSION THREAD

**Discussion by cdwilson** [INTI-CMNB/KiBot#243] [Q&A] [answered]
Let's say that I have two assembly variants (`variant_1` & `variant_2`) and I want to set `output` file name differently for each variant.  For `variant_1` I want the schematic to be named `RED.pdf` and for `variant_2` I want the schematic to be named `BLUE.pdf`.

It appears that `%I` was intended to allow user-defined content in the output file name, but I'm not exactly sure how to set this value based on the currently active variant.

The documentation says:

> `output_id`: [string=''] Text to use for the %I expansion content. To differentiate variations of this output.

It seems like I should set `output_id: "%I.%x"`, but I'm not sure how to get `%I = RED` for `variant_1` and `%I = BLUE` for `variant_2` in the kibot.yaml file.

Essentially, I'm looking for something like a variable which can be defined differently for each variant inside the kibot.yaml file and then used in the outputs.

**Comment by set-soft** [comment]
Hi @cdwilson !
Use `output_id: RED` in one case and `output_id: BLUE` in the other. 

If both variants share the outputs (without `extend` or similar mechanism to make them different) you can also use `%v` and `%V`: You can just name one variant `RED` and the other `BLUE` and use `%V` in the `output` pattern. The name of the variant is something arbitrary. Also note that variants has two fields, its name and the `file_id` (`%v`).

**Reply by cdwilson** [reply]
Hi @set-soft, sorry, I didn't do a good job describing what I was trying to accomplish in my original post.  What you describe in your reply makes total sense in the case where each variant only needs a single modifier that is used in all the outputs (via `%v` and `%V`).

What I'm looking for is a way to define multiple modifiers for each variant.  Specifically, for each variant I have a top-level part number for the assembly variant, e.g. `BOM-1234`.  I also have a unique schematic document number for each variant, e.g. `SCH-5678`.

When I generate the BOM for a variant, I want to name it `BOM-1234.csv`.  However, when I generate the schematic for that same assembly variant, I want to name it `SCH-5678.pdf`.

This is probably not the best way to implement it, but I'm imagining something like this:

```
# File: release_BOM-1234.kibot.yaml

import:
  - file: release.kibot.yaml

variants:
  - name: BOM-1234
    comment: BOM-1234
    type: kibom
    file_id: _BOM-1234
    variant: BOM-1234
    pre_transform: _var_rename
    set_variant_variables: <-- some mechanism to define a "variable" that can be used in the text variables and the output file names
      - name: SCHEMATIC_DOC_NUMBER
        value: SCH-5678
```

```
# File: release_BOM-9999.kibot.yaml

import:
  - file: release.kibot.yaml

variants:
  - name: BOM-9999
    comment: BOM-9999
    type: kibom
    file_id: _BOM-9999
    variant: BOM-9999
    pre_transform: _var_rename
    set_variant_variables:
      - name: SCHEMATIC_DOC_NUMBER
        value: SCH-7777
```

```
# File: release.kibot.yaml

preflight:
  set_text_variables:
    - name: SCHEMATIC_DOC_NUMBER
      text: ${SCHEMATIC_DOC_NUMBER}

outputs:
  - name: schematic_pdf
    ...
    options:
      ...
      output: "${SCHEMATIC_DOC_NUMBER}.%x"
```

**Reply by cdwilson** [reply]
FYI, for anyone else trying to do something similar in the future, I was able to achieve this very easily using python's [Template strings](https://docs.python.org/3/library/string.html#template-strings).

I have a python script which automatically generates multiple `<variant>.kibot.yaml` files from a single `template.kibot.yaml` file.  This actually simplified things, since it allowed me to have just a single `template.kibot.yaml` (rather than having to maintain separate configs for each variant that each import from a shared `release.kibot.yaml` file).  The `template.kibot.yaml` file contains python template strings which are replaced by the python script, for example:

```
# template.kibot.yaml
outputs:
  - name: schematic_pdf
    comment: Export the schematic to PDF
    type: pdf_sch_print
    dir: +/Schematic
    run_by_default: true
    options:
      frame: true
      all_pages: true
      dnf_filter: _kibom_dnf_BOM
      monochrome: false
      output: "%f_V${PROJECT_VERSION}_Schematic_${SCHEMATIC_PART_NUMBER}_Rev_${SCHEMATIC_REVISION}.%x"
```

is transformed into:

```
# FCD-000035.kibot.yaml
outputs:
  - name: schematic_pdf
    comment: Export the schematic to PDF
    type: pdf_sch_print
    dir: +/Schematic
    run_by_default: true
    options:
      frame: true
      all_pages: true
      dnf_filter: _kibom_dnf_BOM
      monochrome: false
      output: "%f_V1_Schematic_FCD-000036_Rev_B.%x"
```
