### DISCUSSION TITLE
fit_field usage in bom vs. kibom outputs

### DISCUSSION THREAD

**Discussion by cdwilson** [INTI-CMNB/KiBot#251] [General]
The documentation says:

> fit_field: [string='Config'] Field name used for internal filters.

If I define a `bom` output with the `fit_field` defined, the resulting BOM does not ignore DNF components (even though `ignore_dnf: true` is set):

```
outputs:
  - type: bom
    options:
      format: HTML
      fit_field: BOM
      ignore_dnf: true
```

However, if I add `dnf_filter: _kibom_dnf_BOM`, then DNF components are correctly ignored in the resulting BOM:

```
outputs:
  - type: bom
    options:
      format: HTML
      fit_field: BOM
      ignore_dnf: true
      dnf_filter: _kibom_dnf_BOM
```

I would assume that by defining `fit_field: BOM`, the internal `_kibom_dnf` filter should effectively function the same as a filter named `_kibom_dnf_BOM`, so `dnf_filter: _kibom_dnf_BOM` should be unnecessary.  

Furthermore, if I define a `kibom` output with `fit_field: BOM`, the DNF components are correctly ignored in the resulting BOM:

```
outputs:
  - type: kibom
    options:
      format: HTML
      conf:
        fit_field: BOM
        ignore_dnf: true
```

It seems like there is a difference between the behavior of `bom` vs. `kibom` outputs, i.e. `bom` seems to require an explicit `dnf_filter: _kibom_dnf_BOM` whereas `kibom` seems to implicitly create this filter based on the `fit_field: BOM` option.

Is this intentional?  If not, could the `bom` output be fixed so that when `fit_field: BOM` is specified, the internal `_kibom_dnf` filter behaves like  `_kibom_dnf_BOM` (i.e. `dnf_filter: _kibom_dnf_BOM` doesn't need to be specified also)?

**Comment by set-soft** [comment]
Do you have a small example to check this?
Using a small config: 

```yaml
outputs:
  - name: 'bom_internal'
    comment: "Bill of Materials in CSV format"
    type: bom
    dir: BoM
    options:
      fit_field: BOM
```

I see:
```
DEBUG:Creating internal filter: {'name': '_kibom_dnf_BOM', 'type': 'generic', 'comment': 'Internal KiBoM DNF filter (BOM)', 'config_field': 'BOM', 'exclude_value': True, 'exclude_config': True, 'keys': 'dnf_list'} (kibot - fil_base.py:270)
...
DEBUG:Applying filter `_kibom_dnf_BOM` to fitted (kibot - fil_base.py:171)
```
