### DISCUSSION TITLE
Update text (silk/...) on PCB to include git hash/version.

### DISCUSSION THREAD

**Discussion by mdeweerd** [INTI-CMNB/KiBot#274] [Ideas]
It's always good to have an automated version reference, so why not add the short git hash to the PCB as a silk text.
AFAIK it's already possible to update schematic/pcb properties that appear on the sheet (which is different).

I am not sure what the best method would be to determine the location and options:
- A pre-existing label on the PCB of which the content would be replaced;
- A pre-existing component on the PCB that has a label that would be replaced.
- A fixed location on the PCB.
- Only added when generated by KiBot (the label could be set as hidden by default);
- ... .

It should be possible to insert this multiple times and at least once on front and back layers.

**Comment by set-soft** [comment]
What's wrong with text variables?

**Reply by mdeweerd** [reply]
Ok I did not see that option, but I'll have to use pcb_replace.

Thanks.

**Reply by mdeweerd** [reply]
For the record (other readers), this worked:
```yaml
  sch_replace:
    replace_tags:
      - tag: version
        #command: 'git log -1 --format="%h_%(describe:tags)" -- $KIBOT_SCH_NAME'
        command: 'git log -1 --format="%h" -- $KIBOT_SCH_NAME'
  pcb_replace:
    replace_tags:
      - tag: version
        command: 'git log -1 --format="%h" -- $KIBOT_PCB_NAME'
``` 

``` 
git log -1 --format="%h_%(describe:tags)" -- $KIBOT_SCH_NAME
``` 
works interactively, but non the docker image and is probably because my local git version is newer.
