### DISCUSSION TITLE
Diff with github action -> fetch depth

### DISCUSSION THREAD

**Discussion by 42CrMo4** [INTI-CMNB/KiBot#308] [General]
Hello, 

I was trying to get the **Diff** option working on my Github Workflow. But had a hard time figuring out why it was not working. In the end it was a small forgotten configuration setting on my side and had nothing to-do with Kibot. Nevertheless I thought I would share my findings here as this could occur to others too and therefore might help. 

**Sample Error Logs I was getting**

```
ERROR:In section 'diff_pcb' (diff): The 'KIBOT_LAST-1' doesn't resolve to a valid hash (kibot - error.py:40)
Error: Process completed with exit code 7.
```
```
ERROR:Running ['/usr/bin/git', 'checkout', '--recurse-submodules', 'main'] returned 1 (kibot - kiplot.py:154)
Error: Process completed with exit code 25.
```

**Problem**

Either the KIBOT_LAST-n command could not be resolved or the git checkout would fail. In hindsight it was the same problem. 

**Solution**

I use the _checkout@v3_ action and in the default configuration it only fetches 1 commit. This will result in failing the lookup of any Tag/Hash/commit. As seen in the error logs. 

To change this I had to add one line to the checkout@v3 step. See below the minimum example I used. 

```
Fabrication:
    name: Fabrication files
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto:dev

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
```

So adding the line `fetch-depth: '0'` which fetches all commits solved it. For full details on the behavior please see the  [checkout@v3 readme](https://github.com/actions/checkout#usage)

I know for the most people this might be obvious but git and github workflows are not my profession :)
