### DISCUSSION TITLE
How to have diffs relative to previous tag?

### DISCUSSION THREAD

**Discussion by raulgotor** [INTI-CMNB/KiBot#312] [Q&A] [answered]
Hello, 

I want to have the diffs of the schematic relative to the latest tag in git. Using the example .yaml file:

```yaml
- name: basic_diff_sch
  comment: Schematic diff between the last two changes
  type: diff
  dir: diff
  options:
      old: KIBOT_LAST-1
      old_type: git
      new: HEAD
      new_type: git
      cache_dir: /kikit/.cache
      add_link_id: true
      pcb: false
```

I though of having something like `old: @TAG@` and when calling kibot from the command line, using `-g TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`)`, but sadly`@TAG@` seems not to be replaced. Is there any solution available for this?

By the way, what a great software you guys created. Many thanks!
