### DISCUSSION TITLE
KiBot renders, KiCad does not?

### DISCUSSION THREAD

**Discussion by gcormier** [INTI-CMNB/KiBot#415] [General]
KiCad does not have a 3D model for the ESP32-S2. The 3D preview in KiCad

![image](https://user-images.githubusercontent.com/8388983/229859309-bc74d96e-d119-4ac7-bea5-d36e68ccd11b.png)

Yet when I push it to GitHub and my GH action runs, it manages to render it with the model! (A missing polyfuse model as well)
![image](https://user-images.githubusercontent.com/8388983/229859404-af726579-7174-4d25-96fb-fd7d7db141e9.png)

I mean, super happy about that.. but.. where is KiBot getting the model from? My pipeline even has this in the log

```
WARNING:(W048) Failed to download `[https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/RF_Module.3dshapes/ESP32-S2-WROVER.wrl`](https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/RF_Module.3dshapes/ESP32-S2-WROVER.wrl%60) (kibot - out_base_3d.py:115)
```

**Comment by set-soft** [comment]
Hi @gcormier !

Do you have LCSC codes in your components? KiBot can also download 3D models from EasyEDA, courtesy of LCSC

**Reply by gcormier** [reply]
Aha, I do, so that must be it :) So I can then try out a rotation filter for this part.

**Reply by gcormier** [reply]
Is it possible to rotate a single 3d model in this scenario?

```
kibot:
  version: 1

outputs:
  - name: 'STEP'
    comment: "STEP file"
    type: step

  - name: 'Rendering'
    type: render_3d
    options:
      view: top
      rotate_x: 4
      rotate_y: 0
      rotate_z: -3
      ray_tracing: true
      auto_crop: true
      transparent_background: true
      output: "render.png"
```
