### DISCUSSION TITLE
Gitlab CI - No eeschema signature

### DISCUSSION THREAD

**Discussion by manuel-rw** [INTI-CMNB/KiBot#458] [Q&A] [answered]
Hello,
thank you for this awesome project.
I just started using it and automatically creating artifacts on each commit.

It works great so far, but I have issues with the 3d renders of the PCB.
This is my kiplot / kibot configuration:

```yaml
# Example KiPlot config file
kiplot:
  version: 1

preflight:
  run_erc: false
  update_xml: true
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

global:
  units: millimeters

outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: Schematic.pdf

  - name: 'print_front'
    comment: "Print F.Cu+Dwgs.User"
    type: pdf_pcb_print
    dir: .
    options:
      output_name: PCB_Top.pdf
    layers:
      - layer: B.Cu
      - layer: F.SilkS

  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: Gerbers
    options:
      # generic layer options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: false
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true

      # gerber options
      line_width: 0.1
      subtract_mask_from_silk: false
      use_protel_extensions: false
      gerber_precision: 4.6
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: true

    layers:
      - layer: B.Cu
        suffix: B_Cu
      - layer: F.SilkS
        suffix: F_SilkS
      - layer: Edge.Cuts
        suffix: Edge_Cuts
  - name: basic_position_CSV
    comment: Components position for Pick & Place
    type: position
    dir: .
    options:
      format: CSV
      only_smd: false
      output: '%i %f_pos_%D.%x'
  - name: basic_render_3d_30deg_top
    comment: 3D view from 30 degrees top
    type: render_3d
    dir: renders/top
    output_id: _view
    options:
      ray_tracing: true
      rotate_x: 3
      rotate_z: -1
      download: true
      zoom: 6
      height: 1440
      width: 2560
      no_virtual: true
  - name: basic_render_3d_30deg_bottom
    comment: 3D view from 30 degrees bottom
    type: render_3d
    dir: renders/bottom
    output_id: _view
    options:
      ray_tracing: true
      rotate_x: 3
      rotate_z: -1
      download: true
      zoom: 6
      view: bottom
      height: 1440
      width: 2560
      no_virtual: true
  - name: iBoM
    comment: Interactive HTMl BoM
    type: ibom
    dir: BOM
    options:
      highlight_pin1: false
```

This is the pipeline on GitLab:

```yaml
stages:
  - run_erc
  - run_drc
  - gen_fab

image:
  # name: setsoft/kicad_auto:dev_k6
  name: ghcr.io/inti-cmnb/kicad7_auto_full:latest

erc:
  stage: run_erc
  script:
    - "kibot -e './pcb/XXX.kicad_sch' -d Fabrication -s update_xml,run_drc -i"
  rules:
    - changes:
      - "**.kicad_sch"
      - ".gitlab-ci.yml"
      when: always
  artifacts:
    when: always
    paths:
      - Fabrication/

drc:
  stage: run_drc
  script:
    - "kibot -e './pcb/XXX.kicad_pcb' -d Fabrication -s update_xml,run_erc -i"
  rules:
    - changes:
      - "**.kicad_pcb"
      - ".gitlab-ci.yml"
      when: always
  artifacts:
    when: always
    paths:
      - Fabrication/


sch_outputs:
  stage: gen_fab
  script:
    - "kibot -e './pcb/XXX.kicad_sch' -d Fabrication -s run_drc,run_erc print_sch basic_position_CSV iBoM"
  rules:
    - changes:
      - "**.kicad_sch"
      - ".gitlab-ci.yml"
      when: on_success
  artifacts:
    when: always
    paths:
      - Fabrication/

pcb_outputs:
  stage: gen_fab
  script:
    - "kibot -e './pcb/XXX.kicad_pcb' -d Fabrication -s run_drc,run_erc,update_xml print_front gerbers basic_render_3d_30deg_bottom basic_render_3d_30deg_top"
  rules:
    - changes:
      - "**.kicad_pcb"
      - ".gitlab-ci.yml"
      when: on_success
  artifacts:
    when: always
    paths:
      - Fabrication/
```

In the job, I get the following error:
```
Using config file: XXX.kiplot.yaml
- 'Print F.Cu+Dwgs.User' (print_front) [pdf_pcb_print]
WARNING:(W058) Missing KiCad main config file /root/.config/kicad/7.0/kicad_common.json (pcbnew_do - misc.py:200) (kibot - kiplot.py:132)
- 'Gerbers for the board house' (gerbers) [gerber]
- '3D view from 30 degrees top' (basic_render_3d_30deg_top) [render_3d]
ERROR:At line 1 of `/builds/XXXXXXXX/XXXXXX/pcb/XXXXX.kicad_pcb`: No eeschema signature (kibot.gs - gs.py:731)
ERROR:Line content: `(kicad_pcb (version 20[22](https://my-gitlab-host/XXX/XXXXX/-/jobs/213#L22)1018) (generator pcbnew)` (kibot.gs - gs.py:731)
```

What does this error mean?
I was not able to find any information at all regarding it.
I don't have much experience with KiCad at all - so I might be missing something.
Would be awesome, if someone here could point me to the issue. I'm glad to provide more information if needed.

PS: Since KiCad 7, I also get false-positives for some clearances (known bug). Can I disable them to get the ERC & DRC up again? And, can I somehow host the interactive HTML BOM on Gitlab? I always have to download it, which is an inconvenience.
