### DISCUSSION TITLE
Simple animations using Blender

### DISCUSSION THREAD

**Discussion by set-soft** [INTI-CMNB/KiBot#482] [Announcements]
A [thread](https://forum.kicad.info/t/kirec3d-record-animations-videos-from-the-3d-view/44162) in the KiCad Forum about creating animations using 3D View made me think about a few useful options to enable the generation of videos using the `blender_export` output.

Here is a simple example:

https://github.com/INTI-CMNB/KiBot/assets/22823627/197e97c3-2515-45a5-9bf6-c214969806a8

It was generated using the following [configuration file](https://github.com/INTI-CMNB/KiBot/blob/dev/tests/yaml_samples/blender_export_mult.kibot.yaml):

```yaml
# KiBot Blender export test multiple view points
# Multiple points of view
kibot:
  version: 1

outputs:
  - name: '3d_video_export'
    comment: "Generates the frames for a video of a rotating PCB"
    type: blender_export
    options:
      render_options:
        transparent_background: true
        samples: 10
      fixed_auto_camera: true
      auto_camera_z_axis_factor: 1.5
      default_file_id: '_%03d'
      point_of_view:
        - rotate_x: 30
          rotate_z: -20
        - rotate_x: 4
          rotate_z: 4
          steps: 90
      outputs:
        - type: render
 ```

To join the generated PNGs into a video I used:

```
ffmpeg -framerate 24 -pattern_type glob -i '*.png' -c:v libx264  -pix_fmt yuv420p out.mp4
```
