### DISCUSSION TITLE
Make KiBot fail on unconnected items with filter

### DISCUSSION THREAD

**Discussion by gcormier** [INTI-CMNB/KiBot#514] [Q&A]
I've checked the DRC section, but I'm not sure if this use case can be covered.

![image](https://github.com/INTI-CMNB/KiBot/assets/8388983/94c7e50d-4c5c-4b5d-a139-11b5ac69f38b)

I want to have KiBot fail if there are items unconnected. I'd like to filter this, as some "unconnected" items (`*SHIELD*) I don't care about.

I think this can't be done today, and I might need some combination of `ignore_unconnected` as well as the ability to filter that?

**Comment by set-soft** [comment]
Why don't you just add filters for the *SHIELD* stuff?

Try something like:

```yaml
kibot:
  version: 1

preflight:
  run_drc: true
  filters:
    - filter: 'Ignore J1 shield connections'
      error: 'unconnected_items'
      regex: 'J1-SHIELD-PadS1'
```

Note that the name *unconnected_items* is the name used by KiCad and reported in the KiBot logs (from the DRC report).

I implemented a toy test here: [test_unconnected_items_filter.zip](https://github.com/INTI-CMNB/KiBot/files/13280321/test_unconnected_items_filter.zip)
