### DISCUSSION TITLE
Include some filters for `position` task

### DISCUSSION THREAD

**Discussion by gcormier** [INTI-CMNB/KiBot#516] [Q&A] [answered]
KiKit now has components when panelizing. The result is that KiBot will output these in the `position` job.

I don't see a filter option on `position`. Is there currently a way to tell KiBot to exclude all components matching `*KiKit*` when making the pick and place?

**Comment by set-soft** [comment]
Hi @gcormier !

Did you try using a `dnf_filter`? (in the options for the position output)

You can use a general filter and remove the components you want.

**Reply by gcormier** [reply]
I'm not sure how to be honest.

https://github.com/INTI-CMNB/KiBot/blob/master/tests/yaml_samples/populate_with_filter.kibot.yaml This has filters defined, but it never references them in the populate task. Do I just define filters at the start of YAML, and that will apply to the `populate` and all other tasks? 

I've applied that here but I'm still seeing the fiducials/etc in the CPL file.

https://github.com/gcormier/kitritiled/blob/master/pcb/kibot.yaml

**Reply by gcormier** [reply]
Also note for DNF, there is nothing populated on the components added by KiKit. All I have is the names of them to go on, unless we request a KiKit change.

**Reply by set-soft** [reply]
Can you create a very small example, let say a couple of components, and explain which components are added by KiKit that should be removed?
I can then create a filter example and also add them to the default mechanical filter, which already removed fiducials when they have the correct reference (FID*).

**Reply by gcormier** [reply]
Sure thing - I'm stepping out to work, I will try to compile a full example for you, probably Wednesday evening.

In the meantime, in case these are of use, here is the panel I have generated and the BOM/CPL files. Note that KiKit recently made a change to include these as components in a panel.

[kitritiled-panel.kicad_pcb.txt](https://github.com/INTI-CMNB/KiBot/files/13349159/kitritiled-panel.kicad_pcb.txt)
[kitritiled-panel_cpl_jlc.csv.txt](https://github.com/INTI-CMNB/KiBot/files/13349160/kitritiled-panel_cpl_jlc.csv.txt)
[kitritiled_bom_jlc.csv.txt](https://github.com/INTI-CMNB/KiBot/files/13349161/kitritiled_bom_jlc.csv.txt)
[kitritiled.kicad_sch.txt](https://github.com/INTI-CMNB/KiBot/files/13349162/kitritiled.kicad_sch.txt)

**Reply by gcormier** [reply]
This should reproduce the issue

```
docker pull ghcr.io/inti-cmnb/kicad7_auto:latest
git clone https://github.com/gcormier/kitritiled
cd kitritiled
cd pcb

docker run -it --rm -v "$(pwd)":/data ghcr.io/inti-cmnb/kicad7_auto kibot -c /data/kibot-panel.yaml -b /data/kitritiled.kicad_pcb -d /data/out
docker run -it --rm -v "$(pwd)":/data ghcr.io/inti-cmnb/kicad7_auto kibot -c /data/kibot.yaml -b /data/out/kitritiled-panel.kicad_pcb -d /data/out -e /data/kitritiled.kicad_sch

```

Note that DRC notices this issue
![image](https://github.com/INTI-CMNB/KiBot/assets/8388983/a04ea907-a4d3-4118-902f-60bfb0efb484)

Perhaps KiKit should be excluding these from the POS files?

![image](https://github.com/INTI-CMNB/KiBot/assets/8388983/90c673dc-a99f-4f79-a11b-e3c79ca587e9)

**Reply by set-soft** [reply]
Hi @gcormier !
Looking at the example I see KiKit is missing the following attributes: 

- *board_only* To avoid warnings about a component that isn't in the schematic
- *exclude_from_pos_files* To avoid including it in the position files, the problem here 
-  *exclude_from_bom* To avoid including it in a BoM, not very important because the BoM is usually created from the schematic

**Reply by gcormier** [reply]
Do you think it's best if KiKit handles this as the outgoing provider instead of input filters on KiBot? I can circle back to KiKit to continue the discussion.

**Reply by set-soft** [reply]
Looking deeper in the problem: filters can't help here because they applied using information from the schematic, which doesn't really exist here (no schematic for the panel).

I can just add an option to exclude "KiKit_*" references, but this is a workaround, not a final solution.

The correct solution is to make KiKit behave nicely and mark the auxiliary footprints properly.

**Reply by yaqwsx** [reply]
@set-soft: At the moment, none of the attributes are set as the panel is inherently uncoupled from schematics. At the moment, there is no clear way of making an appropriate schematic for the panel (and there are no plans for dealing with that until there is schematic API).

I agree that: we should set `exclude_from_bom` as it makes sense. I will reflect this in the upcoming days.

I am not sure about setting `board_only` as there is no schematic connected to the panel. But from some perspectives, we can expect that these features are not in schematic (it can be questionable about fiducials and tooling holes).

I disagree about setting `exclude_from_pos_files` - the whole point of change was to include these items in the POS files as there are processes that require (at least tooling) holes to be present in the pos file. It's up to the POS file exported for *given manufacturer* and *purpose* to decide how to handle them. I dislike the option of specification how treat the footprints into panel as I already have users that export single panel for multiple manufacturers with different requirements on the inclusion of such footprints.

**Reply by gcormier** [reply]
Would it be possible to have an parameter in KiKit to determine if `exclude_from_pos_files` is set or not?

The root of this issue is that for JLC, they do not want fiducials/tooling in the POS. The changes proposed above to KiKit would not fix this issue.

**Reply by yaqwsx** [reply]
As I expressed above, deciding if tooling and fiducials should be included should be the decision of the POS export, not building the panel.

**Reply by set-soft** [reply]
>  At the moment, none of the attributes are set as the panel is inherently uncoupled from schematics. At the moment, there is no clear way of making an appropriate schematic for the panel (and there are no plans for dealing with that until there is schematic API).

The mentioned attributes are from the PCB. You can set them using FOOTPRINT::SetAttributes. The values are:

```python
# KiCad 6 module attributes from class_module.h
MOD_THROUGH_HOLE = 1
MOD_SMD = 2
MOD_EXCLUDE_FROM_POS_FILES = 4
MOD_EXCLUDE_FROM_BOM = 8
MOD_BOARD_ONLY = 16  # Footprint has no corresponding symbol
MOD_JUST_ADDED = 32  # The footprint was added by the netlist update
MOD_ALLOW_SOLDERMASK_BRIDGES = 64
MOD_ALLOW_MISSING_COURTYARD = 128
```

**Reply by set-soft** [reply, marked as answer]
Hi @gcormier !

I think that @yaqwsx is right about `exclude_from_pos_files`, is something that some people could want to include. Perhaps for special cases and in a separated file, not for pick and place.

Anyways, I managed to make KiBot include components from the PCB in the list of components to be processed by filters. You get a warning in this case, but not for *KiKit_* components because we know they are panel stuff.

So now you can apply a filter like this:

```yaml
kibot:
  version: 1

global:
  field_lcsc_part: LCSC

filters:
  - name: remove_extra
    comment: 'Remove KiKit auxiliary'
    type: generic
    exclude_any:
      - column: References
        regex: "^KiKit_"

outputs:
  - name: 'position'
    type: position
    dir: positiondir
    options:
      dnf_filter: remove_extra
      format: CSV
      separate_files_for_front_and_back: false
      only_smd: false
```

But if you want to create a file with reference positions you can use:

```yaml
kibot:
  version: 1

global:
  field_lcsc_part: LCSC

filters:
  - name: remove_extra
    comment: 'Remove KiKit auxiliary'
    type: generic
    invert: true
    exclude_any:
      - column: References
        regex: "^KiKit_FID"
      - column: References
        regex: "^KiKit_TO"

outputs:
  - name: 'position'
    type: position
    dir: positiondir
    options:
      dnf_filter: remove_extra
      format: CSV   # CSV or ASCII format
      units: millimeters  # millimeters or inches
      separate_files_for_front_and_back: false
      only_smd: false
```

Which generates:

```csv
Ref,Val,Package,PosX,PosY,Rot,Side
"KiKit_FID_B_1","Fiducial","Fiducial",15.0000,88.5483,0.0000,bottom
"KiKit_FID_B_2","Fiducial","Fiducial",77.3965,88.5483,0.0000,bottom
"KiKit_FID_B_3","Fiducial","Fiducial",15.0000,3.8500,0.0000,bottom
"KiKit_FID_B_4","Fiducial","Fiducial",77.3965,3.8500,0.0000,bottom
"KiKit_FID_T_1","Fiducial","Fiducial",15.0000,88.5483,0.0000,top
"KiKit_FID_T_2","Fiducial","Fiducial",77.3965,88.5483,0.0000,top
"KiKit_FID_T_3","Fiducial","Fiducial",15.0000,3.8500,0.0000,top
"KiKit_FID_T_4","Fiducial","Fiducial",77.3965,3.8500,0.0000,top
"KiKit_TO_1","NPTH","NPTH",5.0000,89.8983,0.0000,top
"KiKit_TO_2","NPTH","NPTH",87.3965,89.8983,0.0000,top
"KiKit_TO_3","NPTH","NPTH",5.0000,2.5000,0.0000,top
"KiKit_TO_4","NPTH","NPTH",87.3965,2.5000,0.0000,top
```

The JLCPCB template now has an internal filter to remove the *KiKit_* references, but you can change the filter from outside if needed.

Will be available in *dev* when I finish adapting the test cases.
