### DISCUSSION TITLE
[HOW] Best practice setup CI/CD for Kibot

### DISCUSSION THREAD

**Discussion by Nudelsalad** [INTI-CMNB/KiBot#596] [Q&A]
I am figuring out the best approach to have a pipeline running for all my kicad projects stored inside Gitlab.

I am currently seeing therefore three approaches:

## Most general one:

- Inside every project there is the same simple Gitlab-ci.yml file pointing to a generous Gitlab-ci.yml inside the config repository. There the general CI/CD Workflow is defined and the kibot jobs get executed at a certain event(push/merge/tag) with the same config.

Current Problem:

- specifying a different fabricator yaml can be done via an environment variable which gets passed to the yaml in the CI -> not very handy
- no fix amount of parameters, varies from project to project so yaml substitution or preprocessing by overwriting a different amount and different parameters seems impossible

Advantages:

- no hardware guy needs to touch a kibot.yaml

Disadvantages:

- no further yaml substitution and preprocessing possible without having to much Gitlab-ci variables involved

For me it is very important to have always a fine grained control on what is being outputted, if nothing is specified or no kibot.yaml is found inside the project it takes a generous one. Therefore I figured out the following 2 approaches(first might be impossible?):

## First idea

1.  Defining the output jobs for every manufacturer with the **same *output ==names==***
2.  Putting a kibot.yaml file into every repository which gets executed by pipeline if exists
3.  importing the default config and the needed config (e.g.:JLCPCB) after that (to let overwrite the default output configs of existing outputs with those of JLCPCB)
4.  executing kibot in CI to execute the output jobs

Advantages:

- if no fine grained control wished, no hardware guy needs to touch a kibot.yaml
- fine grained control possible

Disadvantages:

- having the same name for outputs here is important to not make any changes to CI necessary
- only works if existing outputs gets overwritten if an output with the same name occurs

So my question now:

Does kibot only concatenate the yaml files or does he also substitute already defined outputs where the output name is the same with the imported ones?

## Second idea (workaround to this problem)

An option would be to define only certain jobs in one file and to import the rest where the fabrication outputs all have the same name.

Generous file in every repo (or if nothing is found, take always a generous one with imported default.kibot.yml fabrication outputs):

Needs to be specified inside every fine grained controlled repository:

**main.kibot.yaml**

```
BOM, IBOM, 3D model, kiri
Import config here # needs to be set by hand
# YAML substitution or preprocessing now possible
```

fabrication output jobs where the output names are the same so the CI can call them seamlessly all with the same name

**default.kibot.yaml**  
gerber, drill, pick and place

**jlpcb.kibot.yaml**  
gerber, drill, pick and place

Your internal templates for outputs provide all different names for outputs, this is why I ask this question. Also maybe as a kind of guideline to setup CI/CD workflow for me and others.

Interesting to know would also be if I import an anchor of the same name if this does overwrite the settings

I have already running the first mentioned approach. Kind of unhappy that no fine grained control is possible there. Seeing forward to your expertise @set-soft and contributing this to the docs if wished to help future me and others.

**Comment by set-soft** [comment]
Hi @Nudelsalad !

Your description is somehow abstract, so I'm not sure i get the full idea.

The first thing that comes to my mind: Why don't you just generate fabrication stuff for all the manufacturers you need could need and then let the user choose the one that's needed for the current project?

> Does kibot only concatenate the yaml files or does he also substitute already defined outputs where the output name is the same with the imported ones?

Outputs must have unique names. In order to "concatenate" outputs you must explicitly *extend* an output. If you import an output with an already defined name you'll get an error.

> Interesting to know would also be if I import an anchor of the same name if this does overwrite the settings

YAML anchors are local to a file, they don't get propagated to other files.


From your description it looks like you need some extra logic. I don't fully understand what do you think is simple and what isn't. You mention that defining an environment variable isn't simple ... but it looks like adding extra files is simple for you ...

Also note that you can use groups to simplify the KiBot invocation. So you can have groups like "sch_docs", "pcb_docs", "render", etc. And then also define things like "fab_manf1", "fab_manf2", etc. So then you call KiBot asking for the outputs you want, i.e. "pcb_docs render fab_manf2"

**Comment by oliv3r** [comment]
@Nudelsalad You are in luck! I just released v0.2.0 of my [gitlab pipeline component](https://gitlab.com/explore/catalog/ci-includes/kici). It's so new, I haven't properly introduced it to @set-soft yet :D (I was about to actually :p, but have one tiny pdf scaling issue left to resolve).

If you want to know how to 'use' this component, I've also got you covered (besides the self-test and readme of the repo)!

I've been working on https://gitlab.com/riglol/lapod as my test repo-ish, to get this pipeline component working. I'm now in the process of adding the pipeline component to my other kicad projects too ;) literally years I was too lazy to do so.

The rigol/lapod repo hasn't been merged to master and tagged for release yet, so you don't see the 'release process' yet there (should happen in a few days), but the component repo itself does actually tag and release itself, with a hello-world demo project.

P.S. Note that it currently relies on kibot:dev, though (after the pdf bug) we could hopefully release kibot v1.6.4 soon! (hint hint).

Feel free to reach out if things are not clear (and thus the documentation needs improvement). Yes, it is a bit tricky to first grasp and set it up. But once it runs, it's amazing!

The really dumb 'TL;DR' version is
```yaml
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2024 Olliver Schinagl <oliver@schinagl.nl>

include:
  - component: gitlab.com/ci-includes/kici/gitlab-component@v0.2.0
    inputs:
      stage_lint: 'lint'
      stage_build: 'build'
      attach_diff: 'true'
      projects: 'breakout_hdmi breakout_hdmi_mini pod_lmh7322 pod_lmh7324 pod_sn65lvds'
  - component: gitlab.com/ci-includes/pipeline-deployers/release-announcer@v0.1.0
    inputs:
      release_assets: 'assets/release.json'
      release_dependency: 'kici_deploy'
  - component: gitlab.com/ci-includes/pipeline-deployers/release-brancher@v0.1.0
  - project: 'ci-includes/masslinter'
    ref: 'master'
    file: 'all-linters.yml'

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH =~ /^release\/v\d+.\d+$/'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - lint
  - build
  - branch
  - deploy
  - complete

default:
  tags:
    - docker
```
as your `.gitlab-ci.yaml` file, and submodule/clone/copy/create a `.kibot` folder in the root of your repo that holds your (properly named) `kibot.yaml` file. This is the hard part to get right ... as it relies on the proper naming and/or symlinks
