### DISCUSSION TITLE
External Libraries & Templates

### DISCUSSION THREAD

**Discussion by JackFGS** [INTI-CMNB/KiBot#624] [Q&A] [answered]
Good Afternoon,

Ive been struggling to setup github CI/CD for a couple of days now and I'm stuck!

Is there a way to include external libraries / templates to the container?

We use google drive and I have the drive mapped in the Linux GitHub runner but I cant see a way of adding it in the yaml?

Please see below any suggestions would be appreciated 

```yaml
name: example

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.yaml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.yaml'
  workflow_dispatch:
jobs:
  example:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: config.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: '*.kicad_sch'
        # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
```

**Comment by set-soft** [comment]
I never used Google Drive for GitHub projects, what are you using to integrate it?

Normally you put your libs in another repo. Then you use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). In this way the libs becomes part of the project, but you update them only in one repo. Note that you need to do some update in the repos using the lib, but is just a command, the changes are done in the lib repo.

This is the most common case.

**Reply by JackFGS** [reply, marked as answer]
I have finally managed to make it work today,

I have mounted google drive in the runner using https://github.com/astrada/google-drive-ocamlfuse and the yaml below!

```
 runs-on: [self-hosted, linux]
    container: 
      image: ghcr.io/inti-cmnb/kicad8_auto_full:latest   # Don't Change, except if needing older version of KiCad.
      options: -v /DRIVE:/src/Gdrive   
    steps:  
    - uses: actions/checkout@v4
    - name: Remove OUTPUT Dir
      run: |
        rm -rf ./OUTPUT
    - name: Run KiBot
      run: |
        kibot -c ./config.kibot.yaml
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
       name: OUTPUT
       path: OUTPUT
```

**Reply by set-soft** [reply]
Interesting! 
Are you installing the [google-drive-ocamlfuse](https://github.com/astrada/google-drive-ocamlfuse) tool in a local runner?

**Comment by cyberreefguru** [comment]
To add to the question, how does one do the same thing when the user libraries are in a repo and you are using CI/CD? Hours of searching have turned up no answer.

Example, I have KICAD_USER_MODEL_DIR set to the location on my local drive when I'm using kicad manually -- how do I set this variable in kicad within docker when using CI?

I can pull the libraries into docker from git, but I don't know how to 'tell' kicad that is the user directory?

Specifically interested in:
KICAD8_3RD_PARTY
KICAD9_3RD_PARTY
KICAD_USER_MODEL_DIR
KICAD_USER_TEMPLATE_DIR

(though I don't think template dir is used).

I feel like this is trivial but I can't seem to find an answer (yet).

-Tom

**Reply by set-soft** [reply]
Did you try using the `environment` option from the `global` options?

**Reply by cyberreefguru** [reply]
I have not -- I will look into that. Thanks!

**Reply by cyberreefguru** [reply]
Hi Salvador -- I implemented global variables and also implemented some options for pcbdraw, but it's not clear they are working. I'm still getting warnings of missing libraries even though the libraries are available (based on listing the directory and echoing the output).

```
- 'Print schematic (PDF)' (print_sch) [pdf_sch_print]
- 'Top layer view' (board_top) [pcbdraw]
WARNING:(W103) (component) Component Resistor_SMD:R_0603_1608Metric has no footprint. (kibot - out_pcbdraw.py:45)
WARNING:(W103) (component) Component Capacitor_SMD:C_0603_1608Metric has no footprint. (kibot - out_pcbdraw.py:45)
```

These specific components are symlinks but that should not be a problem as far as I can tell -- they look fine when I pull the repo manually.

Snippet of my kibot.yaml:

```
  - name: board_top
    comment: "Top layer view"
    type: pcbdraw
    dir: doc
    options:
      output: power-module-pcb-top.png
      libs: 
        - pcbdraw/KiCAD-base
        - pcbdraw
      format: png
      margin: 5
      show_solderpaste: false
      show_components: all
      warnings: visible
```

and my git workflow:

```
    - name: Checkout PcbDraw Library
      uses: actions/checkout@v4
      with:
        repository: yaqwsx/PcbDraw-Lib
        path: pcbdraw
```

Or you can view here: https://github.com/crgmakes/module-power

Any suggestions? 

I'd like to get this working but it's not a big deal if it doesn't.

Everything else is great, so kudos to you for the great work!

-Tom
