### DISCUSSION TITLE
How to use drc_exclusions_workaround?

### DISCUSSION THREAD

**Discussion by DaAwesomeP** [INTI-CMNB/KiBot#645] [Q&A]
Hello!

I have `drc_exclusions_workaround` in my config like this:
```yaml
global:
  drc_exclusions_workaround: true

preflight:
  drc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
  erc:
    dont_stop: true
    format: HTML,RPT,JSON,CSV
```
However, I am still seeing DRC errors and warnings in KiBot that I excluded from the UI in KiCAD. Do I need to specifically save these exclusions somehow? The docs here don't say anything more: https://kibot.readthedocs.io/en/master/configuration/global.html

Thanks!
