### DISCUSSION TITLE
How to send ERC DRC report to a different directory

### DISCUSSION THREAD

**Discussion by Strooom** [INTI-CMNB/KiBot#675] [Q&A] [answered]
I am using KiBOT in a CI workflow from github actions.
I would like to send all generated output (renders, pdfs, etc) to a dedicated directory, which I then add to the repository rather than attaching as a .zip of artifacts.
It's working ok for renders and schematics, but not for the ERC and DRC reports, so I'm probably not using the right syntax in the yaml file.

The github action defines a general outputs directory : 
```
      - name: run KiBOT export
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          additional_args: '--verbose'
          config: config.kibot.yaml
          dir: outputs
```
Then in config.kibot.yaml I have
```
preflight:
  erc: true
  drc: true
  check_zone_fills: true
  dir: reports
```
expecting the reports to go to outputs/reports, but that does not work.
The docs (https://kibot.readthedocs.io/en/master/configuration/preflights/erc.html) mention that I could use a erc: 'dict', but I don't know what syntax to use here.. 
As it's running on a github actions runner, it's also not easy to quickly experiment or try and error.
Any example of how to use extra options with the erc: and drc: preflight actions ?

**Comment by set-soft** [comment]
> expecting the reports to go to outputs/reports, but that does not work.

Look in the logs where are the ERC reports stored, also try *-vvvv* instead of just *--verbose*

> The docs (https://kibot.readthedocs.io/en/master/configuration/preflights/erc.html) mention that I could use a erc: 'dict', but I don't know what syntax to use here..

The *ERCOptions parameters* link explains the available options.

> As it's running on a github actions runner, it's also not easy to quickly experiment or try and error.

So just run it in your machine! Download docker, pull the docker image and run it locally.

> Any example of how to use extra options with the erc: and drc: preflight actions ?

https://github.com/INTI-CMNB/KiBot/tree/master/tests/yaml_samples

Look for files named *erc_k8* and similar

**Comment by Strooom** [comment, marked as answer]
Thanks, 
most of the examples still use the older 'run_drc' style, but I managed to find the solution in there anyway. 
So
```
preflight:
  erc: true
  drc: true

```
becomes
```
preflight:
  erc:
    dir: 'reports'
  drc:
    dir: 'reports'

```
Specifying options simply means you list them below 'erc:' in a section with one more indent
