### DISCUSSION TITLE
Github actions and KiBot with monorepo

### DISCUSSION THREAD

**Discussion by usbalbin** [INTI-CMNB/KiBot#683] [Q&A] [answered]
What is the best practice for setting up KiBot github actions for a monorepo like this?
```bash
hardware/
  pcb_foo/
    pcb_foo.kicad_sch
    pcb_foo.kicad_pcb
  pcb_bar/
    pcb_bar.kicad_sch
    pcb_bar.kicad_pcb
firmware/
  ...
```
Where do I put the kibot config files? In the root or inside the corresponding subdirectory? How do I get the KiBot action to run in the sub directory(or should I)?

**Comment by set-soft** [comment]
> Where do I put the kibot config files? In the root or inside the corresponding subdirectory?

I'll suggest the last.

> How do I get the KiBot action to run in the sub directory(or should I)?

You don't need to do it. You just need to provide the names including the directory. The GitHub Action will run at the root of the workspace.

**Reply by usbalbin** [reply, marked as answer]
> You don't need to do it. You just need to provide the names including the directory. The GitHub Action will run at the root of the workspace.

So something like this?

```yml
name: '...'
on:
  [...]
jobs:
  pcb_foo:
    #<checkout etc...>
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: 'hardware/pcb_foo/config.kibot.yaml'
        schema: 'hardware/pcb_foo/pcb_foo.kicad_sch'
        board: 'hardware/pcb_foo/pcb_foo.kicad_pcb'
        dir: pcb_foo # <--- Where the generated outputs will be placed relative to repo root?

  pcb_bar:
    # <more or less same as pcb_foo>
```
