### DISCUSSION TITLE
Generate gerber for panel

### DISCUSSION THREAD

**Discussion by usbalbin** [INTI-CMNB/KiBot#687] [Q&A] [answered]
Hi!

When panelizing a PCB what is the best way to generate gerbers from the panel? From what I can tell, the ['panelize'](https://kibot.readthedocs.io/en/master/configuration/outputs/panelize.html) config can only generate a preview.

```yaml
- name: 'panel'
  type: 'panelize'
  options:
    configs: 'panel.json'
    create_preview: true
```

Should this be done as two steps? First run kibot for the single pcb, run DRC etc and then generate the panel project. Then invoke kibot a second time, this time for the previously generated panel project to generate the gerbers?

Or am I missing something? :)
