### DISCUSSION TITLE
Panel Origin

### DISCUSSION THREAD

**Discussion by Thorfinn-Thorsson** [INTI-CMNB/KiBot#740] [Q&A] [answered]
Hi @set-soft ,

Love your work!!

Quick question: 
Is it possible to set a Arbitrary Point/Footprint/FID/Tooling Hole as the origin for a Panel and not just the `tl,bl,tr...,br`?
For example, I would like the FID that we generate on the bottom left of the Panel to be the origin point?

**Comment by set-soft** [comment]
Hi @Thorfinn-Thorsson !
All the panelization process is done by KiKit and from what I see it only supports the tl,tr,bl,br,mt,mb,ml,mr,c options.
You should create a Feature Request issue at the KiKit project.

**Comment by Thorfinn-Thorsson** [comment]
For others who are interested, you can do something like the following.

Using a custom fiducial plugin like this one.
[FiducialPlugin.py](https://gist.github.com/Cimos/3d149678255046562186e129dc640e8e)

Then add it to your panel config like this.

```yaml 
fiducials:
            type: plugin
            arg: ' --panel 5 5 --board -2.5 2.5'
            code: 'FiducialPlugin.py.CustomFiducialPlugin'
```

**Comment by set-soft** [comment, marked as answer]
I faced a similar problem and used another solution, here is the script:

```python
def kikitPostprocess(panel, args):
    board = panel.board
    for m in board.GetFootprints():
        if m.GetReference() == args:
            center = m.GetCenter()
            print(f'Changing origin to {center}')
            panel.setAuxiliaryOrigin(center)
            panel.setGridOrigin(center)
```

Then you can just add the following post-process to KiKit's JSON file:

```json
    "post": {
         "script": "move_origin.py",
         "scriptarg": "KiKit_FID_T_3"
    },
```

Where *KiKit_FID_T_3* is the name of the fiducial you want to use as origin. If you don't know it just open the panel with pcbnew and select the fiducial you want, just use the reference of the footprint here.

If not using a separated JSON, but KiBot's YAML use:

```yaml
   post:
    script: move_origin.py
    scriptarg: KiKit_FID_T_3
```
