### DISCUSSION TITLE
How to zoom out or offset PCB when 3D render? 3D models truncated.

### DISCUSSION THREAD

**Discussion by dhaillant** [INTI-CMNB/KiBot#771] [General]
Hello,
I'm using KiBot to generate 3D iso style views to show how components are located on the boards.
Sometimes, the 3D models get truncated.
Often I can adjust/tweak the resolution to get a better result, but sometimes, the 3D models just get truncated.
![example](https://github.com/user-attachments/assets/ecff8caa-a940-4a54-bcce-439ad28d1632)
In this example, the top right potentiometer isn't showing completely.

This is the YAML code I use:
```
  - name: iso_3d
    comment: 3D ISO view
    type: render_3d
    dir: PCB%v/png
    output_id: iso
    options:
      output: '%p-%r-%i%I%v-%D.%x'
      rotate_x: 5
      rotate_z: -6
      width: 3000
      height: 2000
      orthographic: true
```

Is there a way to zoom out or offset/translate the PCB so that bigger components stay visible?
Thanks!
David
