### DISCUSSION TITLE
Use KiBot compress to archive a entire folder

### DISCUSSION THREAD

**Discussion by alextrical** [INTI-CMNB/KiBot#798] [Q&A] [answered]
Good Day

Im currently looking to compress the entire contents from a folder, pupulated by a few different steps in a KiBot worflow

Specifically im looking to add the contents of a folder at './Panel_2x1/JLCPCB' to a zip file.

The code im using is the folowing
```
outputs:
  - name: JLCPCB_manufacturing_output
    type: compress
    options:
      format: ZIP
      source: './Panel_2x1/JLCPCB'
      output: 'JLCPCB_manufacturing_files.zip'
```
or 
```
outputs:
  - name: JLCPCB_manufacturing_output
    type: compress
    options:
      format: ZIP
      source: '*'
      # from_cwd: true
      output: 'JLCPCB_manufacturing_files.zip'
```
or
```
outputs:
  - name: JLCPCB_manufacturing_output
    type: compress
    options:
      format: ZIP
      files:
        - source: JLCPCB/*
          from_cwd: true
          dest: source
        - source: Panel_2x1/JLCPCB/*
          from_cwd: true
          dest: source
```

The resulting zip file is devoid of any contents, any advice is greatly appreciated
Kind regards
Ben J

**Comment by set-soft** [comment, marked as answer]
Hi @alextrical !

In the first and second example you don't specify any files. And KiBot informs it like this:

```
WARNING:(W015) Unknown option `source` (kibot - optionable.py:224)
WARNING:(W050) No files provided, creating an empty archive (kibot - out_compress.py:99)
```

You must pay attention to the warnings!!

The third example might work ... as long as you really run it from the folder where `Panel_2x1/JLCPCB/` is located. 
Note that you are asking for a ZIP file containing a folder named `source` that contains the files from `./Panel_2x1/JLCPCB/` and `./JLCPCB/`. 

You should check the files listing the files, i.e. using `ls`. Assuming you are using the script from #797 
1. Open a terminal
2. Change to the working directory
3. Use `ls Panel_2x1/JLCPCB/*` to see if the files are there
4. Run KiBot using the third example

You might also want to specify absolute paths during tests.

**Reply by alextrical** [reply]
Hi @set-soft 

Once again thank you for your assistance.
You are correct that I overlooked the error message, I was attempting to use it in a GitHub Action and didnt spot the warning.

I have created a basic test and can confrim that the 3rd snippet does indeed work as expected, in a folder structured like this 
<img width="824" alt="image" src="https://github.com/user-attachments/assets/f88dded1-59dc-485d-9b48-e9353312f6ba" />

```
outputs:
  - name: JLCPCB_manufacturing_output
    type: compress
    options:
      format: ZIP
      files:
        - source: JLCPCB/*
          from_cwd: true
          dest: source
        - source: Panel_2x1/JLCPCB/*
          from_cwd: true
          dest: source
 ```
 
 Though clearly I have mis calculated the working directory its running at inside of the GitHub action.
 
 Thank you for your assistance in confirming that the function is suitable for my needs.
 
 Many thanks
 Ben J
