### DISCUSSION TITLE
[HOW] Generate paste layers without Do Not Populate (DNP) components

### DISCUSSION THREAD

**Discussion by montirafa** [INTI-CMNB/KiBot#809] [Q&A]
**What do you want to achieve?**
Generate paste layers without Do Not Populate (DNP) components. The global `remove_solder_paste_for_dnp: true` is not enough.

**Do you have some PCB/Schematic to use as example?**
I can't share the original project, but I also tested it using the project shared in  [issue 784](https://github.com/INTI-CMNB/KiBot/issues/784) 

[test.zip](https://github.com/user-attachments/files/19762114/test.zip)

**Do you have some configuration file (.kibot.yaml) that you are using?**
Edited file:
```yaml
kibot:
  version: 1

global:
  remove_solder_paste_for_dnp: true
variants:
  - name: 'Test'
    comment: 'Some useful comment'
    type: kibom
    file_id: '_Test'
    variant: ''

outputs:
  - name: 'gerber_default'
    comment: 'Generate Gerbers (Default)'
    type: 'gerber'
    dir: 'Gerbers'
    layers:
      - F.Paste
      - B.Paste
    options:
      disable_aperture_macros: true
      exclude_pads_from_silkscreen: true
      output: '%f-%r-%v-%i.%x'
      plot_footprint_values: false
      subtract_mask_from_silk: true
      use_aux_axis_as_origin: true
      use_gerber_net_attributes: false
      use_gerber_x2_attributes: false
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? GitHub
- In a GitHub action? Which tag are you using? v3
- Using a docker image? kicad8_auto:1.8.4-2_k8.0.8_d12.7
- Using a desktop system? Which OS, distro and version? -
