### DISCUSSION TITLE
Export SVG with outlines of THT pad holes

### DISCUSSION THREAD

**Discussion by dhaillant** [INTI-CMNB/KiBot#835] [Missing in my workflow]
Hello,
I can't find a way to export a simple SVG that includes outlines for the THT pad holes.

The goal is to prepare files for a K40 laser engraver, which requires specific colors assigned to different tasks (e.g., blue for engraving, red for cutting).

I'm able to output individual layers for engraving (e.g., silkscreen in blue for engraving)

While `edge.cuts` layer exports cleanly for cutting, I'm unable to include THT holes outlines.

The only workaround I've found is using **PCB Print** output with a copper layer.
But this generates a very complex SVG  (with solder masks and redundant objects), requiring manual cleanup in Inkscape.

Is there a simpler method to export THT hole outlines as SVG paths?
Thank you for your time and help!
David

KiBot 1.8.3 - Copyright 2018-2024, Salvador E. Tropea/INTI/John Beard - License: AGPL v3
KiCad Version: 8.0.9-8.0.9-0~ubuntu22.04.1, release build

**Comment by set-soft** [comment]
If color is what really encodes the cut you can try this:

```yaml
kibot:
  version: 1

outputs:
  - name: 'print_front'
    comment: "Red holes"
    type: pcb_print
    options:
      format: 'SVG'
      scaling: 2
      colored_vias: false
      colored_pads: false
      plot_sheet_reference: false
      add_background: true
      pages:
        - layers:
            - layer: F.Cu
              color: '#FFFFFFFF'
            - layer: Edge.Cuts
              color: "#FF0000"
          page_id: F_Cu_color
          colored_holes: true
          holes_color: '#FF0000'
```

Using the *light_control* example I get:

![light_control-assembly_page_F_Cu_color](https://github.com/user-attachments/assets/2a96d8a3-3134-456c-b45e-964983abced9)

I scaled it to 2 just to make it bigger, I guess you won't need it.
This SVG contains the tracks, pads, etc. but all in white, so they aren't even visible. 
The edge and holes are all in red. 
Note that this includes holes for the vias.
