### ISSUE TITLE
3D Model variants (related or not to BOM variants)

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#103]
# Summary

Allow removing STEP submodel filtering based on variants.  
Currently the STEP models are filtered based on the fact that the component is present or not, but I have multiple models for a single component that correspond to component variants.

# Discussion

I tend to make footprints that allow different types of components in the same spot.

Some developers will suggest to make two different footprints and put them in the same spot, but then we have to cope with overlapping footprints and footprint alignement, etc.

One good example is the choice between a surface mount push button or a through hole push button:
![image](https://user-images.githubusercontent.com/1504752/141644890-fcda7ffa-d3cc-47bd-b027-c502d936d148.png)

I also do Fuseholders, DC jacks, rectifying diode bridges, ethernet jacks, wire-to-Board connectors, etc. this way when possible.  Sometimes it's just one component type, but I add the connectors mating part, the 3D model for the case (my Edges are defined in a footprint where I add a 3D model of the casing when available).

In the 3D modeling setup, I add both the THT and SMD components (sometimes even 3), one on top of the other.   That allows me to check that they are all compatible for instance.

In the case of an ethernet connector, I'ld have a variant in the BOM setup to select either the THT type or SMD type, in other case I do not have a variant because I don't care about the type.

3D models are not managed by variants for the same component, and there is not really provisioning in KiCAD that helps us to manage that.

I see that the STEP output is generated by removing 3D models.

I suggest to a model filtering feature to the STEP output generation which allows us to remove models from the output.

Suggestion:
```yaml
- name: 'step with model variants'
  type: step
  variant_options:
      - variants: [ v1, v2 ]  # variant names defined in yaml configuration
        footprint: AV:SW-PHAP3301E_dual # Optional
        refs: "SW[12]" # Optional, filter applied only to these references
        keep: ".*B3F.*" # Keeps only the models matching the reference, full path match
        remove:  ".*430182070816.*" # removes the matching models, full path match, useless with keep.
      - variants: [ v3 ]
        footprint: ".*:OtherFootPrint" # Optional, regex, must also cope with rescue library
        refs: "^(U10|U11)$" # Optional, applies only to refs.
        remove:  ".*SMD.*" # removes the matching models, full path match, useless with keep.
```
