### ISSUE TITLE
Override "output" (& other) options from imported yaml

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#112]
Importing Yaml configuration files is excellent for setting up common outputs/filters accross projects.

Most targes do not need to be specialised for a project, but there are cases where overriding some values would be helpful.

For example, for the 3D output the general configuration is ok, but the output size needs to be adjusted.

With this in the imported file ('common/common.kibot.yaml'):
```
kibot:
  version: 1

outputs:
  - name: "render_2d_top"
    type: render_3d
    dir: "+PCBA"
    options:
      id_add: "_2d"
      no_tht: false
      no_smd: false
      no_virtual: true
      background1: "#66667F"
      background2: "#CCCCE5"
      board: "#332B16"
      copper: "#B29C00"
      silk: "#E5E5E5"
      solder_mask: "#143324"
      solder_paste: "#808080"
      move_x: 0
      move_y: 1
      ray_tracing: false
      wait_ray_tracing: 5
      view: "z"
      zoom: 5
      #width: 2560
      #height: 720
      orthographic: true
```

The following in project configuration file would allow us to override some values.  In the example: solder mask color, zoom and output size.
The name is used as a unique key:

```yaml
kibot:
  version: 1

import:
  - common/common.kibot.yaml

outputs:
  - name: "render_2d_top"
      solder_mask: "#030303"
      zoom: 10
      width: 2560
      height: 720
```
