### ISSUE TITLE
Missing tool option(s) - kicost "split_extra_fields"

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#120]
KiBot 0.11.0 

I was looking to add 'split_extra_fields' to the kicost parameters, but this was not available.  The 'board_qty' seems to be missing as well.

I suppose that the goal is that tool options are made available as yaml options, but keeping up with that may be a burden.  Maybe there should be a more generic options that allows the user to add any option to the tool's execution.

**Comment by set-soft** [comment]
I added them, but didn't test if they work. Please let me know it.

About the generic option: not sure ... this will kill the report of issues like this one ... if you take a look at the patch you'll see it adds interesting stuff.

**Comment by mdeweerd** [comment]
I did not get a complaint from the tool for the split.. option, but I haven't verified its effect yet.

"board_qty" failed:
```
WARNING:(W015) Unknown option `board_qty` (kibot.optionable - log.py:88)
```

And the `fields` option just adds a single column with the header "comment,S1MN,S1PN,S2MN,S2PN":
```yaml
  - name: 'kicost'
    type: kicost
    dir: "+PCBA"
    options:
      currency: [ EUR ]
      no_collapse: true
      no_price: true
      fields:
        - comment
        - S1MN
        - S1PN
        - S2MN
        - S2PN
      board_qty: 1
      show_cat_url: true
```

I yet have to look for the generic option (it's a 'bit' late here).
