### ISSUE TITLE
"Extends" & "date_format" feedback following "test"

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#121]
Hi @set-soft
This is related to #116 and #112 .

I just put the "extends" option into practice.  Which allowed met to adjust the 3D rendering outputs to a black solder mask as well as adjusting zoom and offset:
```yamloutputs:
  - name: render_2d_top_black
    type: render_3d
    extends: render_2d_top
    dir: "+PCBA"
    disable_run_by_default: render_2d_top
    options:
      zoom: 10
      width: 4096
      solder_mask: '#1A1A1A'
      copper: '#2A2A2A'
      move_y: 1
      height: 1024
  - name: render_2d_bottom_black
    type: render_3d
    extends: render_2d_bottom
    dir: "+PCBA"
    disable_run_by_default: render_2d_bottom
    options:
      zoom: 10
      width: 4096
      solder_mask: '#1A1A1A'
      copper: '#2A2A2A'
      move_y: 1
      height: 1024
  - name: render_3d_top_black
    type: render_3d
    extends: render_3d_top
    dir: "+PCB"
    disable_run_by_default: render_3d_top
    options:
      zoom: 8
      width: 4096
      solder_mask: '#1A1A1A'
```

Some observations:
- The option 'type' needs to be specified, but we could assume that this option is provided due to "extends".
- disable_run_by_default: it's ok, but I expected this to be a boolean (disable the parent rule or not).  This is more flexible though as one can disable another rule that extends the same "template".
- The dir option is not inherited (I had '+PCBA' and '+PCB' but the output was in the root of the global output directory), so I set them again (see example above).
- The output type 'bom' does not support the 'id_add' option
- I did not get the expected dateformats with the following configuration - I removed time from the date_time_format as my "out_dir" has two underscores ('_') between %d and %g:
```yaml
global:
  output: "%f_%r_%d-%i.%x"
  #out_dir: "%f_%br_%bd_%g/"
  out_dir: "%bf_%r_%d_%g/"
  date_time_format: '%Y%m%d_%H%M%S'
  date_format: '%Y%m%d'
  time_format: '%H%M%S'
  variant: '5V_3btn'
  # variant: 'proto'
  #date_time_format: '%Y%m%d_%H%M%S'
  date_time_format: '%Y%m%d'
  date_format: '%Y%m%d'
  time_format: '%H%M%S'
```
