### ISSUE TITLE
Temporary project file for "kicad2step" should be deleted

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#124]
Some temporary files are left behind such as 'tmpie2w2az0.pro'.
It turns out that this was used for the kicad2step script.

My step output is specified like this:
```yaml
  - name: 'step'
    comment: 'Exports the PCB as a 3D model.'
    type: 'step'
    dir: "+STEP"
    options:
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      # dnf_filter: ''
      # [boolean=true] Downloads missing 3D models from KiCad git. Only applies to models in KISYS3DMOD
      # download: true
      # [string='https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'] Base URL for the KiCad 3D models
      # kicad_3d_url: 'https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'
      # [boolean=true] Use metric units instead of inches
      metric_units: true
      # [number=-1] The minimum distance between points to treat them as separate ones (-1 is KiCad default: 0.01 mm)
      # min_distance: -1
      # [boolean=false] Used to exclude 3D models for components with 'virtual' attribute
      no_virtual: true
      # [string='grid'] Determines the coordinates origin. Using grid the coordinates are the same as you have in the design sheet.
      # The drill option uses the auxiliary reference defined by the user.
      # You can define any other origin using the format 'X,Y', i.e. '3.2,-10'
      origin: 'grid'
      # [string='%f-%i%v.%x'] Name for the generated STEP file (%i='3D' %x='step'). Affected by global options
      # output: '%f-%i%v.%x'
      # [string=''] Board variant to apply
      # variant: ''
```
