### ISSUE TITLE
Unknown option `invert_bottom`

### ISSUE THREAD

**Issue by SukuWc** [INTI-CMNB/KiBot#136]
## Problem
I'm trying to automate the generation of double sided PCBA manufacturing files but I can't figure out the bottom rotation. I would like to use the combination of negative_bottom and invert_bottom parameters but when adding invert_bottom I get an error message

## Github Actions error message:
```
kibot -e XY.sch -b XY.kicad_pcb -c XY.kibot.yaml -d mfg-bot -m kibot.mak
ERROR:In section ``fix_rotation` (rot_footprint)`: Unknown option `invert_bottom` (kibot.kibot.error - error.py:40)
make: *** [Makefile:15: kibot.mak] Error 7
```

## Environment
- Kicad 5.1.10

## relevant part of the .kibot.yaml file

```
filters:
  - name: 'exclude_any'
    type: 'generic'
    comment: 'Exclude logos, testpoints, fiducials and power'
    exclude_any:
      - column: Reference
        regex: '^(G|#|TP).*'
      - column: Value
        regex: '^.*(\(NF\)).*'

  - name: fix_rotation
    comment: 'Adjust rotation for JLC'
    type: rot_footprint
    negative_bottom: false
    invert_bottom: true
    rotations:
      - ["SOIC-16_74HC165", 90.0]
      - ["SOIC-16_74HC4051", 90.0]
      - ["SOT-23-5", 180.0]
      - ["SOT-23-6", 180.0]
      - ["SOIC-8W_FLASH", 90.0]

variants:
  - name: rotated
    comment: 'Just a place holder for the rotation filter'
    type: kibom
    variant: rotated
    pre_transform: fix_rotation
```
