### ISSUE TITLE
Support replacing project Text Variables

### ISSUE THREAD

**Issue by s-ol** [INTI-CMNB/KiBot#161]
With KiCAD 6, project-level text variables can be declared and expanded in schematic and pcb text, header block fields etc using `${VARIABLE}` syntax. After being configured in either the *Board Setup* or *Schematic Setup* menus, they are added to the `PROJECT.kicad_pro` JSON file under the `text_variables` key.

The schematic file contains only the variable references, not their values. By updating the `kicad_pro` file, the schematic is completely "updated".

The PCB file caches the variable values in `(property "VARIABLE" "VALUE")` fields, but reloads the current value from the `kicad_pro` file when pcbnew is started. The PCB can be "updated" by simply opening the file and saving it immediately.

This mechanism could be used as a cleaner way of accomplishing what `sch_replace` and `pcb_replace` have been used for so far.
A `set_text_var` preflight option could look like this:

```
set_text_var:
  STATIC_TEXT:
    text: "static text. not sure why, but might be useful if yaml is generated..."

  COMMIT_HASH:
    command: "git rev-parse --short HEAD"
```

And would just need to modify the `kicad_pro` JSON document.

**Comment by set-soft** [comment]
Hi @s-ol !
This is a good idea. I didn't investigate much about KiCad 6 variables (where are stored, when are applied, etc.), so you filled this gap ;-)
I implemented it in a way that is more similar to how `pcb_replace` and `sch_replace` are defined, so KiCad 5 users can easilly migrate to the new preflight.
In addition I added %X pattern expansion. This could help people using global variants.

**Comment by s-ol** [comment]
This is the error/warning I meant:

```
WARNING:(W075) Trying to reformat SCH time, but not in ISO format (${DATE}) (kibot.gs - gs.py:149)
WARNING:(W075) Problem: Invalid isoformat string: '${DATE}' (kibot.gs - gs.py:150)
```

And this [`pcbnew.ExpandTextVars(str, PROJECT)`](https://docs.kicad.org/doxygen-python/namespacepcbnew.html#ad3104172fde92d0ddbb1080e47a990b7) function looks right.

**Comment by set-soft** [comment]
Hi @s-ol !
The last patch (342fb40c59a05e4fb39c8180a8f17dd3acbbdb7e) should expand `DATE` before using it, please let me know if it works for you.

**Comment by set-soft** [comment]
> And this [`pcbnew.ExpandTextVars(str, PROJECT)`](https://docs.kicad.org/doxygen-python/namespacepcbnew.html#ad3104172fde92d0ddbb1080e47a990b7) function looks right.

I'm doing the expansion manually to have more control.

**Comment by s-ol** [comment]
Hey @set-soft, I'm still getting this issue with current master: (02a942c)

```
WARNING:(W075) Trying to reformat SCH time, but not in ISO format (${VCS_DATE}) (kibot.gs - gs.py:181)
WARNING:(W075) Problem: Invalid isoformat string: '${VCS_DATE}' (kibot.gs - gs.py:182)
```

Heres the start of my config:

```yaml
kibot:
  version: 1

preflight:
  check_zone_fills: true
  run_drc: true
  run_erc: true

  filters:
    - filter: 'Ignore R7/8 overlap with R7/8alt'
      error: 'courtyards_overlap'
      regex:  'Footprint R[78]'

  set_text_variables:
    - name: 'VCS_DATE'
      command: 'git log -1 --format="%as"'

    - name: 'VCS_REV'
      command: 'git rev-parse --short HEAD'
```
