### ISSUE TITLE
pdf_pcb_print title append accumulates

### ISSUE THREAD

**Issue by richardbarlow** [INTI-CMNB/KiBot#185]
If there is more than one `pdf_pcb_print` output and they append something to the title, it looks as if the appended values accumulate (so that latter output has both its and the previous outputs text appended). Example:

```yaml
  - name: "assy_front_pdf"
    type: pdf_pcb_print
    layers:
      - Edge.Cuts
      - F.Courtyard
      - F.Fab
    options:
      title: "+ - Front"
      output: "%f-assy-front_%sr.%x"

  - name: "assy_back_pdf"
    type: pdf_pcb_print
    layers:
      - Edge.Cuts
      - B.Courtyard
      - B.Fab
    options:
      title: "+ - Back"
      mirror: true
      output: "%f-assy-back_%sr.%x"

```

The PDF produced by `assy_front_pdf` has the title "Original - Front", the PDF produced by `ass_back_pdf` has the title "Original - Front - Back".
