### ISSUE TITLE
Add option to generate IPC-D-356 netlist file 

### ISSUE THREAD

**Issue by dbriscoe511** [INTI-CMNB/KiBot#197]
Some manufacturers require this, especially if they are testing the PCB in house. There are very few options available for this format, so it likely wont need more than:

```
  - name: board_d356
    comment: IPC-D-356 netlist file
    type: IPC-D-356
    dir: 
   output: 
```
