### ISSUE TITLE
Text substitution not performed in BOM title

### ISSUE THREAD

**Issue by dbriscoe511** [INTI-CMNB/KiBot#198]
A script input of:

```
 type: bom
 .....
      xlsx: 
        generate_dnf: true
        logo: false
        title: '%f BOM'
```
The resultant BOM title is "%f BOM" instead of "Myboard BOM"

If this is intended behavior, feel free to close this issue.
