### ISSUE TITLE
[HOW] Add multiple 3d-packages search paths

### ISSUE THREAD

**Issue by slimcdk** [INTI-CMNB/KiBot#204]
**What do you want to achieve?**
To configure multiple search paths for 3d-packages - like you do through the KiCAD GUI. I have a couple of libraries that do not place 3d-packages in the common KiCAD 3d-package directory.

**Do you have some PCB/Schematic to use as example?**
This is my project repo https://github.com/slimcdk/esp-stepper-servo
This is the libraries I'm including https://github.com/slimcdk/slimc-kicad-libraries

**Do you have some configuration file (.kibot.yaml) that you are using?**
My kibot config is composed by multiple files, but this sums a complete config for exporting a step file and a single image
```yaml
kibot:
  version: 1
  
preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: true
  set_text_variables:
    - name: date
      command: git log -1 --format='%as'
    - name: commit
      command: git log -1 --pretty=format:%h

global:
  output: "%f-%i.%x"

outputs:
  - name: step
    type: step
    dir: exports
    options:
      metric_units: true
      
  - name: render top
    type: render_3d
    dir: exports/renders
    options:
      height: 1000
      width: 1600
      zoom: 2
      download: true
      ray_tracing: true
      view: top
```

**Environment (please complete the following information):**
Where are you running KiBot:
Locally on Ubuntu 22.04 with KiCAD 6 and KiBot 1.1.0 and on GHA with latest Ubuntu and KiBot v2_k6 Action
