### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'distutils.sysconfig'

### ISSUE THREAD

**Issue by KyleHunter** [INTI-CMNB/KiBot#213]
**Describe the bug**
On my test project that has been working for a while, I now get this error on trying to produce schematic outputs.

`-c kibot_files/schematic-files.kibot.yaml -d KiBotOutput -b kicad_proj/test_kibot.kicad_pcb -e kicad_proj/test_kibot.kicad_sch
Traceback (most recent call last):
  File "/usr/local/bin/kibot", line 16, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/kibot/__main__.py", line [25](https://github.com/MicroType-Engineering/test_kibot/runs/6969702244?check_suite_focus=true#step:9:26)9, in main
    load_actions()
  File "/usr/local/lib/python3.9/dist-packages/kibot/kiplot.py", line 83, in load_actions
    from kibot.mcpyrate import activate
  File "/usr/local/lib/python3.9/dist-packages/kibot/mcpyrate/activate.py", line 31, in <module>
    from .importer import source_to_xcode, path_xstats
  File "/usr/local/lib/python3.9/dist-packages/kibot/mcpyrate/importer.py", line 7, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils.sysconfig'`

**To Reproduce**
```
kibot:
  version: 1

global:
  # Sets the default output filename for all generated files. You likely don't have to change this.
  output: "%i.%x"

preflight:
  sch_replace:
    date_command: git log -1 --format='%as' -- $KIBOT_PCB_NAME
    replace_tags:
    - tag: "version"
      command: echo $version
outputs:
  - name: "print_sch"
    comment: "PDF - print schematic"
    type: pdf_sch_print
    dir: "Schematic-Files"

  - name: "standard_bom"
    comment: "Standard csv BOM for upload to Octopart or similar"
    type: bom
    dir: "Schematic-Files"
    options:
      blacklist: "DNF*"
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
      columns:
        - Part
        - field: manf
          name: Manufacturer
        - References
        - Quantity Per PCB
```

**Environment (please complete the following information):**
Where are you running KiBot:
- Github Actions
- `v1_k6` and `v2_k6`. Both show it

**Additional context**
Something odd (I don't have much experience with Github actions) is that this isn't the first bug that a new version of Kibot is caused, yet using my fork of a known working version on Github will also show the error. It's like even when using a fork, it still references back to your branch.
