### ISSUE TITLE
[HOW] to make render_3d output deterministic for use in git

### ISSUE THREAD

**Issue by dariuskt** [INTI-CMNB/KiBot#215]
Hey!

I want that render_3d output image would be the same every time i render without changing anything in the project. Is there a way to achieve that?

I have created pre-commit hook in git to run kibot every time so that pdf, bom, images and gerbers would be kept up to date with a project.

Problem is that every time render_3d runs it will produce slightly different file and git will treat that as a change and in git history i have no way to know if there was a real change.
I had similar problem with pcbdraw, but solved that by using `format: jpg`
As render_3d produces png I suspect that png has some kind of timestamp or date inside that creates this problem.

Is there a way to convince render_3d produce jpg image instead of png? or maybe there is some option to exclude timestamps from png?

```yaml
  - name: pcb_image_3d_front
    type: render_3d
    options:
      output: 'docs/PCB_front.jpg'
      orthographic: true
      download: true
      solder_mask: '#104020'
      ray_tracing: true
      width: 1334
      height: 958
      view: top
      zoom: 5
```

- Using a docker image `setsoft/kicad_auto:ki6.0.5_Debian`
