### ISSUE TITLE
[BUG] Time-out waiting for 3d viewer to be responsive

### ISSUE THREAD

**Issue by Regressor** [INTI-CMNB/KiBot#216]
KiBot can't render 3d image of board complaining about non-responsive 3d viewer

How to reproduce:
Create a board with a component having link to 3d model of rpi cm4 module (https://datasheets.raspberrypi.com/cm4/CM4-step.zip) and try to get 3d image of it.

Expected behavior: KiBot renders 3d image of board. 
Real behavior: KiBot quickly (about a minute) throws time-out error

I'm running KiBot in gitlab ci environment using setsoft/kicad_auto:10.4-5.1.6 image
I tried to change resolution, view and other parameters but result is same.

I started render_3d action with -vv key and then examined .ogv video file. The pcbnew 3d viewer screen shows clock cursor and a status text in bottom left angle "Loading cm4.step"

**Comment by set-soft** [comment]
Hi @Regressor !
This is a very particular 3D model, I tried it using an old i5 (i5-2310) and it took 47 seconds to be rendered (the loading time was the problem because the OpenGL render took 65 ms).

Did you try using a global `kiauto_time_out_scale`?

Even in this slow machine I didn't get a time-out for a naive board using the module:

![t1-3D_top](https://user-images.githubusercontent.com/22823627/178318993-f434a898-4944-44c2-a042-6d3f25f80790.png)
![t1-3D_bottom](https://user-images.githubusercontent.com/22823627/178319006-a2e6d30c-a14a-4a8b-a7ed-c7a39f269810.png)

Using:

```yaml
# Example KiBot config file
kibot:
  version: 1

outputs:
  - name: "base"
    type: render_3d
    run_by_default: false
    options:
      width: 2000
      height: 1000

  - name: "base2"
    type: step
    run_by_default: false
    options:
      metric_units: false

  - name: "top"
    type: render_3d
    extends: "base"
    options:
      rotate_x: 3
      rotate_z: -2

  - name: "bottom"
    type: render_3d
    extends: "top"
    options:
      width: 1920
      view: "bottom"
```

But if the motherboard is even more complex you could easily get a time-out.

**Comment by Regressor** [comment]
I tried kiauto_time_out_scale: 2.0 and got same result. Then I tried kiauto_time_out_scale: 4.0 and this helped, but bring another problem: now all images are "top" view :(

My config:

```
kiplot:
  version: 1

global:
  kiauto_time_out_scale: 4.0
  kiauto_wait_start: 120

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: false
  ignore_unconnected: false

  - name: 'render_3d_top'
    comment: "Render 3D image of board's top"
    type: render_3d
    dir: ../_fabrication/pcb_mainboard/_assemble/picture
    options:
      output: '%f_top.%x'
      view: 'top'
      background1: '#FFFFFF'
      background2: '#C2C2C2'
      solder_mask: '#11184c'
      zoom: 5
      width: 3840
      height: 2160

  - name: 'render_3d_bottom'
    comment: "Render 3D image of board's bottom"
    type: render_3d
    dir: ../_fabrication/pcb_mainboard/_assemble/picture
    options:
      output: '%f_bottom.%x'
      view: 'bottom'
      background1: '#FFFFFF'
      background2: '#C2C2C2'
      solder_mask: '#11184c'
      zoom: 5
      width: 3840
      height: 2160

```

Also it looks like zoom is ignored too:

![pcb_mainboard_top](https://user-images.githubusercontent.com/17557802/178481506-a5cf3efb-79be-4bd7-9db4-02f60e5545eb.png)
![pcb_mainboard_bottom](https://user-images.githubusercontent.com/17557802/178481520-ef891259-2091-474b-b87d-66d80b78b885.png)

I removed cm4.step, removed global section from yaml and pcb top / bottom was rendered as expected.
Then I returned cm4.step and got error:

ERROR:Time-out waiting for 3D viewer to be responsive (pcbnew_do - pcbnew_do:508) (kibot - kiplot.py:159)

Commands to render (from .gitlab-ci.yml):

```
    - cd pcb_mainboard
    - kibot -s all render_3d_top
    - cd ..
    - mv _library/buk_library.3dshapes/case _library/buk_library.3dshapes/case2 || true
    - cd pcb_mainboard
    - kibot -s all render_3d_bottom
    - cd ..
```
