### ISSUE TITLE
[BUG] Pick & place does not generate two files for top/bottom

### ISSUE THREAD

**Issue by myorbit** [INTI-CMNB/KiBot#222]
**Describe the bug**
The key 'separate_files_for_front_and_back: true' does not generate two separated files but one where top and bottom are included. It seems that the file gets overridden because it does not start with C1 but with C4. Also the reference is missing on the first 10u. Creating it manually within KiCad works and I get the expected output.

**To Reproduce**
Here is my yaml config ...

```
  - name: 'position'
    comment: "Pick and place file"
    type: position
    dir: pick_place_position
    options:
      output: '%f.%x'
      format: ASCII
      units: millimeters
      separate_files_for_front_and_back: true
      only_smd: true
```
... which produces the following output:

```
### Module positions - created on Wed 13 Jul 2022 13:39:56  ###
### Printed by KiBot
## Unit = mm, Angle = deg.
## Side : top
# Ref     Val                  Package                                                 PosX       PosY        Rot        Side  
J2        FTSH-107-01-F-DV-K   PinHeader_2x07_P1.27mm_Vertical_SMD                     68.0000    -107.2000   0.0000     top   
## End
      10u                  C_0805_2012Metric                                       87.3000    -160.2000   90.0000    bottom
C4        2u2                  C_0603_1608Metric                                       79.1000    -160.3000   90.0000    bottom
C5        10u                  C_0805_2012Metric                                       68.3000    -158.5000   90.0000    bottom
```

**Expected behavior**
Should generated two separated files for top and bottom.

**Environment (please complete the following information):**
* In a CI/CD workflow with GitLab
* docker image: kicad_auto:ki6
