### ISSUE TITLE
[BUG] Gerber output only shows F.Cu filled

### ISSUE THREAD

**Issue by myorbit** [INTI-CMNB/KiBot#226]
**Describe the bug**
I have a 6-layer board and all zones are filled and re-filled ('B') in the KiCad project.
1) I gernerate the Gerber files directly from the KiCad project. All copper layers are generated as intended.
2) After that I push changes to GitLab and there only the top layer (F.Cu ) is filled. All other layers just show the tracks.
(I also checked with other Gerber viewers.)

I made a minimal example where I noticed that it has to do something with my 'print_asm_notes' in the yaml config which generates a PDF with top and bottom assembly plots.

It would be great if someone could tell me if I am doing something wrong with the assembly prints? And why does it affect my gerber outputs? I am a bit lost right now.

**To Reproduce**

I tried several combinations:

It does not change anything if I add 'print_asm_notes' before or after 'gerbers' in the following section of `.gitlab-ci.yml`:
```
pcb_outputs:
  stage: gen_fab
  script:
    - "kibot -d fabrication -s all gerbers excellon_drill zip_gerber_drill"
```

But it matters where 'print_asm_notes' is in the `kicad_ci.kibot.yaml` file. Reordering actually changes the outcome to this:

1) Do not use 'print_asm_notes': Generates my gerber files just fine with all zones filled in all layers. But obviously no assembly print is generated.
2) 'print_asm_notes' before 'gerbers': Does generates gerber files with zone filled only on top layer. Zones with higher priorities on other layers are filled but not the GND zone (zone priority 0) on other layers. Assembly print on top is filled. Assembly print on bottom layer shows all zones filled with higher priorities but not the GND zone with priority 0.
3) 'print_asm_notes' after 'gerbers': Generates my gerber files just fine with all zones filled in all layers. Assembly print on top is filled. Assembly print on bottom layer shows all zones filled with higher priorities but not the GND zone with priority 0.

Here are my yaml files (see changes above):

`.gitlab-ci.yml`
```
### Gitlab CI/CD for KiCad

stages:
  - run_erc
  - run_drc
  - gen_fab

image:
  name: setsoft/kicad_auto:dev_k6

erc:
  stage: run_erc
  script:
    - "kibot -d fabrication -s update_xml,run_drc -i"
  rules:
    - changes:
      - "**.kicad_sch"
      - ".gitlab-ci.yml"
      - "**.kibot.yaml"
      when: always
  artifacts:
    when: always
    paths:
      - fabrication/

drc:
  stage: run_drc
  script:
    - "kibot -d fabrication -s update_xml,run_erc -i"
  rules:
    - changes:
      - "**.kicad_pcb"
      - ".gitlab-ci.yml"
      - "**.kibot.yaml"
      when: always
  artifacts:
    when: always
    paths:
      - fabrication/


sch_outputs:
  stage: gen_fab
  script:
    - "kibot -d fabrication -s run_drc,run_erc"
  rules:
    - changes:
      - "**.kicad_sch"
      - ".gitlab-ci.yml"
      - "**.kibot.yaml"
      when: on_success
  artifacts:
    when: always
    paths:
      - fabrication/

pcb_outputs:
  stage: gen_fab
  script:
    - "kibot -d fabrication -s all gerbers excellon_drill zip_gerber_drill"
  rules:
    - changes:
      - "**.kicad_pcb"
      - ".gitlab-ci.yml"
      - "**.kibot.yaml"
      when: on_success
  artifacts:
    when: always
    paths:
      - fabrication/
```

`kicad_ci.kibot.yaml`
```
# KiBot config file
kibot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  filters:
    - filter: 'Filter to ignore courtyards_overlap'
      error: 'courtyards_overlap'
      regex: 'Footprint'
  check_zone_fills: true
  ignore_unconnected: false


global:
#   kiauto_wait_start: 60
#   kiauto_time_out_scale: 2
  # We want the revision added to the names for this project
  output: '%f_v%r-%i.%x'

outputs:
 
  - name: 'print_asm_notes'
    comment: "Assembly print as PDF"
    type: pcb_print
    dir: .
    options:
      format: 'PDF'
      output: '%f_v%r-asm_notes.%x'
      force_edge_cuts: true
      plot_sheet_reference: true
      drill_marks: none
      pages:
        - sheet: 'Assembly Top Layer'
          colored_holes: true
          holes_color: '#f5e7e3'
          layers:
          - layer: F.Cu
            color: '#f5e7e3'
          - layer: F.Fab
            color: '#840000'
            plot_footprint_refs: true
            plot_footprint_values: false
          - layer: Edge.Cuts
            color: '#000000'
        - sheet: 'Assembly Bottom Layer'
          colored_holes: true
          holes_color: '#def5f1'
          mirror: true
          layers:
          - layer: B.Cu
            color: '#def5f1'
          - layer: B.Fab
            plot_footprint_refs: true
            plot_footprint_values: false
          - layer: Edge.Cuts
            color: '#000000'

  
  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: gerbers
    options:
      # generic layer options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: false
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true

      # gerber options
      line_width: 0.1
      subtract_mask_from_silk: false
      use_protel_extensions: false
      gerber_precision: 4.6
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: true

    # 6-layer
    layers:
      - layer: F.Cu
      - layer: In1.Cu
      - layer: In2.Cu
      - layer: In3.Cu
      - layer: In4.Cu
      - layer: B.Cu
      - layer: F.Paste
      - layer: B.Paste
      - layer: F.Mask
      - layer: B.Mask
      - layer: F.Fab
      - layer: B.Fab
      - layer: User.Drawings
      - layer: User.3
      - layer: Edge.Cuts
        suffix: Edge_Cuts

  - name: 'excellon_drill'
    comment: "Excellon drill files (no map)"
    type: excellon
    dir: drill
    options:
      metric_units: false
      pth_and_npth_single_file: false
      use_aux_axis_as_origin: false
      minimal_header: false
      mirror_y_axis: false
      report:
       filename: '%f_v%r-%i.%x'

  - name: 'zip_gerber_drill'
    comment: ZIP file of Gerber with NC Drills
    type: compress
    dir: export
    options:
      files:
        - from_output: gerbers
          dest: /
        - from_output: excellon_drill
          dest: /
```

**Expected behavior**
Gerbers with KiBot should generate same output as with direct Fabrication Outputs -> Gerbers in KiCad.
Assembly prints should print correct with all zones filled.

**Screenshots**
Gerbers with all zones filled correctly:
![grafik](https://user-images.githubusercontent.com/3307747/179092397-6a9a2b4c-4d94-47f1-ace3-8a854e098527.png)

Gerbers with only zones of higher priority filled:
![grafik](https://user-images.githubusercontent.com/3307747/179092885-47a1c7dd-9fd3-4d47-a940-218ccbed11ed.png)

Assembly print top layer with all zones filled:
![grafik](https://user-images.githubusercontent.com/3307747/179093116-ddb01127-dabb-4dbe-a282-900e89233a45.png)

Assembly print bottom with only higher priority zones filled:
![grafik](https://user-images.githubusercontent.com/3307747/179093390-6074a26a-437a-48c3-8fb3-a3acb3c31b7c.png)

**Environment (please complete the following information):**
* In a CI/CD workflow with GitLab
* docker image: kicad_auto:dev_k6
