### ISSUE TITLE
[BUG] No pcbdraw output

### ISSUE THREAD

**Issue by s-ol** [INTI-CMNB/KiBot#244]
**Describe the bug**
Running kibot no error is produced, but the pcbdraw output is simply missing.

```
kibot -b pcb/pcb.kicad_pcb -e pcb/pcb.kicad_sch -c config.kibot.yaml
- '' (ibom) [ibom]
WARNING:(W037) Field Mouser# of component U1 (USBLC6-2SC6) contains extra spaces: ` 511-USBLC6-2SC6 ` removing them. (kibot - v5_sch.py:1029)
- '' (bom) [bom]
- '' (pnp) [position]
- '' (pcb) [pcbdraw]
- '' (schematic) [svg_sch_print]
WARNING:(W058) Missing KiCad main config file /root/.config/kicad/6.0/kicad_common.json (eeschema_do - misc.py:179) (kibot - kiplot.py:164)
Found 21 unique warning/s (40 total)
```

**To Reproduce**
Kibot is being run from the docker image. The `kibot` invocation above is a macro for this:

```
function kibot
  docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY \
      -v $(pwd):$HOME/workdir \
      --env NO_AT_BRIDGE=1 \
      --workdir="$HOME/workdir" \
      setsoft/kicad_auto:ki6 kibot "$@"
end
```

Here's the config file:

```
kibot:
  version: 1

preflight:
  check_zone_fills: true
  run_drc: false
  run_erc: false

  set_text_variables:
    - name: 'VCS_DATE'
      command: 'git log -1 --format="%as"'

    - name: 'VCS_REV'
      command: 'git rev-parse --short HEAD'

    - name: 'VCS_TAG'
      command: 'git describe --tags --exact-match HEAD || echo "r?"'

global:
  dir: 'dist/%d_0x33.board_%r'
  output: '%i.%x'
  solder_mask_color: 'black'
  silk_screen_color: 'white'

filters:
  - name: 'exclude_virtual'
    type: 'generic'
    exclude_any:
      - column: Footprint
        regex: 'Jumper'
      - column: Value
        regex: '^PMOD/GPIO$'
      - column: Value
        regex: 'Outline'

outputs:
  - type: 'ibom'
    name: 'ibom'
    options:
      layer_view: 'B'
      dnf_filter: exclude_virtual

  - type: 'bom'
    name: 'bom'
    options:
      exclude_filter: exclude_virtual

  - type: 'position'
    name: 'pnp'
    options:
      output: 'placement.%x'
      separate_files_for_front_and_back: false

  - type: 'pcbdraw'
    name: 'pcb'
    options:
      output: 'pcb.%x'
      format: 'svg'
      bottom: true

  - type: 'svg_sch_print'
    name: 'schematic'
```

The board repository can be found at https://git.s-ol.nu/hw/0x33.board/hardware/-/

**Expected behavior**
There should be a `pcb.svg` in `dist/...`

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image: `kicad_auto:ki6`
