### ISSUE TITLE
[KiDiff] Getting PCB difference when requesting the SCH difference

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#273]
@set-soft The filename for the differences was improved by differentiating between sch and pcb, but when following the sch flow, I still get the pcb difference, not the SCH difference.

Here are the essential parts of my yaml configuration, I can share more if needed - I was using the proto variant, but I do not think that is essential:
```yaml
import:
   # Some imports
global:
  output: '%f_%r_%d-%i.%x'
  # out_dir: "%f_%br_%bd_%g/"
  out_dir: '%bf_%r_%d_%g/'
  date_time_format: '%Y%m%d_%H%M%S'
  date_format: '%Y%m%d'
  time_format: '%H%M%S'
  variant: 5V_3btn
variants:
  - name: proto
    comment: 5V power, 4 buttons per screen
    type: kicost
    file_id: _proto
    variant: ^(button3|button4|screen5v|conn3|AD8|bl_buffer)$
    pre_transform: kicost_rename
  - name: diff_A_pcb
    type: diff
    comment: PCB difference with previous version
    layers: [all]
    options:
      # output: '%f-%i%I%v.%x'
      cache_dir: .cache
      diff_mode: red_green # or stats
      # fuzz: 5
      #new: AYAC100577-02_20191209
      #new_type: git  # git or file
      old: DUO_PROTO
      old_type: git
      pcb: true
      threshold: 40
  - name: diff_A_sch
    type: diff
    comment: SCH difference with previous version
    layers: [all]
    options:
      # output: '%f-%i%I%v.%x'
      cache_dir: .cache
      diff_mode: red_green # or stats
      # fuzz: 5
      #new: AYAC100577-02_20191209
      #new_type: git  # git or file
      old: DUO_PROTO
      old_type: git
      pcb: false
      threshold: 40
```

_Originally posted by @mdeweerd in https://github.com/INTI-CMNB/KiBot/discussions/265#discussioncomment-3520327_
