### ISSUE TITLE
Allow for adjustment of rotation in pick and place file

### ISSUE THREAD

**Issue by lifeisafractal** [INTI-CMNB/KiBot#28]
Not all fab houses follow the same standards for rotation in the pick and place process. The example that brought this up for me is that KiCad follows a left/upper left Pin 1 convention where as JLCPCB considers 0 degree rotation based on the components are oriented in the tape and reel and these two don't always match. This causes the need for a lot of manual editing to get things right which is time consuming and error prone.

I came across [this blog post](https://dubiouscreations.com/2019/10/21/using-kicad-with-jlcpcb-assembly-service/) which call out a tool (I think written by the author) that will use some filters to automatically adjust the rotation based on pad name. I think this would be a nice feature to add to kibot.

I could see adding a `rotation_fix` entry in the position output. You could create regular expressions to match footprint names and then apply a rotation correction. If just footprint feels a little restrictive, we could add another key called `field` that lets you specifiy the field to filter on. This way you could exclude cretin components from getting modified based on designator or part number.

```yml
- name: 'position_example'
    comment: 'Generates the file with position information for the PCB components, used by the pick and place machine.'
    type: 'position'
    dir: 'Example/position_dir'
    options:
      # [list(dict)] Rotation fixes to apply based on a footprint regular expression match
      # Only the first match is applied.
      rotation_fix:
        - name: Do not correct Q4, this part is special
          field: Reference
          regex: "^Q4$"
          rotation: 0
        - regex: "^SOT-223"
          rotation: 180
        - regex: "^SOT-23"
          rotation: 180
        - regex: "^SOT-353"
          rotation: 180
        - name: All QFNs need to be corrected
          regex: ""^(.*?_|V)?QFN-(16|20|24|28|40)(-|_|$)"
          rotation: 270
...
```

I could take a stab at implementing this, but wanted to check before putting the effort in to see if this has a shoot at getting accepted upstream and to get any feedback on the design.
