### ISSUE TITLE
[FEATURE] Set Edge.Cuts color when `force_edge_cuts: true` is set

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#281]
**Is your feature request related to a problem? Please describe.**
I may have missed it in the documentation, but I didn't find a way to set the Edge.Cuts color when `force_edge_cuts: true`.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14631/188511277-be576427-c5be-4424-aedd-f13ce1c792f0.png">

**Describe the solution you'd like**
I'd like an option to set the color of the Edge.Cuts layer when `force_edge_cuts: true`.

**Describe alternatives you've considered**

A workaround is to add the Edge.Cuts layer manually to each page:

```
        - layers:
            - layer: F.Cu
              color: "#000000"
            - layer: Edge.Cuts
              color: "#000000"
```

<img width="493" alt="image" src="https://user-images.githubusercontent.com/14631/188511866-47d463bb-5c7c-479b-9810-5e8dafec83a1.png">
