### ISSUE TITLE
[FEATURE] output groups

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#293]
**Is your feature request related to a problem? Please describe.**
As I'm experimenting with KiBot via the command line, there are times when I'm finding myself wanting to run the same subsets of outputs from a KiBot config.  For example, I have outputs for CSV BOM, HTML BOM, XLSX BOM, iBOM all in the same config file, and if I want to generate all the BOM outputs, I need to type all the output targets individually.

`kibot [-b BOARD] [-e SCHEMA] [-c CONFIG] bom_csv bom_html bom_xlsx ibom`

**Describe the solution you'd like**
It might be nice to have something like "output groups" where the group is just an alias that maps to a list of output targets.  For example, an output group might be something like:

```
output_groups:
  - name: bom
    outputs:
      - bom_csv
      - bom_html
      - bom_xlsx
      - ibom
```

Then you could just run `kibot [-b BOARD] [-e SCHEMA] [-c CONFIG] bom`.

**Describe alternatives you've considered**
I'm currently doing something like this by defining separate config files which import a subset of the outputs from a base config file, e.g.:

```yaml
# bom.config.yaml
import:
  - file: base.kibot.yaml
    outputs: [
      bom_csv,
      bom_html,
      bom_xlsx,
      ibom,
    ]
    preflights: all
    filters: all
    variants: all
    global: all
```

`kibot [-b BOARD] [-e SCHEMA] -c bom.config.yaml`

Not sure if anybody else would find something like this useful, but I wanted to mention it.
