### ISSUE TITLE
[BUG] Kibom variant exclude_filter is documented as '', but is actually '_mechanical'

### ISSUE THREAD

**Issue by matthiesenj** [INTI-CMNB/KiBot#303]
**Describe the bug**
When creating a kibom-type variant and leaving the 'exclude_filter' property to its default value, it clearly has '_mechanical'-filter behavior.
The kibom variant documentation says it defaults to the empty string:

> exclude_filter: [string|list(string)=''] Name of the filter to exclude components from BoM processing.

**To Reproduce**
Run the following yaml on a project.

``` yaml
kibot:
  version: 1

global:
  variant: "default"

variants:
- name: "default"
  type: kibom
#  exclude_filter: ''

outputs:
- name: "bom"
  type: bom
  options:
    exclude_filter: ''
```

**Expected behavior**
According to the documentation, the above should not exclude anything, but it does - items matched by the _mechanical filter are excluded from the output. If the commented line is enabled, nothing gets excluded from the BoM.

It's obvious when looking at the variant code that a variant is assigned the _mechanical filter if the property is not explicitly set, but I don't know if the code or the documentation is wrong.
