### ISSUE TITLE
[BUG] Coordinates generated by 'position' and 'bom' not identical

### ISSUE THREAD

**Issue by matthiesenj** [INTI-CMNB/KiBot#306]
**Describe the bug**
I have a project where I recently switched to using the 'bom' output for generating XYRS data in order to also have a 'populate' column.
The problem is that the XYRS data isn't correct for some parts when using 'bom' output.

**To Reproduce**
Running the following yaml produces two files where the bom output produces wrong XYRS for a few parts.
I tried creating a simple project from scratch using the footprints with wrong XYRS to reproduce, but I can't get it to show the problem. Unfortunately, I can't share the project where I see the problem (proprietary).

``` yaml
outputs:
# Use bom output to generate position file
- name: bom_position
  type: bom
  disable_run_by_default: true
  options:
    format: CSV
    output: "bom_pos.%x"
    bottom_negative_x: false
    columns:
    - field: "References"
      name: "Ref"
    - field: "Footprint"
    - field: "Footprint X"
      name: "PosX"
    - field: "Footprint Y"
      name: "PosY"
    - field: "Footprint Rot"
      name: "Rot"
    - field: "Footprint Side"
      name: "Side"
    group_fields: [] # disable grouping
    use_aux_axis_as_origin: true

- name: position
  type: position
  options:
    format: CSV
    output: "pos.%x"
    separate_files_for_front_and_back: false
    bottom_negative_x: false
    columns:
    - id: "Ref"
    - id: "Package"
      name: "Footprint"
    - id: "PosX"
    - id: "PosY"
    - id: "Rot"
    - id: "Side"
    include_virtual: false
    use_aux_axis_as_origin: true
```

'bom' output (excerpt):
...
U402,Diodes_SO-8EP,57.0000,-16.5000,0.0000,top
_U101,Raspberry-Pi-4-Compute-Module_1-100,-45.5420,57.9120,0.0000,top
U102,Raspberry-Pi-4-Compute-Module_101-200,-45.5420,57.9120,0.0000,top_
U602,SOP-4_3.8x4.1mm_P2.54mm,33.2500,-15.2500,180.0000,top
U603,SOP-4_3.8x4.1mm_P2.54mm,33.2500,-21.7500,0.0000,top
U301,USON-10_2.5x1.0mm_P0.5mm,27.5000,-47.5000,0.0000,top
...

'position' output (excerpt):
...
"U402","Diodes_SO-8EP",57.0000,-16.5000,0.0000,top
_"U101","Raspberry-Pi-4-Compute-Module_1-100",100.9000,-51.9600,90.0000,top
"U102","Raspberry-Pi-4-Compute-Module_101-200",100.9000,-18.0400,90.0000,top_
"U602","SOP-4_3.8x4.1mm_P2.54mm",33.2500,-15.2500,180.0000,top
"U603","SOP-4_3.8x4.1mm_P2.54mm",33.2500,-21.7500,0.0000,top
"U301","USON-10_2.5x1.0mm_P0.5mm",27.5000,-47.5000,0.0000,top
...
All parts are located in the same quadrant relative to the aux axis origin.
As can be seen, the XYRS for the two bad parts is the same - I can move one of the footprints, but the XY stays the same in the bom output. If I move the aux axis origin, the XY for both of them changes. When looking at the footprint properties in pcbnew, they have different (correct) XY.

If I delete the problematic footprints from the pcb (in pcbnew), the bom output still lists them at the same coordinates, whereas the position output (correctly) doesn't list them at all.

If I delete a completely unrelated footprint that otherwise generates correct XYRS, the bom output still lists it, and at the same coordinates as the bad footprints mentioned above - it doesn't warn that the footprint isn't there.

I think what happens is that the bom output isn't able to look up the footprint within the pcb data, and then just outputs some arbitrary numbers.

Do you have any insights into what could be going wrong?

**Expected behavior**
Identical XYRS data for both outputs.

**Environment (please complete the following information):**
- Using a docker image? `kicad_auto:latest` on Windows 10
