### ISSUE TITLE
[HOW] To Let URL string be a hyperlink

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#311]
**What do you want to achieve?**
Let the `extra_fields` option in `interactive_bom` [urlify](https://github.com/openscopeproject/InteractiveHtmlBom/issues/82#issuecomment-1228665488) my URL string

**Do you have some configuration file (.kibot.yaml) that you are using?**

```yaml
  - name: 'interactive_bom'
    comment: "Interactive Bill of Materials in HTML format"
    type: ibom
    dir: .
    options:
      name_format: 'ibom'
      show_fabrication: true
      hide_silkscreen: true
      highlight_pin1: true
      extra_fields: 'Datasheet'
      checkboxes: 'Sourced,Placed,Bogus'
      output: MyProject.ibom.html
```

**Environment (please complete the following information):**
I'm running KiBot:
- In `GitLab`
- Using docker image kicad_auto:dev_k6`
