### ISSUE TITLE
[BUG] diff output for schematic only first page

### ISSUE THREAD

**Issue by Crzyrndm** [INTI-CMNB/KiBot#319]
Currently attempting to add diff output for Github PR for a Kicad6 project

PCB diffs work amazingly well, the schematic diff however is only generating a single page (page 1) and none of the other sheets in the project. This particular project has about 15 sheets with the first sheet being basically just links between the top level sheets. All are in the same repository (no submodules)

```yaml
outputs:
  - name: "schematic-diff"
    comment: "schematic diff"
    type: diff
    dir: diff/
    options:
      output: "${PROJECT}-${VERSION}-%i.%x"
      cache_dir: .cache/
      pcb: false
      only_different: false
      # comparison is with current commit
      new: HEAD
      new_type: git
      # original
      old: KIBOT_LAST-10 # placeholder
      old_type: git
```

```yaml
      - uses: INTI-CMNB/KiBot@v2_dk6 # have tried v2_k6 and v2_dk6
        with:
          # Required - kibot config file
          config: config.kibot.yml
          # optional - prefix to output defined in config
          dir: output
          # optional - schematic file
          schema: "schematic.kicad_sch"
          # optional - PCB design file
          board: "pcb.kicad_pcb"
```

NOTE:
`${PROJECT}` and `${VERSION}` are set in preflight `set_text_variables`

Expected: Schematic diffs are created for all pages, not just the first page

**Comment by set-soft** [comment]
Hi @Crzyrndm !
The development version should support it now. 
Thanks for reporting!

**Comment by Crzyrndm** [comment]
@set-soft this doesn't seem to be working
```yaml
  - name: "schematic-diff-branch"
    comment: "schematic diff against main"
    type: diff
    dir: diff/
    options:
      output: "${PROJECT}-${VERSION}-branch-%i.%x"
      cache_dir: .cache/
      pcb: false
      only_different: true
      only_first_sch_page: false # should be the default?
      # comparison is with current commit
      new: HEAD
      new_type: git
      # original
      old: b428c6b047400a179d6b628271ace56436c30c5f # hardcoded for testing
      old_type: git
```
^^ results in "No diff" (or a title page with no changes visible if "only different" is false)
