### ISSUE TITLE
[FEATURE] Additional arguments with the Github action

### ISSUE THREAD

**Issue by Crzyrndm** [INTI-CMNB/KiBot#320]
The [Github action](https://github.com/INTI-CMNB/KiBot#usage-of-github-actions) appears to not provide any "additional arguments" field that could be used for e.g. [preprocessing](https://github.com/INTI-CMNB/KiBot#doing-yaml-substitution-or-preprocessing)

I came across this while trying to feed in the "old" commit for a diff based on some previous steps in the workflow (depending on context, diff against base branch or the previous release)

a simple `additional_args` field that appends to the kibot invocation would be appreciated

**Comment by set-soft** [comment]
Hi @Crzyrndm !
I added `additional_args`, can you test it?
Be careful about quotes, they will be problematic, as usually when handling shell stuff.
The current behavior should be to just concatenate the text at the end of the kibot invocation.

**Comment by Crzyrndm** [comment]
```yaml
- uses: INTI-CMNB/KiBot@v2_dk6
        with:
          config: config.kibot.yml
          dir: output
          schema: "schematic.kicad_sch"
          board: "pcb.kicad_pcb"
          additional_args: -E OLD_COMMIT=1234
```

`Error: INTI-CMNB/KiBot/v2_dk6/action.yml (Line: 68, Col: 8): Unrecognized named-value: 'additional_args'. Located at position 1 within expression: additional_args`
?
