### ISSUE TITLE
[HOW] set_text_variables usage

### ISSUE THREAD

**Issue by Unichord** [INTI-CMNB/KiBot#340]
I can't find a way to substitute variables in both PCB/Gerbers and schematic PDFs, probably I'm not using them right.
I'm working on KiCad 6, no WSL2, no CI/CD environment.

This is my preflight (I also tried with `pcb_replace`), the rest is just a simple gerber/PDF generation, if needed just let me know:
```
preflight:
  # pcb_replace:
    # - replace_tags:
        # tag: 'name'
        # text: 'aaaaaaaaa'
  set_text_variables:
    - name: 'b_name'
      text: 'example'
      command: 'echo $KIBOT_PCB_NAME'
    - name: 'b_code'
      command: 'echo 22.4360'
```
I defined the variables as `${b_name}` and `${b_code}`, but I also tried `b_name` and `b_code`, and also `@b_name@` and `@b_code@`, with no result whatsoever. Also in the yaml file I tried setting the name as `'@b_name@'` and so on.

This is a small example of the PCB, I left just the writings and the header, if more is needed let me know:
[FMFR1_example.zip](https://github.com/INTI-CMNB/KiBot/files/10114202/FMFR1_example.zip)

Thanks.
