### ISSUE TITLE
[HOW or BUG] multivar use

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#353]
**What do you want to achieve?**
Compare multiple variants

**Do you have some PCB/Schematic to use as example?**
https://github.com/mdeweerd/kbot-testcases - tag multivar

**Do you have some configuration file (.kibot.yaml) that you are using?**
Relevant part:
```yaml
  - name: diff_variants
    type: diff
    dir: +Diffs
    comment: PCB difference between variants
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts
      - F.Fab
      - B.Fab

    options:
      cache_dir: .cache
      diff_mode: red_green  # or stats
      # fuzz: 5
      new: [header, all]
      new_type: multivar
      add_link_id: true
      copy_instead_of_link: true
      old: master
      old_type: git
      pcb: true
      threshold: 40
```
Full:
https://github.com/mdeweerd/kibot-testcases/blob/main/designs/tc5/tc5.kibot.yaml

**Environment (please complete the following information):**
Where are you running KiBot:
Docker: setsoft/kicad_auto:dev  on windows.

**Additional context**

Run 
```shell
kibot -c designs/tc5/tc5.kibot.yaml -b designs/tc5/tc5.kicad_pcb -e designs/tc5/tc5.sch -g variant=header diff_variants
```

Results in:
```
- 'PCB difference between variants' (diff_variants) [diff]
 - header vs all
ERROR:In section 'diff_variants' (diff): Unknown output `header` (kibot - error.py:40)
```

As far as I understand from the documentation, the multivar type is used to select variants and the output diff type is used to select outputs.
Apparently multivar is currently expecting an output while I was looking to compare the `header` variant with the `all` variant in the example.

Documentation:
```
Use output to specify the name of a pcb_variant/sch_variant output. Use multivar to compare a set of variants, in this mode new is the list of variants.
```

Not sure if this is a bug, a documentation to clarify or an interpretation errror.  Anyway, rather that defining a pcb_variant output for each pcb variant, and similar for each sch variant, I'ld love to see multivar behave as I understand it from the documentation (and as suggested in the above example).
