### ISSUE TITLE
[BUG] ${ISSUE_DATE} and set_text_variables: not working as expected 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#361]
**Describe` the bug**
For the schematic set_text_variables works as expected and the variables are changed but ${ISSUE_DATE} is empty.
For the board it is the exact opposite set_text_variables does not work at all but ${ISSUE_DATE} is replaced by the current date.

Config should be the same for both 

**To Reproduce**

```
# Example KiPlot config file
kiplot:
  version: 1

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  ignore_unconnected: false
  set_text_variables:
    - name: 'SBS_Prj_Reviewer'
      command: 'git log -1 --pretty=format:"%cn"'
    - name: 'SBS_Prj_Creator'
      command: 'git log -1 --pretty=format:"%an"'

global:
  drc_exclusions_workaround: true
  units: 'millimeters'
  date_time_format: '%d.%m.%Y'
#   kiauto_time_out_scale: 2


outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: Schematic
    options:
      output: "%v_%p_Rev%r-%i_%D.%x"
      
  - name: 'gerbers'
    comment: "Gerbers for the board house"
    type: gerber
    dir: Gerbers
    options:
      # generic layer options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      output: "%v_%p_Rev%r-%i_%D.%x"
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      disable_aperture_macros: true
      line_width: 0.1
      uppercase_extensions: true
      subtract_mask_from_silk: true
      inner_extension_pattern: '.g%n'
      edge_cut_extension: '.gml'
    layers:
      - 'copper'
      - 'F.SilkS'
      - 'B.SilkS'
      - 'F.Mask'
      - 'B.Mask'
      - 'Edge.Cuts'
      - 'F.Paste'
      - 'B.Paste'

  - name: 'drill'
    comment: "Drill files"
    type: excellon
    dir: dril
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      output: "%v_%p_Rev%r-%i_%D.TXT"
      
      
  - name: 'print_pcb_pdf'
    comment: "PDF for the PCB"
    type: pcb_print
    dir: PCB_Docu
    options:
      #svg_precision: 6
      realistic_solder_mask: false
      force_edge_cuts: true
      keep_temporal_files: false
      #enable_ki6_frame_fix: true
      #sheet_reference_layout: pcb_print.kicad_wks
      scaling: 1.0
      pages:
        - layers: [ F.SilkS, Dwgs.User ]
          sheet: 'Top Silk layer'
        - layers: [ F.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ F.Cu, Dwgs.User ]
          sheet: 'Top copper layer'
        #- layers: [ In1.Cu, Dwgs.User ]
        #  sheet: '1 inner layer'
        #- layers: [ In2.Cu, Dwgs.User ]
        #  sheet: '2 inner layer'
        #- layers: [ In3.Cu, Dwgs.User ]
        #  sheet: '3 inner layer'
        #- layers: [ In4.Cu, Dwgs.User ]
        #  sheet: '4 inner layer'
        - layers: [ B.Cu, Dwgs.User ]
          sheet: 'Bottom copper layer'
        - layers: [ B.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ B.SilkS, Dwgs.User ]
          sheet: 'Bottom layer'
        - layers: [ F.Paste,Dwgs.User]
          sheet: 'Top paste Fabrication layers'
        - layers: [ B.Paste,Dwgs.User]
          sheet: 'Bottom paste Fabrication layers'
      output: "%v_%p_Rev%r-%i_%D.%x"



  - name: 'archiv'
    comment: "ZIP archive"
    type: compress
    dir: Produktion
    options:
      files:
        - from_output: gerbers
          dest: /
        - from_output: drill
          dest: /
      output: "%v_%p_Rev%r_%I.%x"
```
`
**Expected behavior**
variables defined by set_text_variables should be replaced and ${ISSUE_DATE}  should be replaced by current date 

**Screenshots**
SCH: 
![image](https://user-images.githubusercontent.com/120729391/211336517-80a54840-2e77-4a19-9ffb-7167acc60e68.png)
BRD:
![image](https://user-images.githubusercontent.com/120729391/211336685-790f3bab-70fe-4c5f-aef3-e687e200b397.png)

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? GitLab
- Using a docker image?`kicad_auto:dev_k6`

**Comment by set-soft** [comment]
OK, I created a custom layout and tried it using KiCad. The ISSUE_DATE variable doesn't work in eeschema.
Solution: Use a variable defined by you.
For the PCB all works as spected, what is failing for you?
BTW: ISSUE_DATE is the date from the PCB, not the current date.
Pleas confirm the above, in this case this issue should be closed and a KiCad bug should be filled.

**Comment by MarkusSBS** [comment]
ah sorry that i missed to explain it better 

I have some dummy data in the kicad projekt file for testing. 
For "erstellt durch" its Markus and "Genehmigt von" Its empty 

now i want to replace it with the git author and git commiter for a release. 
this is done with:   

```
set_text_variables:
    - name: 'SBS_Prj_Reviewer'
      command: 'git log -1 --pretty=format:"%cn"'
    - name: 'SBS_Prj_Creator'
      command: 'git log -1 --pretty=format:"%an"'

```

For the schematic everthing works as expected. Except the date is not set (but you mention i have to set it manualy) 

For the PCBnew nothing of the dummy data is replaced with the set_text_variables but the date is replaced with a dateformat i specifyed with:

```
global:
date_time_format: '%d.%m.%Y'

```
