### ISSUE TITLE
[HOW] schematic svg with filled background

### ISSUE THREAD

**Issue by nerdyscout** [INTI-CMNB/KiBot#362]
![image](https://user-images.githubusercontent.com/8549545/211660843-237a44b8-88d8-4144-a0a1-f6fd3ee62a8b.png)

i might be confused a bit currently... using Type: `svg_sch_print`, which i guess belongs to the dialog of the screenshot. correct?

anyway... I am looking for an option to generate a schematic as svg with colored background. what am I missing?

**Comment by set-soft** [comment]
Hi @nerdyscout !
Yes, `svg_sch_print` (which was adapted by you from `pdf_sch_print`) is this dialog.
It wasn't possible to control it.
Now it should be, I tried:

```yaml
  - name: 'print_sch_svg'
    comment: "Print schematic (SVG)"
    type: svg_sch_print
    dir: Schematic
    options:
      color_theme: User
      background_color: true
```
And got:
![_light_control_Rev-schematic_2023-01-11](https://user-images.githubusercontent.com/22823627/211938512-97f65d70-3aee-40aa-8f1d-27faf914a527.svg)

Of course I have a color scheme called *User* and it defines the background as an ugly yellow ;-)
If you'll use CI/CD you'll need to copy the color file to `~/.config/kicad/6.0/colors/` (i.e. `~/.config/kicad/6.0/colors/user.json`)

Let me know if it works for you.

**Comment by set-soft** [comment]
Hi @nerdyscout !
Did you have time to test it?

**Comment by nerdyscout** [comment]
I just did past weekend... but I haven't figured out how to do this:
`If you'll use CI/CD you'll need to copy the color file to ~/.config/kicad/6.0/colors/ (i.e. ~/.config/kicad/6.0/colors/user.json)`
while simply using 
```
  docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    container:
      image: setsoft/kicad_auto:ki6
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            ibom.html octopart.csv schematic.pdf schematic.svg board_top.pdf board_bottom.pdf
```
the user.json obviously is inside the user dir, not the respository. without building my own docker image I currently don't see how to put this file into.
