### ISSUE TITLE
[HOW] layer detection for fabrication output 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#365]
Hello

Is there an easy way for the PCB PDF to have a universal config for different layer count like 2, 4 or 6 layers or do i need a specific yaml for the layer stackup?

with the gerber output there is a wildcard "copper"

```
      pages:
        - layers: [ F.SilkS, Dwgs.User ]
          sheet: 'Top Silk layer'
        - layers: [ F.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ F.Cu, Dwgs.User ]
          sheet: 'Top copper layer'
        #- layers: [ In1.Cu, Dwgs.User ]
        #  sheet: '1 inner layer'
        #- layers: [ In2.Cu, Dwgs.User ]
        #  sheet: '2 inner layer'
        #- layers: [ In3.Cu, Dwgs.User ]
        #  sheet: '3 inner layer'
        #- layers: [ In4.Cu, Dwgs.User ]
        #  sheet: '4 inner layer'
        - layers: [ B.Cu, Dwgs.User ]
          sheet: 'Bottom copper layer'
        - layers: [ B.Mask, Dwgs.User ]
          sheet: 'Top Mask layer'
        - layers: [ B.SilkS, Dwgs.User ]
          sheet: 'Bottom layer'
        - layers: [ F.Paste,Dwgs.User]
          sheet: 'Top paste Fabrication layers'
        - layers: [ B.Paste,Dwgs.User]
          sheet: 'Bottom paste Fabrication layers'
```

cheers 

markus

**Comment by set-soft** [comment]
Hi @MarkusSBS !
This is an interesting question.
The `copper` keyword is useful for a `layer` element, i.e.:

```yaml
pages:
        - layers: [ F.SilkS, copper,  Dwgs.User ]
          sheet: 'Top Silk layer'
```

But this is useless here because you don't want to print all in the same page. BTW: it raised an exception, now fixed.
So we need other mechanism.
The main problem here is that the `sheet` option must be a pattern.
I'll take a look at this.

**Comment by set-soft** [comment]
Hi @MarkusSBS !
Ok, I added something, you use:

```yaml
      pages:
        - layers: [ F.Cu, Dwgs.User ]
          sheet: '%ld (%ln)'
          repeat_for_layer: F.Cu
          repeat_layers: copper
```

And You get N pages. Note the `sheet` option, it will expand to the layer description and name.
Check if it can do what you want.
