### ISSUE TITLE
[HOW] Generate complex panel preview (with pcbdraw raise Huge input lookup error)

### ISSUE THREAD

**Issue by palandri** [INTI-CMNB/KiBot#369]
**What do you want to achieve?**
I was trying to render with `pcbdraw` a panel generated by `panelize`, and depending on the size/complexity of the panel, raised the following error: `ERROR:PcbDraw error: internal error: Huge input lookup, line 397862, column 23 (<string>, line 397862) (kibot - out_pcbdraw.py:498)`

I don't know if this is just my inability, or is a bug. I can generate the preview of the panel with a grid of 6x6, but not more than that. Also, even with a 6x6 grid, pcbdraw takes a lot of time (around 10 minutes).

**Do you have some PCB/Schematic to use as example?**
In [here](https://1drv.ms/u/s!Al54oUii4WMSirZnt1CKeBBkvohtow?e=XV7Vxf) there is the single pcb file, and panel generated.

**Do you have some configuration file (.kibot.yaml) that you are using?**
Relevant yaml section
```yaml
  - name: panel
    comment: Generate panel for fabrication
    dir: JLCPCB-Panel
    type: panelize
    options:
      # create_preview: true # disabled so I could generate the panel
      configs:
        - cuts:
            # type: vcuts
            type: mousebites
            drill: 0.5mm
            spacing: 1mm
            offset: 0.2mm
            prolong: 0.5mm
        - layout:
            rows: 10
            cols: 9
            space: 2mm
            vbackbone: 4mm
            vbonecut: true
            vboneskip: 1
            hboneskip: 1
        - tabs:
            type: fixed
            width: 3mm
            vcount: 0
            hcount: 2
        - post:
            millradius: 1mm
        - framing:
            type: frame
            width: 5mm
            space: 3mm
            cuts: both
            fillet: 1mm
            mintotalheight: 300mm
            mintotalwidth: 200mm
        - copperfill:
            type: hatched
            clearance: 2mm
            spacing: 0.5mm
            width: 0.5mm
        - tooling:
            type: 4hole
            hoffset: 2.5mm
            voffset: 2.5mm
            size: 1.5mm
        - fiducials:
            type: 4fid
            hoffset: 2.5mm
            voffset: 2.5mm
            coppersize: 2mm
            opening: 1mm
        - text:
            type: simple
            text: '{boardTitle}({boardRevision}), {date}'
            anchor: mt
            voffset: 2.5mm
            hjustify: center
            vjustify: center
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? (Ex: `GitHub`/`GitLab`) No
- In a GitHub action? Which tag are you using? (Ex `v1`, `v1_k6`, `v2`, `v2_d`, `v2_dk6`, `v2_k6`) No
- Using a docker image? (Ex: `kicad_auto:ki6`, `kicad_auto:latest`, `kicad_auto:dev`, `kicad_auto:dev_k6`, a custom one? can you provide the `Dockerfile`) Originally yes, tried with kicad_auto:dev_k6 and kicad_auto:latest
- Using a desktop system? Which OS, distro and version? Tried running on native kibot/kikit installation on Ubuntu Server 22.04, managed to raise the size of the grid (around 8x7), but encountered the same problem.

**Additional context**
Add any other context about your setup/project.

**Comment by set-soft** [comment]
Hi @palandri !

I'm not the pcbdraw author, but contributed various patches.
When looking at the code you see it wasn't optimized for speed, but for maintainability.
It does the same heavy tasks over and over, discarding what was generated in the previous passes.

For small PCBs is fast, but it becomes really slow when the complexity grows.
I recommend you using the `render_3d` output.
I tried the following config:

```yaml
kibot:
  version: 1

outputs:
  - name: "base"
    type: render_3d
    run_by_default: false
    options:
      width: 1000
      height: 1500
      transparent_background: true
      auto_crop: true
      zoom: 4
      # The following needs the schematic
      # show_components: none

  - name: "top"
    type: render_3d
    extends: "base"

  - name: "bottom"
    type: render_3d
    extends: "top"
    options:
      view: "bottom"
```

In around 6 minutes I got:

![sd_stick-panel-3D_top](https://user-images.githubusercontent.com/22823627/212732600-629d5b22-2ef6-49e9-977a-21debe9fc5a3.png)

And

![sd_stick-panel-3D_bottom](https://user-images.githubusercontent.com/22823627/212732793-ccb1a2b3-b9dc-4687-925e-5c6a07569f68.png)

BTW: On my system PcbDraw failed after 40 minutes. The error seems to be from Python itself.
