### ISSUE TITLE
[BUG] file_id is often ignored by printing or export

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#371]
**Describe the bug**
If I print or export and set under `options` the `output_name` I miss the `file_if` if I use variants.

**To Reproduce**
```yaml
variants:
  - name: 'default'
    comment: 'default'
    type: kibom
  - name: 'variant1'
    comment: 'my variant'
    type: kibom
    file_id: _variant1
    variant: variant1
    pre_transform: '_var_rename'

outputs:    
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: Schematics.pdf
```
**Expected behavior**
My goal is to export my content the following file naming structure to make it sortable:

- Schematics-myProject-pre_transform
- Gerber-myProject-pre_transform
- Drill-myProject-pre_transform
- PCBprint-myProject-pre_transform

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow GitLab
- kicad_auto:dev_k6`
