### ISSUE TITLE
[FEATURE]SVG support for Logo

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#383]
**Is your feature request related to a problem? Please describe.**

`ERROR:In section 'bom_html' (bom): Only PNG images are supported for the logo (kibot - error.py:40)`

**Describe the solution you'd like**
Supporting vector graphics as logo in bill of materials.

**Describe alternatives you've considered**
Automatic sizing of high resolution png.

I have a 1043x919 px png and use `convert` to resize it.
The problem here is that it looks bad after resize.

**Additional context**
I do currently create one PCB documentation with `pdfunite` and export my generated xlsx spreadsheet with `soffice`.
Unfortunately just png is supported which is let the logo look not so nice compared to the rest of the `bom`.
It's just a request if this is possible.

**Comment by N0cynym** [comment]
Ok I found this commit https://github.com/INTI-CMNB/KiBot/commit/1dea3970bc063340d17251ecc8a11e860fb51f31and will test to scale my logo.

**Comment by N0cynym** [comment]
So I could not work out how the scaling is working correctly.
`logo_scale: -10` removes my png

Which logo is used in default?

**Comment by set-soft** [comment]
Hi @N0cynym !

> So I could not work out how the scaling is working correctly. `logo_scale: -10` removes my png

What do you expect using a negative scale?
How does your logo look using the default scale (2)?
Too big? Use 1 or less than 1. 
Too small? Use more than 2.

But note that (as documented) not all spreadsheet software applies the scale. Also note that the size you get is dependent on the spreadsheet. So you must experiment it for the software you use.

> Which logo is used in default?

The KiBot logo, a 370x200 PNG embedded in the code.

About adding support for SVG: This can be done, but for this KiBot must convert the image to PNG, I don't see any advantage of doing this inside KiBot.

**Comment by N0cynym** [comment]
If I use the scale >1 the logo is to big.

A negative scale will remove the logo.

Trying a positive scale <1 and >0 give me:

`ERROR:In section 'bom_xlsx' (bom): Option `logo_scale` must be a number not `string` (kibot - error.py:40)`

**Comment by set-soft** [comment]
Are you using `.` as decimal separator?
I modified the XLSX test 7 like this:

```yaml
# Example KiBot config file
kibot:
  version: 1

outputs:
  - name: 'bom_internal'
    comment: "Bill of Materials in HTML format"
    type: bom
    dir: BoM
    options:
      format: XLSX
      xlsx:
        logo: docs/images/bot.png
        logo_scale: 0.1
        col_colors: false
```

And worked perfectly, I got it scaled to a good size, the original PNG looks huge.
