### ISSUE TITLE
[HOW] to use %I

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#387]
**Describe the bug**
I have tryed to use the %I for different Report versions.

but it is not replaced bei output_id

i am not shure if i use it wrong or it is broken.

Here is my configuration:

```
  - name: 'report_full'
    comment: "Full design report"
    type: report
    dir: report
    options:
      do_convert: true  
      template: "./report/Full.txt"
      output_id: 'PCB-spec'
      converted_output: "%C1_%p-%v_Rev%r-%i_%IB_${Doc_status}_%D-%T.%x"
      #output: "%C1_%p-%v_Rev%r-%i_${Doc_status}_%D-%T.%x"
      
  - name: 'report_history'
    comment: "Design History"
    type: report
    dir: report
    options:
      do_convert: true  
      template: "./report/History.txt"
      output_id: 'History'
      converted_output: "%C1_%p-%v_Rev%r-%i_%I_${status}_%D-%T.%x"
      #output: "%C1_%p-%v_Rev%r-%i_${Doc_status}_%D-%T.%x"
      

```
result is: 

```
66.6666.66_Zellsim-_RevZ9-report__test_06-02-2023-142139.pdf
66.6666.66_Zellsim-_RevZ9-report_B_test_06-02-2023-142139.pdf

```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow?`GitLab`

- Using a docker image?`, `kicad_auto:dev_k6`

thanks for your help

**Comment by set-soft** [comment]
Hi @MarkusSBS !
As the documentation explains the `output_id` is not part of the *options* section, but part of the *output* itself.
Your config:

```yaml
  - name: 'report_history'
    comment: "Design History"
    type: report
    dir: report
    options:
      do_convert: true  
      template: "./report/History.txt"
      output_id: 'History'
      converted_output: "%C1_%p-%v_Rev%r-%i_%I_${status}_%D-%T.%x"
      #output: "%C1_%p-%v_Rev%r-%i_${Doc_status}_%D-%T.%x"
```

Should be:

```yaml
  - name: 'report_history'
    comment: "Design History"
    type: report
    dir: report
    output_id: 'History'
    options:
      do_convert: true  
      template: "./report/History.txt"
      converted_output: "%C1_%p-%v_Rev%r-%i_%I_${status}_%D-%T.%x"
      #output: "%C1_%p-%v_Rev%r-%i_${Doc_status}_%D-%T.%x"
```
