### ISSUE TITLE
[HOW] What is the proper configuration to get testpoints position file (using filter + output)

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#393]
I try to get the positions for the testpoints, identified through the name of the footprint.
(i.e., I finally get to try #106 

I am labeling this as a HowTo, this could be a functional issue.

I could not find a working combination for a filter + output where only the test point positions were kept in the position file (based on the footprint containing TestPoint) - I always get other components as well.

Test case: https://github.com/mdeweerd/kibot-testcases/tree/TestPinPositions or 
[tc5.tar.gz](https://github.com/INTI-CMNB/KiBot/files/10788393/tc5.tar.gz)

I check the output in `tc5_01_20211224__header/PCBA/tc5_01_20211224-both_pos_test_points.csv`

I tried several filters, these are the current ones:
https://github.com/mdeweerd/kibot-testcases/blob/TestPinPositions/yaml/common.kibot.yaml#L30-L43

```
  - name: test_points
    comment: Get the test points
    type: generic
    # invert: true
    include_only:
      - column: Footprint
        regex: 'TestPoint'
  - name: test_points_nok
    comment: Get the test points
    type: generic
    invert: true
    exclude_any:
      - column: Footprint
        regex: 'TestPoint'
```

To generate test_points position file:

https://github.com/mdeweerd/kibot-testcases/blob/TestPinPositions/yaml/common.kibot.yaml#L700-L707

```yaml
  - name: test_points
    type: position
    dir: +PCBA
    extends: position
    output_id: _test_points
    options:
      include_filter: test_points
      include_virtual: true
```

Thanks !

**Comment by mdeweerd** [comment]
The core issue was that "include_filter" does no exist on the position output options.

So something that works for me (in my project) is:

```yaml
filters:
  - name: test_points
    comment: Get the test points
    type: generic
    invert: true
    exclude_any:
      - column: Footprint
        regex: TestPoint
outputs:
  - name: test_points
    type: position
    dir: +PCBA
    extends: position
    output_id: _test_points
    options:
      dnf_filter: test_points
      include_virtual: true
  - name: position
    type: position
    dir: +PCBA
    options:
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: false
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: Mid X
        - id: PosY
          name: Mid Y
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer
```
