### ISSUE TITLE
Unknown option `point_of_view`

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#399]
**What do you want to achieve?**
I want to use Blender Export.

`point_of_view` seems to be a option of `blender_export`.

I get this error from kibot:

```
ERROR:In section 'blender_3d_export' (blender_export): Unknown option `point_of_view`. Valid options: ['add_default_light', 'camera', 'dnf_filter', 'download', 'kicad_3d_url', 'light', 'no_virtual', 'outputs', 'pcb3d', 'pcb_import', 'pre_transform', 'render_options', 'rotate_x', 'rotate_y', 'rotate_z', 'variant', 'view'] (kibot - error.py:40)
```

Is this feature still under development?

**Do you have some configuration file (.kibot.yaml) that you are using?**
I used [this test](https://github.com/INTI-CMNB/KiBot/blob/master/tests/yaml_samples/blender_export_1.kibot.yaml)
```yaml
  - name: 'blender_3d_export'
    comment: "Exports the PCB in blender format"
    type: blender_export
    options:
      pcb3d: _PCB2Blender_2_1
      camera:
        name: MyCamera
        pos_x: 0.3
        pos_y: width*2
        pos_z: size*3
      render_options:
        transparent_background: true
        samples: 10
        resolution_x: 1920
        resolution_y: 1080
      point_of_view:
        rotate_x: 30
        rotate_z: -20
        view: bottom
      outputs:
        - type: blender
        - type: render
```

**Environment (please complete the following information):**
Running KiBot:
- In a CI/CD workflow, `GitLab` 
- Using docker image `kicad_auto:dev_k6`
