### ISSUE TITLE
Hierarchical Schematic file name diff problem

### ISSUE THREAD

**Issue by DusterTheFirst** [INTI-CMNB/KiBot#403]
**Describe the bug**
When making a diff of a sheet with hierarchical sub-sheets, their names will be shown as different even if it is the same old and new file

**To Reproduce**
Make a commit with changes not to any of the schematics, run kibot with the following config
```
outputs:
    - name: Schematic Changes
      comment: Schematic diff
      type: diff
      dir: sch
      options:
          pcb: false
          only_different: true
          old: HEAD~
```

**Expected behavior**
The diff should show no changes

**Screenshots**
[avionics-diff_sch.pdf](https://github.com/INTI-CMNB/KiBot/files/10942810/avionics-diff_sch.pdf)

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? `kicad6_auto_full:latest`
