### ISSUE TITLE
[HOW] What is the intended way to use kibot with gitlab CI and a multipages projekt 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#404]
**What do you want to achieve?**
I have a projekt with multible hierarchical pages (33 pages) and i want to use it with kibot to generate Produktion data and Documentation. It has worked for the example projekt with just 1 page and the config of the gitlab example: https://gitlab.com/set-soft/kicad-ci-test

**Do you have some PCB/Schematic to use as example?**
My CI config: 

```
erc:
  stage: run_erc
  tags:
    - KiBot
  script:
    - "[ -f *.kicad_sch ] && kibot -d ERC_DRC -s update_xml,run_drc -i"
  rules:
    - if: $CI_COMMIT_TAG =~ /^(preview|prerelease|release)_([0-9]{2}.[0-9]{4}.[0-9]{2})_([a-z,A-Z][0-9])/
    - changes:
      - "**.kicad_sch"
      - ".gitlab-ci.yml"
      when: always
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ERC_DRC/

drc:
  stage: run_drc
  tags:
    - KiBot
  script:
    - "[ -f *.kicad_pcb ] && kibot -d ERC_DRC -s update_xml,run_erc -i"
  rules:
    - if: $CI_COMMIT_TAG =~ /^(preview|prerelease|release)_([0-9]{2}.[0-9]{4}.[0-9]{2})_([a-z,A-Z][0-9])/
    - changes:
      - "**.kicad_pcb"
      - ".gitlab-ci.yml"
      when: always
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ERC_DRC/


docu_outputs:
  stage: gen_fab
  tags:
    - KiBot
  script:
    - "[ -f *.kicad_sch ] && kibot  -d Docu -s run_drc,run_erc print_sch print_pcb_pdf report_full report_history report_pcb_svg interactive_bom"
  rules:
    - if: $CI_COMMIT_TAG =~ /^(preview|prerelease|release)_([0-9]{2}.[0-9]{4}.[0-9]{2})_([a-z,A-Z][0-9])/
  needs: 
    - job: erc
    - job: drc
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - Docu/

```
**problem**

With this config all kicad_sch related JOBs fail with 

```
$ [ -f *.kicad_sch ] && kibot -d ERC_DRC -s update_xml,run_drc -i
/bin/bash: line 129: [: too many arguments
```

If i changed it to:

```
 [ -f *.kicad_pro] && kibot -d ERC_DRC -s update_xml,run_drc -i
```

i get the warning
```
 WARNING:(W044) More than one SCH file found in `.`.
  Using ./EMOB2.kicad_sch if you want to use another use -e option. (kibot - kiplot.py:753)
```
I am not sure of the consequences of this config.

what i noticed: the ERC kibot run only generates only 63errors, the ERC run in KiCAD  over 800 (its a new projekt work in progress)

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? `GitLab`
- Using a docker image? `kicad_auto:dev_k6`,
