### ISSUE TITLE
[HOW] to generate diff files on non A4 sized schematics

### ISSUE THREAD

**Issue by Harmhongerkamp** [INTI-CMNB/KiBot#409]
**What do you want to achieve?**
i have some project that contain schematics which are A3 or A2 sizes, with multiple variants. I want to diff them between variants and various commits. 
this works whit projects that contain A4 sized schematics, but not with A2 and A3 sized ones. 

**Do you have some PCB/Schematic to use as example?**
yes, see attached

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml
kibot:
  version: 1
outputs:
  # Documentation -------------------------------------------------------------
  - name: 'schematic'
    comment: "Export schematic as pdf"
    type: pdf_sch_print
    dir: documentation
  # ---------------------------------------------------------------------------
  - name: "sch_variant"
    type: sch_variant
    comment: "Generate sch variant for other outputs to use"
    dir: /tmp

  - name: "schdiff local<>master"
    type: diff
    dir: documentation/diffs
    options: 
      output: '%f-%v-schdiff-pr.%x'
      new: "sch_variant"
      new_type: output
      old: master
      old_type: git
      pcb: false
      force_checkout: true
      only_first_sch_page: false
    priority: 10
  #TODO
  - name: "schdiff local<>last"
    type: diff
    comment: "Generate diff"
    dir: documentation/diffs
    options: 
      output: '%f-%v-schdiff-commit.%x'
      new: "sch_variant"
      new_type: output
      old: "HEAD~"
      old_type: git
      pcb: false
      force_checkout: true
      only_first_sch_page: false
    priority: 10
```

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? 
  - `kicad6_auto:latest` with git-lfs added.
- Using a desktop system? Which OS, distro and version?
  - ubuntu 20-04 lts. (probably not relevant since is use a docker image"
**Additional context**
Add any other context about your setup/project.
[example_project.zip](https://github.com/INTI-CMNB/KiBot/files/11091217/example_project.zip)
