### ISSUE TITLE
[BUG] Cannot locate resource error when running KiBot on latest kicad7 image

### ISSUE THREAD

**Issue by Informaticore** [INTI-CMNB/KiBot#424]
Running the following KiBot workflow crashes with an error. I got the workflow together with the KiCad CI Template from nerdyscout. I changed the docker image to run the latest kicad7 image.

Workflow sample:
```
  render:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: ghcr.io/inti-cmnb/kicad7_auto:latest
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            board_black_top.svg board_black_bottom.svg
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_img
          if-no-files-found: error
          path: |
            ${{env.dir}}/img/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
```

Error:
```
ERROR:PcbDraw error: Cannot locate resource /usr/share/pcbdraw/styles/set-black-cu.json; explored paths:
- /usr/share/kibot/pcbdraw
- /github/home/.local/share/pcbdraw
- /usr/share/pcbdraw (kibot - out_pcbdraw.py:500)
Error: Process completed with exit code 20.
```

The full log can be found here: https://github.com/open-thngs/dps368-breakout/actions/runs/4677071263/jobs/8284185944
and the workflow file used here: https://github.com/open-thngs/dps368-breakout/actions/runs/4677071263/workflow

somehow it can not find the set-black-cu.json.
