### ISSUE TITLE
[HOW] Panel is missing copper fill

### ISSUE THREAD

**Issue by gcormier** [INTI-CMNB/KiBot#440]
I'm using KiBot with GitHub Actions. I have two pipelines - one is a simple fabrication pipeline for the board, works fine. The 2nd is a panelize pipeline.

The panelize version is missing the copper fill/pour - in this design, this is the bottom layer.

Single
![image](https://github.com/INTI-CMNB/KiBot/assets/8388983/ffaad534-2ca6-4243-95e0-dab7c2ffb3e9)

Panel
![image](https://github.com/INTI-CMNB/KiBot/assets/8388983/337f5195-1ca2-4044-995d-dff32962e20b)

The workflow - https://github.com/gcormier/kicad-jobs/blob/main/.github/workflows/kicad-fabrication-panel.yaml and relevant steps

**Step 1 - Panel**
```
# Generate the panel first
      - name: KiBot (Panel)
        uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: pcb/kibot-panel.yaml
          dir: ${{ env.PanelFolder }} 
          schema: pcb/${{ env.BaseFileName }}.kicad_sch
          board: pcb/${{ env.BaseFileName }}.kicad_pcb
```
kibot-panel.yaml : [kibot-panel.txt](https://github.com/INTI-CMNB/KiBot/files/11482318/kibot-panel.txt)

**Step 2 - Run the fabrication pipeline using the panel PCB file**
```
# Generate fab output based on panel
      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_k7
        with:
          config: pcb/kibot.yaml
          dir: ${{ env.PanelFolder }} 
          schema: pcb/${{ env.BaseFileName }}.kicad_sch
          board: ${{ env.PanelFolder }}/${{ env.BaseFileName }}-panel.kicad_pcb
```
kibot.yaml : [kibot.txt](https://github.com/INTI-CMNB/KiBot/files/11482328/kibot.txt)

Any help would be greatly appreciated.
