### ISSUE TITLE
[BUG] Scaling of images in schematics fails when doing variant exports

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#451]
**Describe the bug**
I realized that for some reason kibot does scale the images incorrectly if you do `pdf_sch_print` with a variant.

**Export without variant:**

![grafik](https://github.com/INTI-CMNB/KiBot/assets/75754060/12a72b99-494e-44f8-ba99-edb31ac2bfcd)

**Export with variant:**

![grafik](https://github.com/INTI-CMNB/KiBot/assets/75754060/0f9f4e98-6727-4a0b-9ea5-4707ce563f4c)

**To Reproduce**

[Test.zip](https://github.com/INTI-CMNB/KiBot/files/11753235/Test.zip)

**Kibot Config**

```
variants:
  - name: 'default'
    comment: 'Variant with default C1, C2 = 100 nF, C3 = 100 uF R1 = 100 Ohm, R2 = 100 Ohm'
    type: kibom
    file_id: _default
    variant: default
    pre_transform: '_var_rename'
    exclude_filter: _none
  - name: 'variant_1'
    comment: 'Variant with default C1, C2 = 220 nF, without C3 R1 = 0 Ohm, R2 = 50 Ohm'
    type: kibom
    file_id: _variant_1
    variant: variant_1
    pre_transform: '_var_rename'
    exclude_filter: _none
  - name: 'variant_2'
    comment: 'Variant with default C1, C2 = 10 nF, without C3 R1 = 50 Ohm, R2 = 0 Ohm'
    type: kibom
    file_id: _variant_2
    variant: variant_2
    pre_transform: '_var_rename'
    exclude_filter: _none

outputs:    
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
```
KiBot Call

```
kibot -d Schematics/default/ 
         -s run_drc,run_erc 
             print_sch

kibot -g variant=variant_1
         -d Schematics/variant_1/ 
         -s run_drc,run_erc 
             print_sch
```

**Expected behavior**

Scaling images if doing variant export as scaling if export without variant.

**Environment :**
Where are you running KiBot:
- In a CI/CD workflow (`GitLab`)
- Using docker image (`kicad7_auto:dev`)
