### ISSUE TITLE
[Feature] Pick-n-Place fully quoted for EuroCircuits

### ISSUE THREAD

**Issue by andersruneson** [INTI-CMNB/KiBot#456]
**Describe the bug**
When uploading a CSV pick-n-place file to EuroCircuits it triggers their "Identify which column to use" dialog which adds manual work for each board ordered.

The issue seems to be a CSV with some columns having quotation marks and some don't. 

**To Reproduce**
Go to eurocuiruits.com, create account, do upload PCB-gerber-zip-file, upload the BOM and then upload a CSV pick-n-place-file generated by KiBot.

![Screenshot from 2023-06-26 12-41-12](https://github.com/INTI-CMNB/KiBot/assets/1451776/7aafa864-d33f-4780-b180-ba8927055e7d)

The generated pick-n-place-file looks like this:
```
Ref,Val,Package,PosX,PosY,Rot,Side
"C1","YAGEO_CC0402JRNPO9BN270","CAPC100X50X55L25N[0402]",144.1500,-27.7500,180.0000,top
"C2","YAGEO_CC1206KKX7R7BB225","CAPC320X160X125L50N[1206]",144.1000,-40.6000,270.0000,top
"C3","TAIYO_EMK107B7104KAHT","CAPC160X80X90L35N[0603]",142.5000,-27.4000,270.0000,top
```

If I add quotation marks " on each column like below, EuroCircuits can read the file fine:
```
Ref,Val,Package,PosX,PosY,Rot,Side
"C1","YAGEO_CC0402JRNPO9BN270","CAPC100X50X55L25N[0402]","144.1500","-27.7500","180.0000","top"
"C2","YAGEO_CC1206KKX7R7BB225","CAPC320X160X125L50N[1206]","144.1000","-40.6000","270.0000","top"
"C3","TAIYO_EMK107B7104KAHT","CAPC160X80X90L35N[0603]","142.5000","-27.4000","270.0000","top"
```

This is the output configuration we use for EuroCircuits:
```
# Same as our generic PNP, but without DNP components
- name: eurocircuits_CSV
  comment: Components position for Pick & Place
  type: position
  dir: 'Manufacturers/EuroCircuits'
  run_by_default: true
  options:
    output: '@EA@-@EArevLong@ EuroCircuits CPL.%x'
    format: CSV
    only_smd: false
    dnf_filter: 
    - no_x_in_DNP_field
    - _mechanical
    - elysics_extra_mech
    separate_files_for_front_and_back: false
```

**Expected behavior**
The import at EuroCircuits should happen automatically.

To be fair, the bug is at EuroCircuits, so I've reach out to them as well to get them to correct their parsing. But maybe add an option to have quotation marks on all columns?

**Screenshots**
See above.

**Environment (please complete the following information):**

**Additional context**
