### ISSUE TITLE
[HOW] kikit_present with just exported files

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#461]
**What do you want to achieve?**
I want to use the `kikit_present` export to create a project webpage.

My problem is that I still have exported via kibot all filles I want to add but `kikit_present` runs his own config in kibot and adds this exports.

If I say `mode: file` it uses my files but still have set the file type in the background.

```yaml
  - name: 'kikit_present'
    comment: 'Create a deployed Webpage for file presentation'
    type: kikit_present
    dir: .
    options:
      description: kicad-ci-tests.md
      name: 'kicad-ci-tests Version 1'
      boards:
        mode: file
        front_image: Production/Images/kicad-ci-tests-3D_blender_top.png
        back_image: Production/Images/kicad-ci-tests-3D_blender_bottom.png
        gerbers: Production/default/Production_default.zip
        pcb_file: Production/Documentation/Documentation.pdf
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow (`GitLab`)
- Using a docker image? (`kicad7_auto_full:dev `)

**Additional context**
Could we add additional files with any type to the `Available files` section?
