### ISSUE TITLE
[HOW] Image quality of `render_3d`

### ISSUE THREAD

**Issue by dmohns** [INTI-CMNB/KiBot#463]
Hey,

**What do you want to achieve?**

I'm trying to render some 3D images as PNG. It works and KiBot generates some output file. However the output is of extremely low quality. I'm wondering how can I increase the DPI for example?

**Do you have some configuration file (.kibot.yaml) that you are using?**

You can attach it or paste the content in the following section:
```yaml
outputs:
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: Assembly
- name: basic_render_3d_30deg
  comment: 3D view from 30 degrees
  type: render_3d
  dir: 3D
  output_id: 30deg
  options:
    realistic: true
    rotate_x: 3
    rotate_z: -2
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? locally
- Using a docker image? (`kicad7_auto_full`)
- Using a desktop system? MacOS

**Comment by set-soft** [comment]
Hi @dmohns !
For *render_3d* you'll get much better results using `ray_tracing: true`.
But if you are looking for high quality just switch to *blender_export* option.
Here is one [example](https://github.com/INTI-CMNB/kibot_variants_arduprog)
I guess you are looking for quality, not image size (DPI).

**Comment by dmohns** [comment]
> Hi @dmohns ! For _render_3d_ you'll get much better results using `ray_tracing: true`. But if you are looking for high quality just switch to _blender_export_ option. Here is one [example](https://github.com/INTI-CMNB/kibot_variants_arduprog) I guess you are looking for quality, not image size (DPI).

Hey @set-soft thanks for the quick reply. I saw the possibility to use `blender_export`. But I'm specifically interested in generating images in a common image file format, preferably PNG. I don't think this is possible using `blender_export` without post-processing, right?

What I mean by quality is: The images generated by `render_3d` are very pixelated, it's hard to see anything on them. The DPI seems the same as KiCAD export, sorry for the confusion. It got better after playing around with the `width` and `height` settings.

**Comment by set-soft** [comment]
> I don't think this is possible using `blender_export` without post-processing, right?

It has a rendered output! You can generate PNGs.

> What I mean by quality is: The images generated by `render_3d` are very pixelated, it's hard to see anything on them. The DPI seems the same as KiCAD export, sorry for the confusion. It got better after playing around with the `width` and `height` settings.

Remember to enable the ray tracing option in your KiBot config

**Comment by dmohns** [comment]
> Remember to enable the ray tracing option in your KiBot config

Yeah, this already makes the image look much better.

> > I don't think this is possible using `blender_export` without post-processing, right?
> 
> It has a rendered output! You can generate PNGs.

Maybe it's just me, but the only output it is generating is a `pcb3d` file 🤔 This is my config

```
- name: 3D_top_view_HQ
  comment: "3D render from top (High Quality)"
  type: blender_export
  dir: 3D2
  options:
    render_options:
      transparent_background: true
      samples: 20
    point_of_view:
      rotate_x: 30
      rotate_z: -20
    outputs:
      - type: render
```
