### ISSUE TITLE
[BUG] change in behavior of compress 

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#473]
**Describe the bug**
After the switch to the Kicad7 train compress stops working if you use the source input and it  just generates an empty zip file.
For a another compress jop it just worked fine if the input is a another job output

This Workes just fine:

```
  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: JLCPCB
    options:
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

```

This generates an empty file in /Fabrication/

```
  - name: 'archiv'
    comment: "ZIP archive"
    type: compress
    dir: ../Fabrication
    options:
      files:
        - source: ../Fabrication/dril/*
          dest: /
        - source: ../Fabrication/Gerbers/*
          dest: /
        - source: ../Fabrication/JLCPCB/*
          dest: /
        - source: ../Fabrication/Produktion/*
          dest: /
        - source: ../Docu/report/*.pdf
          dest: /
      output: "EMS_Produktion_%D-%T.%x"
```

If I execute an `ls `  in the script i can see that it is in the right direktory and its filled with the same data  as the resulting job Artefakts.
It worked with the K6 dev docker some weeks ago.

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? `GitLab`
- Using a docker image? ghcr.io/inti-cmnb/kicad7_auto_full:dev
