### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Informaticore** [INTI-CMNB/KiBot#489]
**Describe the bug**
Render Blender PNG is missing. In my yaml file I am using:

```
outputs:
  - name: 'Blender 3D Image'
    type: 'blender_export'
    dir: 'Generated/render'
    options:
      point_of_view:
        rotate_x: 45
        rotate_y: 45
        rotate_z: 75
      pcb3d:
        download: true
      render_options:
        samples: 100
        transparent_background: true
      outputs:
        type: render
```

the container I am using is: `container: ghcr.io/inti-cmnb/kicad7_auto_full:latest`

I have not touched the config since a while and with my commit some time ago it was generating that PNG
