### ISSUE TITLE
[How] boardCommentN not honored by Kikit

### ISSUE THREAD

**Issue by Unichord** [INTI-CMNB/KiBot#497]
I'm automating panelization on Windows 10 WSL, it works well but some parameters are not passed to Kikit (or there is some other problem), as boardTitle, boardRevision and boardDate are passed correctly and they appear on the board. Comments, on the other hand, don't appear on the board, if I add some other text before or after {boardCommentN} in the yaml, it appears on the panel.

This is the yaml:
```
text3:
          type: simple
          hoffset: -25
          voffset: 4
          width: 4
          height: 4
          thickness: 0.4
          hjustify: right
          text: {boardComment2}
          anchor: tr
```

This is the kicad_pcb:
```
(paper "A4")
  (title_block
    (title "GFP1")
    (date "2023-09-18")
    (rev "1.0")
    (comment 2 "23.4480")
  )
```

By the way, is there a way to copy exactly the schematic Page Settings to the pcb Page Settings (board title, comments, company, etc)? I usually fill in the schematic only, and it's a bit of a hassle to copy all information in the pcb just for this to work. Otherwise, would it be possible to just pass external variables the same way it's done for other yaml? Like this:
```
text3:
          type: simple
          hoffset: -25
          voffset: 4
          width: 4
          height: 4
          thickness: 0.4
          hjustify: right
          text: ${my_var}
          anchor: tr
```
