### ISSUE TITLE
How to replace variables in the schematic header block

### ISSUE THREAD

**Issue by andersruneson** [INTI-CMNB/KiBot#508]
This may be a really stupid question, but I'm trying to use set_text_variables to replace the schematic title block variables and have no success. So is this possible?

This is what my title block looks like in the Drawing Sheet Editor:
![image](https://github.com/INTI-CMNB/KiBot/assets/1451776/a7d82f97-bcce-4fbf-b923-7e6b49c0103b)

And I've got a yaml that looks like this:
```
preflight:
  set_text_variables:
    - name: 'COMMENT1'
      text: 'COMMENT1'
    - name: 'Comment1'
      text: 'Comment1'
    - name: 'comment1'
      text: 'comment1'
    - name: 'Comment 1'
      text: 'Comment 1'
    - name: 'comment 1'
      text: 'comment 1'
    - name: 'title'
      text: 'TESTtitle'
    - name: 'TITLE'
      command: 'echo HEJ TITEL'
    - name: 'ISSUE_DATE'
      text: '12345'
    - name: 'REVISION'
      text: 'EA12345-AB EB...'

```

But nothing in the header is replaced when running the basic_pdf_sch_print output.

**Comment by andersruneson** [comment]
[testproject.zip](https://github.com/INTI-CMNB/KiBot/files/12898148/testproject.zip)
Attached is a testproject, in the small chance of me actually doing it correct.

**Comment by set-soft** [comment]
Hi @andersruneson !

You can't change the variables that are internally defined by KiCad. They are values you enter in the *Page Settings* dialog.

Also: KiCad interprets them in a case sensitive way. So you can actually use:

![image](https://github.com/INTI-CMNB/KiBot/assets/22823627/89535173-cdb7-43b7-918b-af4dad7af551)

And get:

![image](https://github.com/INTI-CMNB/KiBot/assets/22823627/83e1642e-ef4a-4e86-adf5-c8dcc4561717)

Using:

```yaml
kibot:
  version: 1

preflight:
  set_text_variables:
    - name: 'COMMENT1'
      text: 'COMMENT1'
    - name: 'Comment1'
      text: 'Comment1'
    - name: 'comment1'
      text: 'comment1'
    - name: 'Comment 1'
      text: 'Comment 1'
    - name: 'comment 1'
      text: 'comment 1'
    - name: 'title'
      text: 'TESTtitle'
    - name: 'TITLE'
      command: 'echo HEJ TITEL'
    - name: 'issue_date'
      text: '12345'
    - name: 'revision'
      text: 'EA12345-AB EB...'

outputs:
  - name: 'print_sch'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: .
    options:
      output: Schematic.pdf
```
