### ISSUE TITLE
[BUG] KiCad 7.x: ERC can't create a log file without extension

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#529]
Using the docker kicad7 full image, and defining `global.output: 'something/'`, causes kibot to try to save to a non-existant folder. Reviewing the video, we see that the save dialog of the erc pops up, tries to save the report, but then comes back to the result page waiting ...

Since we launch the erc with eeschema_do and the correct path, we can also ensure the path exists before launching eeschema_do, and maybe even create the folder in python.

**Comment by set-soft** [comment]
Hi @oliv3r !
You are misusing the options. The `output` is for the file name, the path should go to `dir`.

**Comment by set-soft** [comment]
I found the real problem: KiCad 7 is applying a nasty Windows behavior, assuming the user is stupid, and adding extensions to file names when you ask otherwise. So KiCad 7 can't create an ERC log file named "something". This is a bug in KiCad, I'll look for a workaround.

**Comment by set-soft** [comment]
The above patch implements a woraround so you can choose any name, even when KiCad 7  can't create report files with arbitrary names

**Comment by oliv3r** [comment]
Ah, i miss-undertsood the option. It was under 'global' so a single filename is a bit weird. As it would mean a single filename for each operation? I'll look into the 'path' option, but `global.output` to me, reads like 'all generated output goes here'...

Thanks for resolving the bug though :)

**Comment by oliv3r** [comment]
@set-soft I'm not sure the issue is completely resolved. I pushed by basic stuff into a temporary git repository, to get the pipeline going [0]. But I see 10 minute timeouts on erc. I pulled the video from the pipeline, and it tries to save the erc report using a `#` as a filename. After hitting the 'save' button, it just sits there indefinitely, well till it gets killed. (Why can't we run the erc via the cli/API yet ... *sigh*).

![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/750fbe93-3330-4064-b901-5d97a8c196a3)

Here's my kibot yaml file, which is very basic, as I want only the erc to run.
```yaml
kibot:
  version: 1

global:
  dir: 'reports'
  restore_project: true

preflight:
  erc_warnings: true
  run_drc: false
  run_erc: true
  set_text_variables:
    - name: 'VCS_SCH_TIMEDATE'
      command: 'date -d @$(git log -1 --format="%at" "${KIBOT_SCH_NAME}") -Iseconds'
    - name: 'VCS_SCH_HASH'
      command: 'git log -1 --format="%H" "${KIBOT_SCH_NAME}"'
      before: 'Git <'
      after: '>'
    - name: 'VCS_TAG'
      command: 'git describe --always --dirty'
```

[0]: https://gitlab.com/olliver/lapod/
