### ISSUE TITLE
[Question] Raytracing in kicad 7 full docker container produces images without traces, poor quality

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#531]
Using the following config:

```yaml
kibot:
  version: 1

global:
  environment:
    models_3d: '${KIPRJMOD}/packages3D'
  filters:
    - number: 9
      regex: 'KiCad config without environment.vars section'

outputs:
  - name: 'render_3d_front'
    comment: "Exports the image generated by KiCad's 3D viewer."
    type: 'render_3d'
    dir: 'output/render_3d/'
    options:
      auto_crop: true
      background1: '#66667f'
      background2: '#cccce5'
      board: '#332b16'
      clip_silk_on_via_annulus: true
      copper: '#8b898c'
      dnf_filter: '_none'
      download: false
      height: 1440
      highlight: []
      move_x: 0
      move_y: -2
      no_smd: false
      no_tht: false
      no_virtual: false
      orthographic: false
      pre_transform: '_none'
      ray_tracing: true
      realistic: true
      rotate_x: -5
      rotate_y: -1
      rotate_z: -3
      show_adhesive: false
      show_board_body: true
      show_comments: false
      show_components: all
      show_eco: false
      show_silkscreen: true
      show_soldermask: true
      show_solderpaste: true
      show_zones: true
      silk: '#d5dce4'
      solder_mask: '#208b47'
      solder_paste: '#808080'
      subtract_mask_from_silk: true
      transparent_background: false
      transparent_background_color: '#00ff00'
      transparent_background_fuzz: 15
      variant: ''
      view: 'front'
      wait_render: -600
      width: 1440
      zoom: 4
```

I get an image that does not contain any PCB traces. Doing it in my local kicad setup, the PCB renders perfectly.

![breakout_hdmi_raydesk](https://github.com/INTI-CMNB/KiBot/assets/1245341/34aea62d-98cf-401a-b2af-bde5f81470e0)
![breakout_hdmi-3D_front](https://github.com/INTI-CMNB/KiBot/assets/1245341/0e43297b-3142-4317-9805-b4bde44048b4)

If i turn of both realistic and raytracing, i get traces, but the soldermask is red/pink
![breakout_hdmi-3D_front](https://github.com/INTI-CMNB/KiBot/assets/1245341/18d8a08f-3601-4137-96b9-786b0cd11f64)

and if I turn on realistic only, i get a green PCB, but without traces.

Also, the quality is quite poor, compared to my local render ...

(note, that I know blender is/will be better, so I'm tackling that next :p)
