### ISSUE TITLE
[FEATURE] Support custom worksheets version 20220228

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#532]
With the kicad 7 full docker image, using my own worksheet, kibot complains about SHEETPATH being unknown and the version being incompatible. The version in the wks was made using kicad 7 and is dated feb 2022, so not that new.

```
WARNING:(W086) Unsupported worksheet version, loading could fail (kibot - worksheet.py:498)
WARNING:(W082) Unknown text variable `SHEETPATH` (kibot.gs - gs.py:407)
```

The outputs section I got from an kibot example, which looks like:
```yaml
  - name: 'pdf_pcb_print'
    comment: 'Exports the PCB to the most common exchange format. Suitable for printing.'
    type: 'pcb_print'
    dir: 'output/pdf'
    options:
      force_edge_cuts: true
      keep_temporal_files: false
      sheet_reference_layout: '../git.kicad_wks'
      scaling: 2.0
      pages:
        - layers: [ 'F.Paste', 'F.Adhes', 'Dwgs.User', 'F.Fab' ]
          sheet: 'Fabrication layers'
        - layers:
            - layer: 'F.Cu'
            - layer: 'F.Mask'
              color: '#14332440'
            - layer: 'F.SilkS'
            - layer: 'Dwgs.User'
          sheet: 'Top layer'
        - layers: [ 'In1.Cu', 'Dwgs.User' ]
          sheet: 'Inner1 plane'
        - layers: [ 'In2.Cu', 'Dwgs.User' ]
          sheet: 'Inner2 plane'
        - layers:
            - layer: 'B.Cu'
            - layer: 'B.Mask'
              color: '#14332440'
            - layer: 'B.SilkS'
            - layer: 'Dwgs.User'
          sheet: 'Bottom layer'
          mirror: true
```

I haven't really tweaked or modified it yet, but stumbled upon the error as I was going ...

I suppose the sheetpath error is not that relevant, as it's a follow up from the earlier error, about the unsupported wks version.

It does seem to somewhat work, the first page is empty, and the wks looks like the default, the other 4 sheets for do have my 'git' wks. All sheets however list the 'SHEETPATH' variable for the 'SHEET' field. Which I think kicad sets to '/'.

[git.kicad_wks.zip](https://github.com/INTI-CMNB/KiBot/files/13697213/git.kicad_wks.zip)
