### ISSUE TITLE
[FEATURE] compressed fab outputs should not keep source dirs

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#537]
While useful to retain the source files when compression of fab outputs is used, it is not needed in regular cases, also we can just unzip the compressed archives. As such, an option just as `keep_temporal_files` would be useful to be able to set to remove temporary files, having a cleaner output result.

```yaml
import:
- file: 'JLCPCB'
  definitions:
    _KIBOT_MANF_DIR: 'output/fab/JLCPCB'
    _KIBOT_POS_PRE_TRANSFORM: '[''_kicost_rename'', ''_rot_footprint'']'
```
