### ISSUE TITLE
Do not crash on missing files

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#540]
Running a (git) diff on files, where only one is available, the other file is usually/always treated as a '/dev/null' file. KiDiff should do the same, to avoid it crashing with the following error:

```
  File "/usr/lib/python3/dist-packages/kibot/out_diff.py", line 184, in cache_sch
    raise KiPlotConfigurationError('Missing file to compare: `{}`'.format(name))

ERROR:In section 'diffsch' (diff): Missing file to compare: `my_first.kicad_sch` (kibot.gs - gs.py:733)
```

E.g. this happens with the following kibot config:

```yaml
kibot:
  version: 1

global:
  environment:
    models_3d: '${KIPRJMOD}/packages3D'
  filters:
    - filter: 'KiCad 7 does not have environment.vars anymore. kibot#528'
      number: 9
      regex: 'KiCad config without environment.vars section'

outputs:
  - name: 'diffsch'
    comment: 'Generates a PDF with the differences between schematic.'
    type: 'diff'
    dir: 'outputs/diff'
    options: &diff_options
      add_link_id: false
      always_fail_if_missing: true
      cache_dir: '/tmp/pdfdiff'
      copy_instead_of_link: false
      diff_mode: 'red_green'
      force_checkout: false
      fuzz: 5
      new: 'HEAD'
      new_type: 'git'
      old: 'master'
      old_type: 'git'
      only_different: true
      only_first_sch_page: false
      threshold: 0
      use_file_id: false
      pcb: false
    layers: 'all'
  - name: 'diffpcb'
    comment: 'Generates a PDF with the differences between PCBs.'
    type: 'diff'
    dir: 'output/diff'
    options:
      <<: *diff_options
      pcb: true
    layers: 'all'
```

where master does not yet contain any file to diff against.

Though I just realize, this may be only a bug for kibot and I put it in the wrong spot, or maybe it's applicable to both ;)
