### ISSUE TITLE
[BUG] VRML job hangs even after successful file creation, when using a symlink as target directory

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#544]
Using the latest kibot 7 full container, generating a VRML, never closes kicad.

Looking at the video, we see that the file is generated and saved properly, but kicad does not exit, causing a timeout error to fail everything.

The used yaml file:

```yaml
kibot:
  version: 1

global:
  environment:
    models_3d: '${KIPRJMOD}/packages3D'
  filters:
    - filter: 'KiCad 7 does not have environment.vars anymore. kibot#528'
      number: 9
      regex: 'KiCad config without environment.vars section'

preflight:
  run_drc: false
  run_erc: false

outputs:
  - name: 'vrml'
    comment: 'PCB in VRML format'
    type: 'vrml'
    dir: 'outputs/vrml'
    options:
      download: false
      dir_models: ''
```

See https://gitlab.com/olliver/lapod/-/jobs/5836088539 and https://gitlab.com/olliver/lapod/-/pipelines/1122395553
