### ISSUE TITLE
[BUG] Text search in PCB output is broken

### ISSUE THREAD

**Issue by martinlofgren** [INTI-CMNB/KiBot#552]
**Describe the bug**
Text search in `pcb_print` used to work before, but doesn't anymore.

**To Reproduce**
Using the KiBot config file with the following output:
```yaml
  - name: 'Assembly_drawing_top'
    comment: "Assembly drawing top"
    type: pcb_print
    dir: 'output/Assembly_drawing'
    options:
      force_edge_cuts: true
      format: 'PDF'
      output: Assembly_top.pdf
      plot_sheet_reference: true
      pages:
        - layers: [ F.Paste, F.Silkscreen, F.Fab ]
          sheet: 'Assembly drawing top'
          monochrome: true
```

Running in Docker with the following command:

```sh
$ docker run -it \
    -v $(pwd):/data \
    -w /data \
    ghcr.io/inti-cmnb/kicad7_auto:latest \
    kibot -v -b project.kicad_pcb -c KiBotConfig/config.yaml Assembly_drawing_top
```

**Expected behavior**
Should render a pcb drawing with searchable text.

**Environment**
Have been running this in the context of a Gitlab CI job, but also in Docker in an Arch Linux system.

Previous, text search was functioning. I did try to run the same project using different versions, seems like the bug was introduced between [1.6.3-1_k7.0.5.1_d11.6](https://github.com/inti-cmnb/kicad_auto/pkgs/container/kicad7_auto/118459788?tag=1.6.3-1_k7.0.5.1_d11.6) and [1.6.3-1_k7.0.7_d12.1](https://github.com/inti-cmnb/kicad_auto/pkgs/container/kicad7_auto/135684285?tag=1.6.3-1_k7.0.7_d12.1).
