### ISSUE TITLE
[FEATURE] Have proper defaults for all supported fab houses

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#554]
Currently, when I have defined multiple layers to make things easier to handle between different projects, not all layers may be existing in the pcb file.

Currently, we fail with

```
  File "/usr/local/lib/python3.11/dist-packages/kibot/out_pcb_print.py", line 230, in config
    self.layers = LayerOptions.solve(self.layers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kibot/layer.py", line 224, in solve
    raise PlotError("Inner layer `{}` is not valid for this board".format(layer))
kibot.error.PlotError: Inner layer `In1.Cu (1 'Inner layer 1' In1_Cu)` is not valid for this board
```

However, it would be nice if kibot would just 'skip' that layer (with a unique ignoreable warning if needed).

I can solve this on the outside of course, by scanning the pcb file (using grep for example), and then generate the needed yaml entries. However that's far uglier and more complex, where instead we can just skip missing layers.

**Comment by set-soft** [comment]
Hmmm ... I think you are looking for the following:

```yaml
# Example KiBot config file
kibot:
  version: 1

outputs:
  - name: 'print_front'
    comment: "Print Top and Bottom layers"
    type: pcb_print
    dir: Layers
    options:
      format: 'PDF'
      keep_temporal_files: true
      pages:
        - sheet: '%ln'
          repeat_for_layer: 'F.Cu'
          repeat_layers: copper
          layers:
            - layer: Edge.Cuts
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.Paste
            - layer: F.SilkS
            - layer: F.Fab
              plot_footprint_refs: false
              plot_footprint_values: false
            - layer: Dwgs.User
```

This will generate 1 page for each copper layer, all of them using the same "template"

**Comment by set-soft** [comment]
While looking at this example I also added this:

```yaml
# Example KiBot config file
kibot:
  version: 1

outputs:
  - name: 'print_front'
    comment: "Print Top and Bottom layers"
    type: pcb_print
    dir: Layers
    options:
      format: 'PDF'
      keep_temporal_files: true
      pages:
        - scaling: 2.0
          sheet: '%ln'
          repeat_for_layer: 'F.Cu'
          repeat_layers: outers
          layers:
            - layer: Edge.Cuts
            - layer: F.Cu
            - layer: F.Mask
              color: '#14332440'
            - layer: F.Paste
            - layer: F.SilkS
            - layer: F.Fab
              plot_footprint_refs: false
              plot_footprint_values: false
            - layer: Dwgs.User
        - scaling: 2.0
          sheet: '%ln'
          repeat_for_layer: 'F.Cu'
          repeat_layers: inners
          layers:
            - layer: Edge.Cuts
            - layer: F.Cu
            - layer: F.SilkS
            - layer: Dwgs.User
```

So you can separate inner/outer layers
