### ISSUE TITLE
[FEATURE] PDF Scaling should honor grid origin

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#573]
Currently, when scaling, kibot scales from the 0,0 starting point, and everything becomes bigger towards the bottom right corner. Or maybe even, with 0,0 as our starting point, we 'bloom' outwards.

However, not only does the bottom right corner contain the PCB worksheet stuff, we also dissproportionally push stuff into the right corner, so that the result is off-center.

Instead, we should honor the grid-origin as our starting point, and bloom outwards from there. The result is that we scale nicely and proportionally, so that the image always remains in the center, and 'blooms' outwards from the center (center being where `grid_origin` is defined. This also fills the image more equally and is slightly less likely to overrun the worksheet corner.

Also this helps tremendously with the 'mirroring' feature, because mirroring is done after scaling, a mirrored page is also of center by the opposite amount. Also here, by scaling based on the `grid_center` we completely avoid/ignore this issue, resulting in far nicer scaled images.

Obviously this does require the user to define the `grid_origin` in the pcb file, but that should be a good idea anyway.

(If `grid_origin is deemed inappropriate, we can also use `aux_axis_origin` as well).

**Comment by oliv3r** [comment]
@set-soft Absolutely! and sorry for the delay :)

![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/86d78bc4-62d7-4772-9900-c540f84f2efe)

Here you can see, that with a scaling of 1.5, the image is scaled from the top left, towards the bottom left. You can see the center is no longer the center.

```yaml
kibot:
  version: 1

import:
  - file: 'kici_common.kibot.yaml'

outputs:
  - name: 'pdf_sch_print'
    comment: 'Exports the schematic to the most common exchange format. Suitable for printing.'
    type: 'pdf_sch_print'
    dir: 'outputs/pdf'
    options:
      all_pages: true
      background_color: false
      frame: true
      monochrome: false
  - name: 'pdf_pcb_print'
    comment: 'Exports the PCB to the most common exchange format. Suitable for printing.'
    type: 'pcb_print'
    dir: 'outputs/pdf'
    options:
      force_edge_cuts: true
      format: 'PDF'
      individual_page_scaling: false
      keep_temporal_files: false
      scaling: @KICI_PDF_SCALING@
      pages:
        - sheet: 'PCB top'
          layers:
          - layer: 'F.Cu'
          - layer: 'F.Mask'
            color: '@KICI_PDF_COLOR_PCB_MASK@'
          - layer: 'F.SilkS'
            color: '@KICI_PDF_COLOR_PCB_SILK@'
          - layer: 'User.Comments'
        - sheet: 'Fabrication top'
          layers:
          - layer: 'F.Fab'
          - layer: 'F.Paste'
          - layer: 'F.Adhes'
          - layer: 'User.Comments'
        - sheet: 'Silkscreen top'
          layers:
          - layer: 'F.SilkS'
        - sheet: 'F.Cu'
          layers:
          - layer: 'F.Cu'
        - sheet: '%ln layer'
          repeat_for_layer: 'F.Cu'
          repeat_layers: 'inners'
          layers:
          - layer: 'F.Cu'
        - sheet: 'B.Cu'
          layers:
          - layer: 'B.Cu'
        - sheet: 'Silkscreen bottom'
          layers:
          - layer: 'B.SilkS'
          mirror: true
        - sheet: 'Fabrication bottom'
          layers:
          - layer: 'B.Fab'
          - layer: 'B.Paste'
          - layer: 'B.Adhes'
          - layer: 'User.Comments'
          mirror: true
        - sheet: 'PCB bottom'
          layers:
          - layer: 'B.Cu'
          - layer: 'B.Mask'
            color: '@KICI_PDF_COLOR_PCB_MASK@'
          - layer: 'B.SilkS'
            color: '@KICI_PDF_COLOR_PCB_SILK@'
          - layer: 'User.Comments'
          mirror: true
      plot_sheet_reference: true

...
definitions:
  KICI_PDF_SCALING: 1.5
  KICI_PDF_COLOR_PCB_MASK: '#14332440'
  KICI_PDF_COLOR_PCB_SILK: '#f2eda1ff'
```

(Luckily) the dimensions are unrelated, as a pure silkscreen page also has this same alignment issue. I'll attach the full pdf for reference.
[breakout_hdmi-assembly.pdf](https://github.com/INTI-CMNB/KiBot/files/14122786/breakout_hdmi-assembly.pdf)

**Comment by oliv3r** [comment]
@set-soft your amazing!!

> Ok, now I understand what do you mean with "scaled from the top left, towards the bottom left.", but this isn't the case. > The image is scaled and then centered.
Ahh, so it IS the dimensions that is responsible here. What confused me I suppose, was the fact that the layers without dimensions where also incorrectly centered?

If you would have centered first, and then scaled, it would have also worked? But I like your trick, it's good!

After pasting in those changes, I was a bit confused about the invert/force options, they read a little unnatural at first, but
![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/b82b4757-5a01-469b-af36-cdff2571edd3)

perfectly centered!

I'm so excited and happy now, I got all main functions of kibot working.

I'll figure out the re-use files bit out in the next few weeks, so that I can do present and navigate; and probably add kicanvas to the mix at that point too :)

Btw, when do you expect to release 1.6.4? When is the feature freeze? I see you are working on kicanvas now.

**Comment by set-soft** [comment]
> > Ok, now I understand what do you mean with "scaled from the top left, towards the bottom left.", but this isn't the case. 
> > The image is scaled and then centered.

>  Ahh, so it IS the dimensions that is responsible here. What confused me I suppose, was the fact that the layers without dimensions where also incorrectly centered?

But they ARE correctly centered!! The other pages affects the centering!! (remember you can ask for individual centering)

> If you would have centered first, and then scaled, it would have also worked? 

Not really, KiCad just computes the center, doesn't really matter the order. And is KiCad the one that does it.

> But I like your trick, it's good!
> 
> After pasting in those changes, I was a bit confused about the invert/force options, they read a little unnatural at first, but ![image](https://private-user-images.githubusercontent.com/1245341/301516862-b82b4757-5a01-469b-af36-cdff2571edd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTYxMjksIm5iZiI6MTcwNjc5NTgyOSwicGF0aCI6Ii8xMjQ1MzQxLzMwMTUxNjg2Mi1iODJiNDc1Ny01YTAxLTQ2OWItYWYzNi1jZGZmMjU3MWVkZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMTM1NzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWViOTcxZTEzODVhZTU2MGZmYWYzZDI2NDAwMWU0OWY0MjA2NWRiOTY1ZWRiNTI2ZWViNzY2MDY3MjczMzViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zsosEfYBLJzASH-vyrs62cSUrcd5Rif1NVEZ7wnQ7rA)
> 
> perfectly centered!
> 
> I'm so excited and happy now, I got all main functions of kibot working.
> 
> I'll figure out the re-use files bit out in the next few weeks, so that I can do present and navigate; and probably add kicanvas to the mix at that point too :)
> 
> Btw, when do you expect to release 1.6.4? When is the feature freeze? I see you are working on kicanvas now.

I want to do a release ASAP.

**Comment by oliv3r** [comment]
> But they ARE correctly centered!! 
Depending on the eye of the beholder :) but yes yes, they where :)

> I want to do a release ASAP.

For what it's worth, all the bugs/features I have found/was after are now in order, so I'd say it's "stable" enough.

Hopefully soon is in the next few days :p

**Comment by oliv3r** [comment]
@set-soft thanks for the tag :D Makes me super happy :)

Btw, I think my original feature request is still somewhat valid. You currently scale and then center, but the center is based on the sheet. Instead, the centering should happen based on `grid_origin` instead, again still due to the worksheet border.

If you look at the following screenshot, you see I tried to center my PCB slightly in the upper half, because that's where it LOOKS more centered (vertically).
![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/c4006346-476d-4d75-bb20-caee354c4537)

However, in the pdf, while perfectly according to instructions of course, it looks 'off' and not 'scaled but in the same location' anymore.

![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/c0d1b58f-a04d-49ef-bcfc-52b9add21339)


Logically, If `grid_origin` is unset in the pdf, what you do now is perfect. However, if it IS set, move the center of the _image_ to the center of the `grid_origin` instead.

This way, the center is what the user has designed the center to be (or rather, the `grid_origin`. I think you could also look for the dimensional center, `(dimension (type center) (layer "Dwgs.User")` in my case, but I think you can have multiple of those, so that'll become messy quickly, even though the intend is far more clear :)

**Comment by set-soft** [comment]
Hi @oliv3r !

You can do this with 1.6.4! 

Just choose any empty layer you want to indicate the center, lets say *User.Eco1*. 

Now draw anything you want to be used as center, lets say a *center dimension* and save your PCB. Then use something like:

```yaml
kibot:
  version: 1

outputs:
  - name: 'print_front'
    comment: "Experiment"
    type: pcb_print
    options:
      plot_sheet_reference: true
      format: 'PDF'
      scaling: 2.0
      pages:
        - layers:
            - layer: User.Eco1
              color: "#FFFFFF00"
              use_for_center: true
            - layer: F.Cu
              use_for_center: false
            - layer: Edge.Cuts
              color: "#FF4040"
              use_for_center: false
```

Do you get the idea? Explanation:

1. The first layer we plot is *User.Eco1* and we say this layer is the only one used for centering purposes. We also use white color to make it the same as the default background.
2. We plot the other layers on top of the *User.Eco1*, so the center dimension can't be seen

That's all, the center is defined by the drawings in the auxiliary layer. You have full control over what is used to center the PCB.
