### ISSUE TITLE
exclude_filter: '_none' does not working for csv bom output

### ISSUE THREAD

**Issue by honzakutil** [INTI-CMNB/KiBot#580]
I have following configuration:
```yaml
outputs:
  # Bill of Materials - in csv format
  - name: 'bom-csv'
    comment: "Bill of Materails - csv format"
    type: bom
    dir: 'outputs/variant_${board_name}${board_rev}_${act_variant}_prints${variant_prints}'
    options:
      output: '${board_name}${board_rev}_${act_variant}_prints${variant_prints}_BOM.%x'
      use_aux_axis_as_origin: true
      exclude_filter: '_none'
      ref_separator: ', '
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        separator: ';'
      columns:
        - field: Quantity Per PCB
          name: Qty
        - field: References
          name: Reference(s)
        - Value
        - Footprint
        - Description
```
After running KiBot with this configuration, all components with JP* (JP201, JP202 ...) are missing in the output csv file. I believe, that filter `_mechanical` is turned on by default for this type of output. I hoped, that I can disable it by using `exclude_filter: '_none'`, but it seems not to be working. Or, maybe I misunderstood the documentation?

If I replace solderjumper symbol (Jumper:SolderJumper_2_Open) with ordinary resistor symbol (Device:R) it works as expeted - parts are listed in the output. Component symbol library/name seems to be the trigger for this. I also tried renaming JP201->R201 and remove content of component description field, but none of these two worked.

Is there any way, how to make KiBot to include the solderjumper parts in the bom output? Or is it a bug and can it be fixed?

I am using KiBot 1.6.3, running in docker desktop on windows. KiBot instalation checker protocol follows: 
[esc5-tx1b_prints01_info.txt](https://github.com/INTI-CMNB/KiBot/files/14268496/esc5-tx1b_prints01_info.txt)
