### ISSUE TITLE
[HOW] Filter DNP components from the position files

### ISSUE THREAD

**Issue by andreasWallner** [INTI-CMNB/KiBot#586]
From the docs and https://github.com/INTI-CMNB/KiBot/issues/392#issuecomment-1460447474 I thought that components that have the DNP flag set in KiCad should be hidden from the bom/output files. I would like to generate position files for our production partners that don't include those components to prevent confusion.

What I tried until now, the latter ones were just tries at workarounds:
 - explicitly set the global `kicad_dnp_applied: true` (just to check, I understood this should be the default anyways)
 - a manual filter, but `exclude_not_in_bom` and `exclude_not_on_board` are for the other flags and not for DNP
 - try `dnf_filter: _kicost_dnp` 

**Do you have some PCB/Schematic to use as example?**
Just a single resistor with DNP enabled: [test.zip](https://github.com/INTI-CMNB/KiBot/files/14335061/test.zip)

**Do you have some configuration file (.kibot.yaml) that you are using?**
```yaml
kibot:
  version: 1

global:
  kicad_dnp_applied: true

outputs:
- name: basic_position_ASCII
  comment: Components position for Pick & Place
  type: position
  dir: Position
  options:
    format: ASCII
    only_smd: false
- name: basic_position_CSV
  comment: Components position for Pick & Place
  type: position
  dir: Position
  options:
    format: CSV
    only_smd: false
```

**Environment (please complete the following information):**
I'm running KiBot locally using the current (7cdb8c7dfbc0) container via `podman run --rm -it -v .:/workspace ghcr.io/inti-cmnb/kicad7_auto:latest /bin/bash -c 'cd /workspace; kibot'` (with KiBot 1.9.4, KiCad 7.10)
