### ISSUE TITLE
[HOW] How to have a DNP/DNF column in csv/xlsx/html BOMs

### ISSUE THREAD

**Issue by schneider-engineering** [INTI-CMNB/KiBot#602]
**What do you want to achieve?**
We would like to generate BOMs with DNP columns like this:

 Qty | References       | Footprint         | Value    | DNP |
| --- | ---------------- | ----------------- | -------- | --- |
| 5   | C5 C7 C9 C18 C20 | C_0402_1005Metric | 0.1µ 16V |     |
| 1   | C6               | C_0402_1005Metric | 0.1µ 16V | DNP |

The html variant with the additional, separate table and the xlsx DNF worksheet are nice and known, but not what we are looking for. For the CSV variant we do not know of any way to include components marked as DNP in the BOM.

Is this possible with KiBot?

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml
- name: 'bom_xlsx'
    comment: "Spreadsheet for the Bill of Materials"
    type: bom
    dir: bom
    options: &bom_options
      xlsx:
        title: '%p'
        logo: false
        digikey_link: Digikey
        highlight_empty: false
      columns:
        - Row
        - field: Quantity Per PCB
          name: Qty
        - References
        - Footprint
        - Value
        - Spec
        - Manufacturer
        - MPN
        - Description
        - Digikey
        - Notes

  - name: 'bom_html'
    comment: "HTML for the Bill of Materials"
    type: bom
    dir: bom
    options:
      <<: *bom_options
      format: HTML
      html:
        title: '%p'
        logo: false
        digikey_link: Digikey
        highlight_empty: false

  - name: 'bom_csv'
    comment: "CSV for the Bill of Materials"
    type: bom
    dir: bom
    options:
      <<: *bom_options
      format: CSV
      csv:
        hide_pcb_info: true
        hide_stats_info: true
```

**Environment (please complete the following information):**
ghcr.io/inti-cmnb/kicad8_auto_full:1.6.5 in gitlab ci
