### ISSUE TITLE
[HOW] Filter after grouping?

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#613]
**What do you want to achieve?**

For components that change values/manf# depending on variant, I would like to reuse fields from other components and only filter after those are "reused".

More specifically, there is a RES 100k in the schematic that changes to a RES 10k for a certain variant.   There are already 100k and 10k components of the same type else where which have a "lcsc#" part number.

I use the following to generate the LCSC bom:

``` 
filters:
  - name: only_lcsc_parts
    comment: Only parts with LCSC code
    type: generic
    include_only:
      - column: LCSC#
        regex: ^C(\d+|_TO_SELECT)
  - name: JLCPCB_bom
    comment: BoM for JLCPCB
    type: bom
    dir: +JLCPCB
    options:
      exclude_filter: only_jlc_parts
      ref_separator: ','
      group_fields: [Value, manf#]
      [...]
```

When I do not specify an lcsc# code while expecting to reuse a lcsc# code from another component, it does not appear in the BOM - probably because the filter is applied before.

When I specify the lcsc# code according to the variants, the result is as expected.  Example of a working example:
![image](https://github.com/INTI-CMNB/KiBot/assets/1504752/2d8bf868-0b87-400b-8a6a-72e084a061fb)

Is there a method to apply the filter after the grouping/reuse of the manufacturer code?

Edit:
This also implies that when the LSCC# code is only set in variants and not in the base value then the component is not selected either.
