### ISSUE TITLE
[BUG] text boxes inside schematic symbols not supported

### ISSUE THREAD

**Issue by nopeppermint** [INTI-CMNB/KiBot#621]
**Describe the bug**
I would like to generate an assembly plan with DNP components marked with a cross.

This works with the project https://github.com/INTI-CMNB/kibot_variants_arduprog the following settings:

kibot --log Generated/kibot.log -c V2/Assembly_DNP.kibot.yaml -b V2/Kicad/pcbname.kicad_pcb

Assembly_DNP.kibot.yaml:
```
kibot:
    version: 1
    
outputs:     
  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: Generated
    options:
      force_edge_cuts: true
      keep_temporal_files: false
      dnf_filter: _kibom_dnf_Config
      scaling: 2.0
      pages:
        - layers: [ F.Silkscreen, F.Fab ]
          sheet: 'Assembly Top'
        - layers: [ B.Silkscreen, B.Fab ]
          sheet: 'Assembly Bottom'
          mirror: true     
```

R1 is not assembled:

![image](https://github.com/INTI-CMNB/KiBot/assets/3403218/d635b623-2f50-4cce-b171-4c3cc4bd726f)

[t1-assembly (4).pdf](https://github.com/INTI-CMNB/KiBot/files/15403030/t1-assembly.4.pdf)

The Problem is, now that I changed to my own proprietary project which I can not share I got an error while parsing the schematic.
(Even though I am generating an assembly plan..)

```
ERROR:Unknown symbol attribute `[Symbol('text_box'), 'Bias & Int. Supply', [Symbol('at'), -11.43, 29.21, 0], [Symbol('size'), 8.255, -6.35], [Symbol('stroke'), [Symbol('width'), 0], [Symbol('type'), Symbol('default')]], [Symbol('fill'), [Symbol('type'), Symbol('none')]], [Symbol('effects'), [Symbol('font'), [Symbol('size'), 1.27, 1.27]]]]` (kibot.gs - gs.py:834)
```

I isolated the error source down to a single schematic symbol:
![image](https://github.com/INTI-CMNB/KiBot/assets/3403218/c21d782b-a5ca-4843-a4e2-8d89ce8648ca)

[test_schematic.zip](https://github.com/INTI-CMNB/KiBot/files/15403155/test_schematic.zip)

**Expected behavior**
- not caring about schematic when generating pcb pdf exports
- or supporting this symbol attribute

**Environment **
Where are you running KiBot:
- In a CI/CD workflow GitLab
- Which tag are you using? ghcr.io/inti-cmnb/kicad8_auto_full:latest
