### ISSUE TITLE
[HOW] variable expansion problem when using NET_NAME

### ISSUE THREAD

**Issue by MarkusSBS** [INTI-CMNB/KiBot#627]
**What do you want to achieve?**
I want to expand the value of a testpoint to the netname. something simulate is done in https://github.com/INTI-CMNB/KiBot/issues/511 and there should be a workaround but it does not work for me.

```
- name: tp_pos
    comment: "TestPoint Position and netname"
    type: position
    dir: PCB_Docu
    output_id: 'TestPoints'
    options:
      output: "${SBS_SAP}_%p-%v_Rev%r-%i_${SBS_Doc_status}_%D-${git_hash}.%x"
      format: ASCII
      units: millimeters
      only_smd: false
      use_aux_axis_as_origin: true
      include_virtual: true
      separate_files_for_front_and_back: false
      pre_transform:
        - "expand_var"
      dnf_filter:
        - "only_tp"`

 filters:
  - name: "only_tp"
    type: generic
    comment: "Select only testpoints"
    include_only:
      - column: References
        regex: '^[t,P][p,P]\d+' 
  
  - name: "expand_var"
    type: expand_text_vars
    comment: "Expand all text variable to their value"
    include_kicad_env: true
    include_os_env: false

kibot -d Docu -vvv -s run_drc,run_erc tp_pos
```

I can not find any problem in the log 

```
### Module positions - created on Thu 06 Jun 2024 11:25:30  ###
### Printed by KiBot
## Unit = mm, Angle = deg.
## Side : both
# Designator   Val              Package                Mid X       Mid Y      Rotation   Layer 
TP1            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -117.6652   98.0371    180.0000   bottom
TP2            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -120.5652   98.0371    180.0000   bottom
TP3            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -122.8652   98.0371    180.0000   bottom
TP4            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -125.3652   98.0371    180.0000   bottom
TP5            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -127.5652   98.0371    180.0000   bottom
TP6            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -130.4652   98.0371    180.0000   bottom
TP7            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -132.6652   98.0371    180.0000   bottom
TP8            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -135.4652   98.0371    180.0000   bottom
TP9            ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -137.7652   98.0371    180.0000   bottom
TP10           ${NET_NAME(1)}   TestPoint_Pad_D1.0mm   -140.3652   98.0371    180.0000   bottom

```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? (`GitLab`)
- Using a docker image? (ghcr.io/inti-cmnb/kicad7_auto_full:dev)

**Additional context**
Add any other context about your setup/project.
