### ISSUE TITLE
[BUG] ibom give error 2 running latest KiBot

### ISSUE THREAD

**Issue by andersruneson** [INTI-CMNB/KiBot#634]
**Describe the bug**
I've migrated a project to KiBot 8 but fail on ibom. The same happens when running kicad8_auto:dev on a KiCad 7 project that worked before. I'm not sure when this started but I've been running 1.6.5 without issues. 

This is the output from KiBot:
```
- 'Generic Bill of Materials in XLSX format' (prototype_bom_xlsx) [bom]
- 'Generic Bill of Materials in XML format' (single_per_row_bom_xml) [bom]
- 'Components position for Pick & Place' (basic_position_ASCII) [position]
- 'Components position for Pick & Place' (basic_position_CSV) [position]
- 'Top Assembly Drawing' (basic_top_pcb_print_pdf) [pcb_print]
- 'Bottom Assembly Drawing' (basic_bottom_pcb_print_pdf) [pcb_print]
- 'Top Conformal Coating' (basic_top_conformal_coating_pdf) [pcb_print]
- 'Bottom Conformal Coating' (basic_bottom_conformal_coating_pdf) [pcb_print]
- 'IPC-D-356 netlist for testing' (ipc_netlist) [netlist]
- 'Interactive HTML BoM' (basic_ibom) [ibom]
ERROR:Failed to create BoM, error 2 (kibot.gs - gs.py:836)
ERROR:P (kibot.gs - gs.py:846)
ERROR:p (kibot.gs - gs.py:846)
```

This is my config:
```
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: '@EA@-@EArevLong@ PCBA'
  run_by_default: true
  options:
    output: '@EA@-@EArevLong@ Interactive Assembly Drawing.%x'
    dnf_filter: 
    - _kibom_dnf_Config
    - elysics_extra_mech
    - _mechanical
    extra_data_file: '@EA@-@EArevLong@ BOM.xml'
    include_tracks: true
    include_nets: true
    highlight_pin1: true
    show_fields: 'MPN,Case,Value'
    group_fields: 'MPN'
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow in GitLab
- Using a docker image kicad8_auto:dev

**Comment by set-soft** [comment]
Hi @andersruneson !
I need something I can reproduce. I don't know what `elysics_extra_mech` is, or the content from `extra_data_file`
Did you try using debug information?
The message from ibom looks quite cryptic

**Comment by andersruneson** [comment]
Hi

Which debug information? Running the verbose (-v) output from kibot? 

elysics_extra_mech is a filter:
```
filters:
- name: elysics_extra_mech
  type: generic
  comment: 'Exclude Elysics extra mechanical'
  exclude_any:
    - column: No BOM
      regex: '.*(Yes|yes|1).*'
```

extra_data_file is the xml from this output:
```yaml
- name: single_per_row_bom_xml
  comment: Generic Bill of Materials in XML format
  type: bom
  run_by_default: true
  options:
    output: '@EA@-@EArevLong@ BOM.%x'
    format: XML
    group_fields: []
    group_connectors: false
    columns:
    - field: 'Part'
      name: 'ReferenceNumber'
    - field: 'References'
      name: 'Designator'
    - field: 'MPN'
      name: 'MPN'
    - field: 'Manufacturer'
      name: 'Manufacturer'
    - field: 'Footprint'
      name: 'Footprint'
    - field: 'MPN'
      name: 'MPN'
    - field: 'Description'
      name: 'Description'
    - field: 'Temperature'
      name: 'Temperature'
    - field: 'Value'
      name: 'Value'
    - field: 'Digi-Key'
      name: 'Digi-Key'
```
