### ISSUE TITLE
[How] PCB draw missing components 

### ISSUE THREAD

**Issue by rizwan-isa-3E** [INTI-CMNB/KiBot#641]
I am using Kibot to automaticaly output an image to show components. However, it doesnt do it. Here is my settings in the .yaml file:

```yaml
  - name: board_top_filled
    comment: "Top layer view with components"
    type: pcbdraw
    dir: PCB
    output_id: '-filled'
    options:
      format: jpg
      dpi: 300
      show_components: all
```

here is the output from the terminal window:

```
'Gerbers' (gerbers) [gerber]
'Drill files' (drill) [excellon]
'Pick & Place' (position) [position]
'PDF for the PCB' (print_pdf) [pcb_print]
'Top layer view' (board_top) [pcbdraw]
WARNING:(W103) (component) Component _footprints:7 has no footprint. (kibot - out_pcbdraw.py:43)
WARNING:(W103) (component) Component _footprints:B has no footprint. (kibot - out_pcbdraw.py:43)
'Top layer view with components' (board_top_filled) [pcbdraw]
'Bottom layer view' (board_bottom) [pcbdraw]
'Bottom layer view with components' (board_bottom_filled) [pcbdraw]
'STEP 3D model' (3D) [step]
```
