### ISSUE TITLE
[FEATURE] Temperature range check

### ISSUE THREAD

**Issue by andersruneson** [INTI-CMNB/KiBot#643]
**Is your feature request related to a problem? Please describe.**
When designing a board according to specification there is normally a product requirement that the board should work in a certain temperature range, like -40 to 85 deg Celsius, then all the components needs to fulfill this range and it would be convenient to have a check for that when running CI on my board.

**Describe the solution you'd like**
An output could be run created that makes a report which lists all components, their range and a separate list with the components that are out of range according to the defined configured range.

**Describe alternatives you've considered**
Could also just be a preflight like erc/drc which exits on out of range errors.

I was thinking that I could do this as a separate script to run in my CI-chain, but it would be much better to have the config settings for the range in the kibot-config. It would also be more work in totalt to make a separate script and then integrate into KiBot instead of just doing this directly in KiBot.

**Additional context**
Some example configuration below. There need to be some kind of setting (like below exit_error_on_out_of_range) so that KiBot would set an error just like a DRC error.

There is also need to configure which fields to look for temperature data, I don't use the built in KiCad libraries so I don't know how temperature data is normally stored in the components, but I assume one would use use one property with a range, or two properties with max and min data.

```
global:
  pcb_material: 'FR4'
  solder_mask_color: 'green'
  silk_screen_color: 'white'
  pcb_finish: 'ENIG'
  copper_thickness: 35
  temperature_range_max: 85
  temperature_range_min: 30

outputs:
- name: temperature
  comment: Simple temperature report
  type: temperature_report
  options:
    temp_max_field: "Temperature Max"
    temp_min_field: "Temperature Min"
    temp_range_field: "Temperature"
    temp_range_regex: "(-?\d+).+?(-?\d+).*"
    exit_error_on_out_of_range: true
```

Thanks for your feedback on this idea.
