### ISSUE TITLE
[BUG] Text variables not propagating to the PCB panel when the panelize output runs

### ISSUE THREAD

**Issue by soldermate** [INTI-CMNB/KiBot#652]
**Describe the bug**
Text variables not propagating to the PCB panel when the panelize output runs.  
The text variables are correctly substituted in the project, but the same variables when used in PCB layers are not substituted.

**To Reproduce**
command
`VERSION="foobar"`
`kibot -v -c board.kibot.yaml -e sch.kicad_sch -b pcb.kicad_pcb -E GIT_VERSION=$VERSION`

board.kibot.yaml
```
kibot:
  version: 1

global:
  out_dir: 'generated'
  output: '%f-@GIT_VERSION@_%i%I%v.%x'
  set_text_variables_before_output: true

preflight:
  set_text_variables:
    - name: 'GIT_VERSION'
      text: '@GIT_VERSION@'

outputs:
  - name: project_panel
    comment: Kicad panel project
    type: panelize
    dir: panel
    options:
      configs: panel_config.json
```

panel_config.json

```
{
    "layout": {
        "type": "grid",
        "rows": 1,
        "cols": 3,
        "hspace": "4.6mm",
        "vspace": "0mm",
        "rotation": "0deg",
        "alternation": "none",
        "renamenet": "Board_{n}-{orig}",
        "renameref": "{orig}"
    },
    "source": {
        "type": "auto",
        "tolerance": "10mm"
    },
    "tabs": {
        "type": "annotation"
    },
    "cuts": {
        "type": "mousebites",
        "drill": "0.8mm",
        "spacing": "1.3mm",
        "offset": "0.25mm",
        "prolong": "0.5mm"
    },
    "framing": {
        "type": "railstb",
        "mintotalheight": "120mm"
    },
    "fiducials": {
        "type": "3fid",
        "hoffset": "10mm",
        "voffset": "5mm",
        "coppersize": "1mm",
        "opening": "2mm"
    },
    "tooling": {
        "type": "4hole",
        "size": "3.9mm",
        "hoffset": "5mm",
        "voffset": "5mm"
    },
    "text": {
        "type": "simple",
        "text": "origin panel to board (x,y): 75mm, 19mm\nboard step (x,y): 95mm, 0.0mm",
        "layer": "F.SilkS",
        "anchor": "bl",
        "voffset": "-5mm",
        "hoffset": "15mm",
        "hjustify": "left"
    },
    "text2": {
        "type": "simple",
        "text": "origin panel to board (x,y): 75mm, 19mm\nboard step (x,y): 95mm, 0.0mm",
        "layer": "B.SilkS",
        "anchor": "br",
        "voffset": "-5mm",
        "hoffset": "-15mm",
        "hjustify": "left"
    },
    "post": {
        "type": "auto",
        "millradius": "1mm",
        "origin": "bl",
        "dimensions": "true"
    },
    "copperfill": {
        "type": "hatched",
        "clearance": "1mm"
    },
    "page": {
        "type": "A3"
    },
    "debug": {
        "trace": "true"
    }
}
```

**Expected behavior**
Text variables in PCB layers should be substituted in the generated panel project.

**Screenshots**
Correct substitution in project settings view after generating the panel
![taxt variable in project](https://github.com/user-attachments/assets/1ff344b0-b29f-4332-841f-539caa0c9e02)

Substition does not occur in PCB layer
![different_text](https://github.com/user-attachments/assets/885fb60d-28dc-45c5-96e9-4bf50353cd4b)

**Environment**
image: ghcr.io/inti-cmnb/kicad8_auto_full:dev

**Additional context**
