### ISSUE TITLE
[BUG] ERROR:In section 'pdf_pcb_print' (pcb_print): `repeat_for_layer` specified, but nothing to repeat

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#671]
With the update to 1.8(.2) I now am getting the following error:

```
ERROR:In section 'pdf_pcb_print' (pcb_print): `repeat_for_layer` specified, but nothing to repeat (kibot.gs - gs.py:845)
```

The code leading to this error is:
```
        - sheet: '%ln layer'
          repeat_for_layer: 'F.Cu'
          repeat_layers: 'inners'
          layers:
          - layer: 'F.Cu'
```
([Full code here](https://gitlab.com/ci-includes/kici/-/blob/master/kibot_jobs/kici_pdf.kibot.yaml#L51)).

The PCB in question does not actually have any inner layers, but when discussing this in the past, you hinted me towards this solution, which is generic and should work in both cases, if you only have 2 layers, or more. With 1.8(.2?) a change was introduced, that breaks this behavior.

Are there alternative solutions? The goal ultimately is to have a single configuration file, that works regardless of how many layers are used (though 2 as a minimum is 'okay' I suppose).
