### ISSUE TITLE
[FEATURE] Allow a different output location to be set for panelize:create_preview

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#672]
The panelize option for kikit works quite nice, and the `create_preview` option is pretty awesome.

However, when creating panels with the following config:
```
kibot:
  version: 1

import:
  - file: 'kici_common.kibot.yaml'

outputs:
  - name: 'panelize'
    run_by_default: @RUN_BY_DEFAULT@
    comment: 'Creates a panel to fabricate various copies of the PCB at once.'
    type: 'panelize'
    dir: 'outputs/panels'
    options:
      configs: @PANELIZE_CONFIG_JSON@
      create_preview: true

...
definitions:
  PANELIZE_CONFIG_JSON: 'kikit_panelize.json'
  RUN_BY_DEFAULT: true
```

the `dir` parameter nicely sets the output location of the kicad panel project, but the preview is not preferred to be stored there as well. Currently `create_preview` takes a boolean; maybe we can also accept a string to set a different dir location, could be relative to dir; e.g. `create_preview: '../png/'` for example.
