### ISSUE TITLE
[BUG] BoM doesn't exclude components outside the selected sub-PCB

### ISSUE THREAD

**Issue by dhaillant** [INTI-CMNB/KiBot#697]
In a KiCad project with multiple sub PCBs, it is currently possible to generate separate gerbers, renders and ibom of individual sub boards, based on variants.

In order to automate the creation of production files for assembly, it would be extremely convenient to be able to generate, in the same way, BoM and position files for each individual sub board.

In the current state, BoM and position files contain the complete list of components, of the entire project, regardless of variants. 
Importing such files to fab houses (example JLCPCB) generates errors as too many components, per boards, are reported and they are hence both not correctly positioned and out of the PCB limits.

The screenshot below shows that gerbers have been correctly generated for the sub PCB, but the components are present for all the boards:
![jlcpcb too many components and out of PCB](https://github.com/user-attachments/assets/96563c1b-ecb4-4e65-80c3-21c602fba341)

Variants (sub boards) are declared like this:
```variants:
  - name: 'sub_pcb'
    comment: 'Sub PCBs'
    type: ibom
    sub_pcbs:
      - name: front
        tlx: 100
        tly: 0
        brx: 170
        bry: 200
      - name: rear
        tlx: 170
        tly: 0
        brx: 220
        bry: 200
```

And the BoM output:
```
filters:
  - name: only_jlc_parts
    comment: 'Only parts with JLC (LCSC) code'
    type: generic
    include_only:
      - column: 'LCSC'
        regex: '^C\d+'

outputs:
  - name: 'bom_test'
    comment: "BoM Test"
    type: bom
    dir: JLCPCB
    options:
      output: 'test_%f_%i%v_jlc.%x'
      exclude_filter: 'only_jlc_parts'
      ref_separator: ','
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint
        - field: 'LCSC'
          name: 'LCSC Part #'
      csv:
        hide_pcb_info: false
        hide_stats_info: false
        quote_all: true
```

(this is based on https://github.com/INTI-CMNB/KiBot/blob/master/docs/samples/JLCPCB.kibot.yaml) 

See the demo project below, with kibot yaml tests:
[kibot_variants_bom_kicad8.zip](https://github.com/user-attachments/files/17407222/kibot_variants_bom_kicad8.zip)

Test with `make all` command.
In the demo project, variants are specified both though `-g` parameter and in yaml file:
"sub_boms" output uses `-g` parameter and "bom1" and "bom2" use yaml variant declaration.

KiCad 8.0.5 and KiBot 1.8.1
