### ISSUE TITLE
[HOW] Nested definitions in YAML file with imported files

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#717]
**What do you want to achieve?**
I have been trying for a while to use nested definitions as follows:

```
# kibot_main.yaml

kibot:
  version: 1

import:
  - file: kibot_globals.yaml
    definitions:
      OUTPUT_DIR: '@OUTPUT_DIR@'

definitions:
  OUTPUT_DIR: ../Generated_alt
```

```
# kibot_globals.yaml

kibot:
  version: 1

global:
  out_dir: '@OUTPUT_DIR@'
  dnp_cross_top_layer: '@LAYER_DNP_TOP@'
  dnp_cross_bottom_layer: '@LAYER_DNP_BOTTOM@'

definitions:
  OUTPUT_DIR: ../Generated
  LAYER_DNP_TOP: F.DNP
  LAYER_DNP_BOTTOM: B.DNP
```

But this results in:

`ERROR:Maximum depth of definition replacements reached, loop? (kibot - config_reader.py:664)`
`ERROR:Unknown section definitions in config. (kibot.gs - gs.py:881)`

Is it possible to achieve what I am trying to set up?

**Do you have some PCB/Schematic to use as example?**
`git clone git@github.com:EPFLXplore/XRE_LeggedRobot_HW.git`
`cd ./XRE_LeggedRobot_HW`
`git checkout 0812bf69eff7c518a2119d76e639c54d5a4da297`
`cd ./amulet_controller`
`kibot -c kibot_yaml/kibot_main.yaml`

**Environment (please complete the following information):**
WSL2 on Windows, running Ubuntu 24.04 LTS. Using the dev branch.
