### ISSUE TITLE
[FEATURE] Exclude filter for ibom Fabrication layers

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#721]
Fill as much as you can, remove the rest

**Is your feature request related to a problem? Please describe.**
Currently, when generating an HTML BOM, if `show_fabrication` option is true, all fabrication (graphics and reference designators) are shown. When there are many testpoints, the ibom can get really cluttered.
![image](https://github.com/user-attachments/assets/52ef94a8-291b-4553-b9d3-4c3973f65ac1)

**Describe the solution you'd like**
It would be nice to be able to specify an exclude_filter (similar to the current implementation of PCB Print), which would allow to hide specific components on the PCB.

**Describe alternatives you've considered**
I've thought about using the `hide_excluded` option and setting all testpoints as DNF, but that would result in a red cross on all testpoints in the schematic.

**Comment by set-soft** [comment]
Why not using a variant?

**Comment by nguyen-v** [comment]
> Why not using a variant?

I'm not sure how to achieve that. Let's say that I have the variants `FULL`, `NO_XT60` and `NO_SNUBBER`, does that mean that I would need to create three new variants `FULL_TP`, `NO_SNUBBER_TP` and `NO_XT60_TP`, set the `Config` field of the testpoints to: `-FULL_TP,-NO_SNUBBER_TP,-NO_XT60_TP` and in the yaml file do something like:

```
outputs:
- name: html_bom
  type: ibom
  options:
    show_fields: 'Value,Footprint,Manufacturer Part Number'
    group_fields: 'Value,Manufacturer Part Number'
    show_fabrication: true
	variant: '%V_TP`
```
Is there a better way, or do I have to create an 'alternate' variant for each variant?
