### ISSUE TITLE
[HOW] Cannot filter some warnings (KiCost warnings)

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#732]
**What do you want to achieve?**
I am trying to filter the warnings
`WARNING:(W044) More than one SCH file found in`
and
`WARNING:(WC007) No information found at...`

**Do you have some PCB/Schematic to use as example?**
```
git clone 
cd XRE_LeggedRobot_HW
git checkout 7d4c7431fc838160d85296a4f6985f6431626698
cd amulet_controller
./kibot_launch.sh

```
**Do you have some configuration file (.kibot.yaml) that you are using?**

https://github.com/EPFLXplore/XRE_LeggedRobot_HW/blob/7d4c7431fc838160d85296a4f6985f6431626698/amulet_controller/kibot_yaml/kibot_globals.yaml

This is my global section for the warning I am trying to ignore:

```
global:
  out_dir: '@OUTPUT_DIR@'
  dnp_cross_top_layer: '@LAYER_DNP_TOP@'
  dnp_cross_bottom_layer: '@LAYER_DNP_BOTTOM@'
  filters:
    # 'Ignore multiple schematics warning (hierarchical schematic). kibot#594'
    - number: 44
    # 'Ignore no information found at Distributor for Part (all information available in KiCost).'
    - number: 7
```

If I try to filter other warnings such as `WARNING:(W135) Value field mismatch for...` it seems to work. Are there some warnings that cannot be filtered?

**Environment (please complete the following information):**
Where are you running KiBot:
Windows 10, WSL2, dev branch
