### ISSUE TITLE
[BUG] Filter does not apply on "re-used" properties

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#736]
I guess this is somewhere between a bug and a feature.

I use the following filter for certain BOMs:
```yaml
filters:
  - name: only_lcsc_parts
    comment: Only parts with LCSC code
    type: generic
    include_only:
      - column: LCSC#
        regex: ^C\d+ 
```

However, this filter works on the components without using the reuseable information.

I have R11 and R15 and others that have 10k values.
However, R11 did not have the 'lcsc#' property field and was excluded from the BOM.

The typical use case is that when certain fields are empty, that they inherit their value from other components where this value is defined.

I am not sure what the best method is to cope with this as the field names are not all predetermined.

Prevention wise, I think a FieldCheck is appropriate to make sure all these fields are filled - either with a value number or with a "NULL" value.
