### ISSUE TITLE
[HOW/FEATURE] Generate outputs for all variants

### ISSUE THREAD

**Issue by Unichord** [INTI-CMNB/KiBot#737]
Hello, what I'm trying to do is a reusable script to generate all variants for every needed output (for my use case BOM, board PDF, pos file are needed) of a single project.

The variants are defined in a folder of the project, like this:
```
variants:
- name: default
  type: kibom
- name: Q
  type: kibom
  file_id: Q
  variant: Q
```

Then I defined a field in Kicad like this:
![Fields](https://github.com/user-attachments/assets/142ccb5e-4902-4c10-a6c1-f55625065183)

But I can't find a way to have all variants generated in the same run, unless doing something convoluted like using `--list-variants` and iterating through them, changing variables as I go.

Is there something I'm missing or doing wrong? Could it be easily done by Kibot itself?

Thanks in advance.

**Comment by Unichord** [comment]
I thought so, thanks for confirming.
Is this something on the roadmap that I can expect anytime soon? Would it be easy to implement in Kibot?

**Comment by set-soft** [comment]
The problem is about side effects.

The above patch implements a mechanism, you can use *--variant ALL* to specify you want to iterate all available variants. And you can even use *--variant ALL --variant NONE* to get all variants plus the case where no variant is in use.

It passes a very simple regression test that used repeated outputs and was adapted to use this mechanism. Can you test it?

**Comment by Unichord** [comment]
Surely I can test it, thank you! Do I find it on the docker image? I don't see any update on it, I did a pull on docker desktop. Is it correct?

**Comment by set-soft** [comment]
Is in the docker images tagged as *dev* i.e. 

```
docker pull ghcr.io/inti-cmnb/kicad8_auto_full:dev
```

**Comment by Unichord** [comment]
Ok, done, thank you. A few comments and questions:

- I tried with only BOM at the moment, it generates different files but the content is identical. It seems that the `config` field is ignored.
- The naming scheme is not suitable for our needs. We have variants like this: ABC1, ABC1D, ABC1E, and the first variants' outputs are named ABC1default.csv for example (this can be easily bypassed by a script later, it's no problem). I tried to set `file_id` and `variant` as "" but it doesn't work, and when setting `name` as "" or '' it says a valid name should exist.
- In my opinion, `name` should be a generic name for the board/variant, and `file_id` should be the actual information used for file naming and so on. Not a problem either way, though.
- Does the variant `type` influence the outputs? I used just `kibom` as type, but all kinds of outputs are generated (ibom, pdf, etc). This is exactly what I need, I'm asking just out of general curiosity.
- Kibot runs are significantly slower now, probably due to the dev branch usage. Just letting you know.

Thank you for support as usual.

**Comment by set-soft** [comment]
> Ok, done, thank you. A few comments and questions:
> 
> * I tried with only BOM at the moment, it generates different files but the content is identical. It seems that the `config` field is ignored.

Can you create a small example with your test case.
What I tried is: [737.zip](https://github.com/user-attachments/files/17978823/737.zip)
As you can see the configuration is:

```yaml
kibot:
  version: 1


variants:
  - name: 't1_v1'
    comment: 'Test 1 Variant V1'
    type: kibom
    file_id: '_(V1)'
    variant: V1

  - name: 't1_v2'
    comment: 'Test 1 Variant V2'
    type: kibom
    file_id: '_(V2)'
    variant: V2

  - name: 't1_v3'
    comment: 'Test 1 Variant V3'
    type: kibom
    file_id: '_V3'
    variant: V3

  - name: 'bla bla'
    comment: 'Test 1 Variant V1+V3'
    type: kibom
    file_id: '_bla_bla'
    variant: ['V1', 'V3']


preflight:
  drc: true


outputs:
  - name: 'bom_internal'
    comment: "Bill of Materials in CSV format"
    type: bom
    dir: BoM

  - name: 'report'
    comment: "Report"
    type: report
```

I invoke KiBot like this:

```
kibot --variant NONE --variant ALL -d Gen
```

This is all variants plus the case with no variants.
And you get different reports and different BoMs. In fact this is equivalent to:

```yaml
kibot:
  version: 1


variants:
  - name: 't1_v1'
    comment: 'Test 1 Variant V1'
    type: kibom
    file_id: '_(V1)'
    variant: V1

  - name: 't1_v2'
    comment: 'Test 1 Variant V2'
    type: kibom
    file_id: '_(V2)'
    variant: V2

  - name: 't1_v3'
    comment: 'Test 1 Variant V3'
    type: kibom
    file_id: '_V3'
    variant: V3

  - name: 'bla bla'
    comment: 'Test 1 Variant V1+V3'
    type: kibom
    file_id: '_bla_bla'
    variant: ['V1', 'V3']

outputs:
  - name: 'bom_internal'
    comment: "Bill of Materials in CSV format"
    type: bom
    dir: BoM

  - name: 'bom_internal_v1'
    comment: "Bill of Materials in CSV format for variant t1_v1"
    type: bom
    dir: BoM
    options:
      variant: t1_v1

  - name: 'bom_internal_v2'
    comment: "Bill of Materials in CSV format for variant t1_v2"
    type: bom
    dir: BoM
    options:
      variant: t1_v2

  - name: 'bom_internal_v3'
    comment: "Bill of Materials in CSV format for variant t1_v3"
    type: bom
    dir: BoM
    options:
      variant: t1_v3

  - name: 'bom_internal_bla_bla'
    comment: "Bill of Materials in CSV format for variant `bla bla`"
    type: bom
    dir: BoM
    options:
      variant: 'bla bla'

  - name: 'report'
    comment: "Report"
    type: report

  - name: 'report_v1'
    comment: "Report for variant t1_v1"
    type: report
    options:
      variant: t1_v1

  - name: 'report_v2'
    comment: "Report for variant t1_v2"
    type: report
    options:
      variant: t1_v2
```

> * The naming scheme is not suitable for our needs.

Which name scheme? It should be the same.

> We have variants like this: ABC1, ABC1D, ABC1E, and the first variants' outputs are named ABC1default.csv for example (this can be easily bypassed by a script later, it's no problem). I tried to set `file_id` and `variant` as "" but it doesn't work, and when setting `name` as "" or '' it says a valid name should exist.

I suspect there are some issue with the global output pattern. What are you using?

> * In my opinion, `name` should be a generic name for the board/variant, and `file_id` should be the actual information used for file naming and so on. Not a problem either way, though.

Can you elaborate?

> * Does the variant `type` influence the outputs? I used just `kibom` as type, but all kinds of outputs are generated (ibom, pdf, etc). This is exactly what I need, I'm asking just out of general curiosity.

We have 3 variant mechanisms, they can be applied to most outputs. You can use `kibom` or `kicost` or `ibom` variants for any output that supports variants. But each variant works in a different way. Please read the docs.

> * Kibot runs are significantly slower now, probably due to the dev branch usage. Just letting you know.

Is that for any operation or for some operation in particular?

**Comment by Unichord** [comment]
> Can you create a small example with your test case. What I tried is: [737.zip](https://github.com/user-attachments/files/17978823/737.zip) As you can see the configuration is:

The configuration I use is basically the same as bug #735, I just changed the way I invoke Kibot:
`kibot -c ${script_dir}/bom.kibot.yaml -e "${proj_dir}/${project}.kicad_sch" -b "${proj_dir}/${project}.kicad_pcb" --variant ALL`

> I invoke KiBot like this:
> 
> ```
> kibot --variant NONE --variant ALL -d Gen
> ```
> 
> This is all variants plus the case with no variants. And you get different reports and different BoMs. In fact this is equivalent to:

Maybe we think differently the concept of variants, I will try to explain more clearly how I think it should work, please let me know if I'm wrong somewhere:
- A variant is a variation within the same scheme/board, i.e. multiple components which are not mounted, a different value for the same Ref, something like this.
- So, ABC1 (which is the project, and we associate it to the gerber files) could be ABC1 (which has R1=10K and C1 mounted) or ABC1D (which has R1=22K and C1 mounted) or ABC1E (which has R1=100K and C1=DNP)
- The gerber files are the same for all variants, while the BOM, the mount files (interactive html BOM for example), and the 3D image are different
Given this, I don't understand what you mean with "all variants plus the case with no variants". _no variants_ should be already included in the _all variants_ case, as it is a variant itself. Am I wrong here thinking this?

> Which name scheme? It should be the same.
The one I mentioned earlier, so ABC1, ABC1D, ABC1E...

> I suspect there are some issue with the global output pattern. What are you using?
Please refer to bug #735, the project I'm using is the same.

> > * In my opinion, `name` should be a generic name for the board/variant, and `file_id` should be the actual information used for file naming and so on. Not a problem either way, though.
> 
> Can you elaborate?
This is the variants file:
```
variants:
- name: 'default'
  file_id: 'T'
  variant: 'T'
  type: kibom
- name: Q
  type: kibom
  file_id: Q
  variant: Q
```
And this is the output folder:
![image](https://github.com/user-attachments/assets/2bb05fa3-33c2-4969-a571-4453eeeffdcd)
The same applies if I set `file_id: ''` and `variant: ''`, the suffix _default_ stays.

> > * Kibot runs are significantly slower now, probably due to the dev branch usage. Just letting you know.
> 
> Is that for any operation or for some operation in particular?
Using the _latest_ branch for BOM generation requires about 7 seconds, while _dev_ branch requires about 13 seconds. No variants are involved of course.

**Comment by set-soft** [comment]
> > Can you create a small example with your test case. What I tried is: [737.zip](https://github.com/user-attachments/files/17978823/737.zip) As you can see the configuration is:
> 
> The configuration I use is basically the same as bug #735, I just changed the way I invoke Kibot: `kibot -c ${script_dir}/bom.kibot.yaml -e "${proj_dir}/${project}.kicad_sch" -b "${proj_dir}/${project}.kicad_pcb" --variant ALL`

I understand you want to use templates that can be applied to any project, and this is the way to go.
But in order to find problems you must remove all the extra complexity, which could introduce side effects and complicates the tests.

If you don't remove it I must do it, which is time consuming and will discourage me.

I took the example from #735 and adapted *bom.kibot.yaml* to be used standalone (no extra complexity), I reduced it to:

```yaml
kibot:
  version: 1


variants:
- name: default
  comment: GFP1
  type: kibom
- name: A
  comment: GFP1A
  type: kibom
  file_id: A
  variant: A

outputs:
- name: netlist
  comment: Generating netlist for iBOM
  type: netlist
  dir: BoM

# CSV default BOM
- name: generic_bom_csv
  comment: Generic Bill of Materials in CSV format
  type: bom
  dir: BoM
  options:
    # use_alt: true
    output: '%f%v.%x'
    columns:
      - Row
      - Part
      - References
      - Value
      - Footprint
      - Quantity Per PCB
      - Status
      - Datasheet
    format: CSV

# Interactive HTML BOM
- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: BoM
  options:
    output: '%f%v.%x'
    layer_view: 'F'
    checkboxes: 'Placed'
    show_fields: 'Value,Footprint'
    extra_data_file: BoM/%p-netlist.net
    extra_fields: 'Config'
    dnp_field: 'Config'
```

Note that your example also uses a missing *kicad_wks* file.


> > I invoke KiBot like this:
> > ```
> > kibot --variant NONE --variant ALL -d Gen
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is all variants plus the case with no variants. And you get different reports and different BoMs. In fact this is equivalent to:
> 
> Maybe we think differently the concept of variants, I will try to explain more clearly how I think it should work, please let me know if I'm wrong somewhere:
> 
> * A variant is a variation within the same scheme/board, i.e. multiple components which are not mounted, a different value for the same Ref, something like this.
> * So, ABC1 (which is the project, and we associate it to the gerber files) could be ABC1 (which has R1=10K and C1 mounted) or ABC1D (which has R1=22K and C1 mounted) or ABC1E (which has R1=100K and C1=DNP)
> * The gerber files are the same for all variants, while the BOM, the mount files (interactive html BOM for example), and the 3D image are different
>   Given this, I don't understand what you mean with "all variants plus the case with no variants". _no variants_ should be already included in the _all variants_ case, as it is a variant itself. Am I wrong here thinking this?

Not wrong just omitting the fact that variants are completely optional. You can generate all the outputs without applying any variant. In most cases this is what you call *default* variant. If you don't use this then `--variant ALL` is enough. My example is more generic, that's all.

> 
> > Which name scheme? It should be the same.
> 
> The one I mentioned earlier, so ABC1, ABC1D, ABC1E...

Ok, using the above mentioned config in the *GFP1* dir of your project I executed:

```
kibot -c bom.kibot.yaml --variant ALL -d BoM_Variant
```

Note that I don't need to specify *-b* or *-e*, this folder contains just one project.

I got:

```
$ ls -1 BoM_Variant/BoM/
GFP1A.csv
GFP1A.html
GFP1.csv
GFP1.html
GFP1-netlistA.net
GFP1-netlist.net
```

Which corresponds to your scheme GFP1 and GFP1A


> > I suspect there are some issue with the global output pattern. What are you using?
> 
> Please refer to bug #735, the project I'm using is the same.

As you can see I used #735 files. Just removed extra stuff that is confusing and incomplete.
 
> > > * In my opinion, `name` should be a generic name for the board/variant, and `file_id` should be the actual information used for file naming and so on. Not a problem either way, though.
> > 
> > 
> > Can you elaborate?
> > This is the variants file:
> 
> ```
> variants:
> - name: 'default'
>   file_id: 'T'
>   variant: 'T'
>   type: kibom
> - name: Q
>   type: kibom
>   file_id: Q
>   variant: Q
> ```
> 
> And this is the output folder: ![image](https://private-user-images.githubusercontent.com/73905953/391939525-2bb05fa3-33c2-4969-a571-4453eeeffdcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzQ2MjksIm5iZiI6MTczMzIzNDMyOSwicGF0aCI6Ii83MzkwNTk1My8zOTE5Mzk1MjUtMmJiMDVmYTMtMzNjMi00OTY5LWE1NzEtNDQ1M2VlZWZmZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzNTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWE5ZmYwZjMwMzhjMWJhOWQzY2UxMmNjODYxZGFkN2FjYWVhM2I4ZjJmN2Q5NmZiYTVhZjk3MjU0NjVkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wg5q-j2uPna30aHu_CsWqljjVZlVRQ4oLPpph2frwKY) The same applies if I set `file_id: ''` and `variant: ''`, the suffix _default_ stays.
> 

As you can see I don't get this. I replaced the variants using the above mentioned variants, and got, as spected:

```
$ ls -1 BoM_Variant2/BoM/
GFP1-netlistQ.net
GFP1-netlistT.net
GFP1Q.csv
GFP1Q.html
GFP1T.csv
GFP1T.html
```
So I can just guess your *KCT1default.csv* file comes from some mistake in the config, like using %V instead of %v

And this is why I insist on creating simple examples that reproduce the problem, not just saying "use this, but changing that and mixng with this"

> > > * Kibot runs are significantly slower now, probably due to the dev branch usage. Just letting you know.
> > 
> > 
> > Is that for any operation or for some operation in particular?
> 
> Using the _latest_ branch for BOM generation requires about 7 seconds, while _dev_ branch requires about 13 seconds. No variants are involved of course.

How do you measure it, is this part of the docker initialization?

On my system I generate netlist, bom and ibom for both variants in 4 s:

```
$ time ~/kibot/src/kibot -c bom2.kibot.yaml --variant ALL -d BoM_Variant3
Using SCH file: GFP1.kicad_sch
Variant `default`:
- 'Generating netlist for iBOM' (netlist) [netlist]
- 'Generic Bill of Materials in CSV format' (generic_bom_csv) [bom]
WARNING:(W009) KiCad config without environment.vars section (kibot - config.py:370)
WARNING:(W020) Malformed value: `ECH-U1C223GX5` (no match in C9) (kibot - units.py:239)
WARNING:(W020) Malformed value: `Coil` (no match in L3) (kibot - units.py:239)
- 'Interactive HTML BoM' (basic_ibom) [ibom]
Variant `Q`:
- 'Generating netlist for iBOM' (netlist) [netlist]
- 'Generic Bill of Materials in CSV format' (generic_bom_csv) [bom]
- 'Interactive HTML BoM' (basic_ibom) [ibom]

real	0m4,186s
user	0m3,692s
sys	0m0,675s
```

Using the stable release it takes more time because I must run KiBot twice:

```
$ time kibot -c bom2.kibot.yaml -g variant='default' -d BoM_Variant4; time kibot -c bom2.kibot.yaml -g variant='Q' -d BoM_Variant4
Using SCH file: GFP1.kicad_sch
Using command line value `default` for global option `variant`
- 'Generating netlist for iBOM' (netlist) [netlist]
- 'Generic Bill of Materials in CSV format' (generic_bom_csv) [bom]
WARNING:(W009) KiCad config without environment.vars section (kibot - config.py:359)
WARNING:(W020) Malformed value: `ECH-U1C223GX5` (no match in C9) (kibot - units.py:239)
WARNING:(W020) Malformed value: `Coil` (no match in L3) (kibot - units.py:239)
- 'Interactive HTML BoM' (basic_ibom) [ibom]
Found 3 unique warning/s (3 total)

real	0m3,018s
user	0m2,673s
sys	0m0,439s
Using SCH file: GFP1.kicad_sch
Using command line value `Q` for global option `variant`
- 'Generating netlist for iBOM' (netlist) [netlist]
- 'Generic Bill of Materials in CSV format' (generic_bom_csv) [bom]
WARNING:(W009) KiCad config without environment.vars section (kibot - config.py:359)
WARNING:(W020) Malformed value: `ECH-U1C223GX5` (no match in C9) (kibot - units.py:239)
WARNING:(W020) Malformed value: `Coil` (no match in L3) (kibot - units.py:239)
- 'Interactive HTML BoM' (basic_ibom) [ibom]
Found 3 unique warning/s (3 total)

real	0m3,001s
user	0m2,725s
sys	0m0,391s
```

So perhaps has something to do with docker and/or the OS
