### ISSUE TITLE
[FEATURE] right_digits option in BoM columns

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#739]
**Is your feature request related to a problem? Please describe.**
When using the BoM output with a filter for testpoint information generation (with Reference, Net Label, X and Y columns), it would be nice to be able to set the number of right digits of the X and Y columns

**Describe the solution you'd like**
Being able to specify the number of right digits in the column options  would be ideal:
```
    columns:
      - field: References
        name: Ref.
      - field: Net Label
        name: Net 
      - field: Footprint X
        name: X
        right_digits: 2
      - field: Footprint Y
        name: Y
        right_digits: 2
```

**Describe alternatives you've considered**
Using the position output (with `include_virtual = true` and an `exclude_filter` (which is btw not documented)). This works, but in this case some of the values are in quotations and the `Net Label` column is not accessible.
