### ISSUE TITLE
[HOW] Fix oversized [BUG] image logo in XLSX BoM

### ISSUE THREAD

**Issue by Kampi** [INTI-CMNB/KiBot#750]
**What do you want to achieve?**

My BOM (generated by type `bom`) contains an oversized image. How can I remove / fix it?

![image](https://github.com/user-attachments/assets/6f70ef52-fff4-4ef0-a8dd-96aa9d83920a)

**Do you have some configuration file (.kibot.yaml) that you are using?**

```yaml
  - name: "BOM for PCBWay"
    comment: "BOM for PCBWay"
    type: bom
    dir: docs
    category: "purchasing"
    options:
      format: XLSX
      count_smd_tht: true
      output: "BOM_PCBWay.%x"
      ref_separator: ','
      columns:
        - field: Row
          name: Item
        - field: References
          name: Ref Des
        - field: Build Quantity
          name: Quantity
        - field: Mfr.
          name: Manufacturer
        - field: Mfr. No.
          name: Mfg Part#
        - field: Value
          name: Description / Value
        - field: Footprint
          name: Package
        - field: Footprint Type
          name: Type
        - field: Footprint Side
          name: Side
      xlsx:
        title: "%f BOM"
        hide_stats_info: false
        quote_all: true
```

**Environment (please complete the following information):**

- In a CI/CD workflow? (Ex: `GitHub`/`GitLab`)

**Additional context**
Add any other context about your setup/project.
