### ISSUE TITLE
[BUG] some strings are seen as booleans in YAML substitutions

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#762]
Fill as much as you can, remove the rest
When performing YAML substitutions, some strings as seen as booleans when performing subsitutions:
```
y|Y|yes|Yes|YES|n|N|no|No|NO|
on|On|ON|off|Off|OFF
```

are all seen as boolean. I guess this is normal behavior for YAML files (v1.1), but it's probably not desired in KiBot

**To Reproduce**
Example with global:

```
kibot:
  version: 1

global:
  edge_connector: '@EDGE_CONNECTOR@'

...
definitions:
  EDGE_CONNECTOR: no
```

```ERROR:In `global` section: Option `edge_connector` must be any of ['yes', 'no', 'bevelled'] not `False` (kibot.gs - gs.py:886)```

Now changing the location of the single quotes
```
kibot:
  version: 1

global:
  edge_connector: @EDGE_CONNECTOR@

...
definitions:
  EDGE_CONNECTOR: 'no'
```

```ERROR:In `global` section: Option `edge_connector` must be a string not `boolean` (kibot.gs - gs.py:886)```

**Expected behavior**
Variable substitutions should keep the string even for the following patterns
```
y|Y|yes|Yes|YES|n|N|no|No|NO|
on|On|ON|off|Off|OFF
```
YAML v1.2 normally doesn't interpret these patterns as booleans

**Environment (please complete the following information):**
Where are you running KiBot:
- WSL2, dev branch

**Comment by nguyen-v** [comment]
```
    import yaml
    from yaml.resolver import Resolver
    for ch in "OoYyNn":
        if len(Resolver.yaml_implicit_resolvers[ch]) == 1:
            del Resolver.yaml_implicit_resolvers[ch]
        else:
            Resolver.yaml_implicit_resolvers[ch] = [x for x in
                    Resolver.yaml_implicit_resolvers[ch] if x[0] != 'tag:yaml.org,2002:bool']
```
in `config_reader.py` seems to solve the issue, but maybe we should use `yamlcore` instead

**Comment by set-soft** [comment]
Hmmm ... something is wrong for sure, but I don't think:

```yaml
kibot:
  version: 1

global:
  edge_connector: '@EDGE_CONNECTOR@'

...
definitions:
  EDGE_CONNECTOR: no
```

Should work. You should always use strings in the definitions. I think what we really need is a warning here. I also think the solution here is to use:

```yaml
kibot:
  version: 1

global:
  edge_connector: '@EDGE_CONNECTOR@'

...
definitions:
  EDGE_CONNECTOR: 'no'
```

The quotes are optional in YAML, but they are there to disambiguate, which is the case here.
