### ISSUE TITLE
[BUG] Populate: some components are always shown, even if not explicitly mentionned

### ISSUE THREAD

**Issue by dhaillant** [INTI-CMNB/KiBot#772]
**Describe the bug**
When using Populate, some components are always shown, regardless of the instructions of the .md populate file.

This bug might be related to the attributes: I had a component marked with both 'Exclude from position files' and 'Exclude from bill of materials' attributes, yet it was constantly visible. By removing these attributes, I managed to make it disappear from the 3D view (and reappear later in the populate document, following explicit instructions in populate.md).

I've also been able to reproduce the bug and make other components appear regardless of the instructions in populate.md by checking the attributes mentioned above.

However, I have other components that do not follow this simple workaround, and so far, I haven't been able to remove them from the 3D views of the populate doc. So maybe there are other interactions happening.

**To Reproduce**
Open pcbnew, choose a component, open its footprint properties and check both attributes "Exclude from position files" and "Exclude from bill of materials". Save the pcb file.

Then start populate:
From Makefile:
`kibot -d $(DIR) -c $(KIBOT_CFG) -b $(PCB) -g variant=sub_pcb[main] populate`

From YAML:
```
  - name: populate
    comment: "Populate front PCB"
    type: populate
    dir: Populate/%f-%r%v-%D/top
    options:
      renderer: top_3d
      input: kibot/populate.md

  - name: top_3d
    comment: Top view render
    type: render_3d
    dir: PCB%v/png
    options:
      output: '%p-%r-%i%I%v-%D.%x'
      width: 1280
      height: 960
      orthographic: true
```

From populate.md:
```
# Assembly procedure
- [[front | ]] This is the front side of the board we are populating.
- [[back | ]] This is the back side of the board we are populating.
(...)
```

From the very first steps, even if no components are explicitly mentioned, the 3D models of components with both attributes checked are shown in the 3D views.

**Expected behavior**
The components that aren't explicitly listed in populate.md shouldn't be shown.

**Environment (please complete the following information):**
- KiBot 1.8.2 - Copyright 2018-2024, Salvador E. Tropea/INTI/John Beard - License: AGPL v3
- KiCad PCB Editor x86_64 on x86_64 Version: 8.0.8-8.0.8-0~ubuntu22.04.1, release build
