### ISSUE TITLE
[Feature] Detect extra fields

### ISSUE THREAD

**Issue by set-soft** [INTI-CMNB/KiBot#774]
### Discussed in https://github.com/INTI-CMNB/KiBot/discussions/773

<div type='discussions-op-text'>

<sup>Originally posted by **Strooom** February  4, 2025</sup>
I am using KiBot in a CI/CD github workflow, and it's really good so I am applying it to all my designs.
One thing is still missing however : I'd like some automated check and/or cleanup of the custom fields used in the project, its symbols and its footprints.

Often a needed symbol and/or footprint is not present in the standard KiCAD libraries but it is made available by its vendor or by sites such as SnapEDA, SamacSys, etc. These symbols and footprints however contain custom fields of metadata which are polluting the design and they may show up in BOM exports etc.

So in general I will clean an imported symbol / footprint before using it in a design, aligning all metadata field names to my standard and removing excess fields. But of course errors can and do occur, and so I'd like to automate this check with KiBOT

**output field_check**
The user provides a list of 'allowed' field names in the YAML file, and KiBOT writes a report file with all symbols and footprints that have fields outside this list., eg. `symbol 'CP2102N' has field 'height'`
User could also provide a list of 'mandatory' field names and KiBOT writes in the report for which symbols / footprints these fields are missing or empty, eg. `symbol 'CP2102N' has empty field 'Datasheet'`
Ideally, the lists of allowed and mandatory fields could be different for symbols, footprints, the schematic and the layout

**This will help a lot with the cleanup of your design's metadata.**
If this would be possible with the current features of KiBOT, I would be pleased to learn how to do that.</div>

**Comment by set-soft** [comment]
Hi @Strooom !

The above patch implements a mechanism to report extra fields, i.e.:

```yaml
kibot:
  version: 1

preflight:
  check_fields:
    - field: MFR
      regex: '.*'
      severity: warning
      severity_missing: continue
    - field: MPN
      regex: '.*'
      severity: warning
      severity_missing: continue
    - field: "LCSC#"
      regex: '.*'
      severity: warning
      severity_missing: continue
    - field: "*"
      severity_missing: warning
```

Can report things like:

```
WARNING:(W162) D5 extra fields: bogus (kibot - pre_check_fields.py:109)
```
