### ISSUE TITLE
[BUG] `sketch_pads_on_fab_layers` enabled for layers specified by name in `pcb_print` output

### ISSUE THREAD

**Issue by stefan894** [INTI-CMNB/KiBot#777]
**What do you want to achieve?**
I updated my kibot docker file from:

`ghcr.io/inti-cmnb/kicad8_auto:1.8.1`  to `ghcr.io/inti-cmnb/kicad_auto:dev_k8`

and I see the following changes when executing: 

``
kibot --log Generated/kibot.log -c V3/Assembly_DNP.kibot.yaml -b V3/Kicad/PCB.0003x.kicad_pcb
``

![Image](https://github.com/user-attachments/assets/b65c7dcd-cbbc-4332-a963-84fc64e8d544)

![Image](https://github.com/user-attachments/assets/26cdaf2a-e91a-4541-8f33-eef626bb23bd)

seems all holes / pins are now also printed, they were not printed with kibot 1.8.1

**Do you have some PCB/Schematic to use as example?**
sorry can not share design, I might try to make a minimal example

**Do you have some configuration file (.kibot.yaml) that you are using?**

.kibot.ymal file:

```
kibot:
    version: 1
    
outputs:     
  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: Generated
    options:
      force_edge_cuts: true
      keep_temporal_files: false
      dnf_filter: _kibom_dnf_Config
      scaling: 1.0
      pages:
        - layers: [ F.Silkscreen, F.Fab ]
          sheet: 'Assembly Top'
        - layers: [ B.Silkscreen, B.Fab ]
          sheet: 'Assembly Bottom'
          mirror: true          
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? `GitLab`
- Using a docker image? `ghcr.io/inti-cmnb/kicad8_auto:1.8.1` and  `ghcr.io/inti-cmnb/kicad_auto:dev_k8``Dockerfile`
