### ISSUE TITLE
[HOW] add selection of color for crosses of DNP in pcb assembly plan

### ISSUE THREAD

**Issue by stefan894** [INTI-CMNB/KiBot#780]
**What do you want to achieve?**
I would like to add selection of color for crosses of DNP in pcb assembly plan: use https://github.com/INTI-CMNB/KiBot/issues/622 feature which seems to be implemented with https://github.com/INTI-CMNB/KiBot/pull/700

actually I am not sure about the syntax, sadly https://github.com/INTI-CMNB/KiBot/pull/700 didn't provided an example how to use it.
I tried to implement it based on some inspiration from https://github.com/INTI-CMNB/KiBot/issues/533 where someone else tries to set layer colors as well.

currently I get the following errors: https://gitlab.com/stefan_bozz/kibot_silkscreen_problem/-/jobs/9141228886

```
$ kibot -c test.kibot.yaml
Using SCH file: t1.kicad_sch
WARNING:(W015) Unknown option `dnp_cross_top_layer` (kibot - optionable.py:224)
WARNING:(W015) Unknown option `dnp_cross_bottom_layer` (kibot - optionable.py:[22](https://gitlab.com/stefan_bozz/kibot_silkscreen_problem/-/jobs/9141228886#L22)4)
ERROR:In section 'print_pdf' (pcb_print): Missing or empty `layer` attribute for layer entry ({'color': '#ff0000'}) (kibot.gs - gs.py:894)
```

**Do you have some PCB/Schematic to use as example?**
https://gitlab.com/stefan_bozz/kibot_silkscreen_problem

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml
kibot:
    version: 1
    
outputs:     
  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: Generated
    options:
      force_edge_cuts: true
      keep_temporal_files: false
      dnf_filter: _kibom_dnf_Config
      scaling: 2.0
      dnp_cross_top_layer: User.2
      dnp_cross_bottom_layer: User.3
      pages:
        - layers:
            - layer: 'F.Silkscreen'
            - layer: 'F.Fab'
            - color: '#ff0000'
            - layer: 'User.2'
          sheet: 'Assembly Top'
        - layers:
            - layer: 'B.Silkscreen'
            - layer: 'B.Fab'
            - color: '#ff0000'
            - layer: 'User.3'
          sheet: 'Assembly Bottom'
          mirror: true          
```

**Environment (please complete the following information):**
Where are you running KiBot:
- In a CI/CD workflow? `GitLab`
- Using a docker image? ghcr.io/inti-cmnb/kicad_auto_full:dev_k8

**Comment by set-soft** [comment]
Hi @stefan894 !

They are global variables. And the `color` option must be applied to a `layer`, here is an example:

```yaml
kibot:
    version: 1

globals:
  dnp_cross_top_layer: 'User.2'
  dnp_cross_bottom_layer: 'User.3'

outputs:     
  - name: print_pdf
    comment: "PDF for the PCB"
    type: pcb_print
    dir: Generated
    options:
      force_edge_cuts: true
      keep_temporal_files: false
      dnf_filter: _kibom_dnf_Config
      scaling: 2.0
      pages:
        - layers:
            - layer: 'F.Silkscreen'
            - layer: 'F.Fab'
            - layer: 'User.2'
              color: '#ff0000'
          sheet: 'Assembly Top'
        - layers:
            - layer: 'B.Silkscreen'
            - layer: 'B.Fab'
            - layer: 'User.3'
              color: '#ff0000'
          sheet: 'Assembly Bottom'
          mirror: true
```

Applied to the arduprog example you get things like:

![Image](https://github.com/user-attachments/assets/41592cbc-b524-481c-82cc-f53b008a54fd)
