### ISSUE TITLE
[BUG] KiCAD DNF flag ignored when generating gerber files from panel.

### ISSUE THREAD

**Issue by Thorfinn-Thorsson** [INTI-CMNB/KiBot#784]
**Describe the bug**
KiCAD DNF flag ignored when generating gerber files from panel.

**To Reproduce**
Generate a basic panel:

```
kibot:
  version: 1

outputs:
  - name: 'pcb_panelization'
    comment: 'Generate Panelization files'
    type: 'panelize'
    dir: 'PCB_%f-%r-%i'
    options:
      output: '%f-%i.%x'
      title: '+ (Panel)'
      units: 'mm'
      create_preview: false
      configs:
        - layout:
            space: 1
            hbackbone: 3
            vbackbone: 3
            rows: 2
            cols: 2
            vbonecut: False
            hbonecut: False
          source:
            tolerance: 15
          framing:
            type: frame
            width: 9
            space: 1
            cuts: none
          tooling:
            type: 4hole
            hoffset: 2.5
            voffset: 2.5
          cuts:
            type: vcuts
            offset: 0
            clearance: 0.5
            cutcurves: False
            layer: User.1
          text:
            type: simple
            voffset: 2.5
            text: '{boardComment3}-{boardRevision}'
          page:
            posy: 25
          post:
            millradius: 0.5
            origin: bl
            dimensions: True
          copperfill:
            type: hatched
            clearance: 0.5
            width: 0.5
            spacing: 2
```

Generate gerber files using the panel file.

```
kibot:
  version: 1

outputs:
  - name: 'gerber_default'
    comment: 'Generate Gerbers (Default)'
    type: 'gerber'
    dir: 'FAB_%f-%r-%v/Default/Gerbers'
    layers:
      - copper
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - F.Paste
      - B.Paste
      - Edge.Cuts
    options:
      disable_aperture_macros: true
      exclude_pads_from_silkscreen: true
      output: '%f-%r-%v-%i.%x'
      plot_footprint_values: false
      subtract_mask_from_silk: true
      use_aux_axis_as_origin: true
      use_gerber_net_attributes: false
      use_gerber_x2_attributes: false

  - name: '2d_top_svg'
    comment: 'Export 2D model - Top (SVG).'
    type: 'pcbdraw'
    dir: 'FAB_%f-%r-%v/Default/Render2D'
    options:
      output: '%f-%r-%v-%i.%x'
```

**Expected behavior**
I expect to see all DNF's not loaded on the PCB.

**Environment (please complete the following information):**
Using Docker image: `FROM ghcr.io/inti-cmnb/kicad8_auto:1.8.2-2_k8.0.8_d12.7`
