### ISSUE TITLE
[HOW] Blender output renders twice when changing output name

### ISSUE THREAD

**Issue by Strooom** [INTI-CMNB/KiBot#792]
I am using kiBot to render an image of the PCB, to show it in the repository's readme.md
To keep names of these image files the same over all projects, I want it to generate 'front.png'.
Still, the default filename is also generated, resulting in a double render time...

This is the yaml for the render output
```
outputs:
  - name: 'render front'
    type: blender_export
    dir: 'pcb'
    options:
      light:
        - name : 'light_1'
          energy: 0
          pos_x: '-size*3.33'
          pos_y: 'size*3.33'
          pos_z: 'size*5'
        - name : 'light_2'
          energy: 0
          pos_x: 'size*10'
          pos_y: 'size*10'
          pos_z: 'size*50'
      render_options:
        transparent_background: true
        samples: 20
        resolution_x: 1000
        resolution_y: 1600
      point_of_view:
        - rotate_z: -90
          rotate_x: 0
          rotate_y: 0
      fixed_auto_camera: false
      auto_camera_z_axis_factor: 0.75
      outputs:
        - type: render
        - output: 'front.png'
```

This is the resulting command line : 
```DEBUG:- Executing: /usr/bin/blender -b --factory-startup -P /usr/local/lib/python3.11/dist-packages/kibot/blender_scripts/blender_export.py -- --format render render --output /github/workspace/outputs/pcb/LoRa-V3-PCB-3D_blender_top.png /github/workspace/outputs/pcb/front.png --scene /tmp/tmpbl6pu0hj.json /github/workspace/outputs/pcb/LoRa-V3-PCB-blender_export.pcb3d (kibot - kiplot.py:159)```

LoRa-V3-PCB-3D is the PCB name, so LoRa-V3-PCB-3D_blender_top.png is (I guess) the default render name.
How can I improve the yaml to only have 1 render, 'front.png'

**Comment by set-soft** [comment]
Hi @Strooom !
Your config is explicitly asking for two outputs, is just a confusion between YAML lists and dicts, here:

```yaml
      outputs:
        - type: render
        - output: 'front.png'
```    

You are saying that you want two outputs, the first with attribute `type: render` and the second with attribute `output: front.png`. The correct syntax is:

```yaml
      outputs:
        - type: render
          output: 'front.png'
```    

So here the list has one element with two attributes.
