### ISSUE TITLE
[HOW] Select manf field instead of value in position export

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#794]
**What do you want to achieve?**

I would like to use custom fields for pick and place export.
Is this possible or a limitation of KiCad?
Or is there a preflight/filter I can use to change field content/copy field content to value?

**Do you have some configuration file (.kibot.yaml) that you are using?**

Yes.

This does not work!

```yaml
- name: 'position'
    comment: "Pick and place file"
    type: position
    dir: .    
    options:
      include_virtual: true
      format: ASCII   # CSV or ASCII format
      units: millimeters  # millimeters or inches
      separate_files_for_front_and_back: true
      bottom_negative_x: true
      columns:
        - Ref
        - Manf
        - Package
        - PosX
        - PosY
        - Rot
        - Side
```
