### ISSUE TITLE
[HOW] PaP export of symbols that use multiple units

### ISSUE THREAD

**Issue by Tho-Wa-Bo** [INTI-CMNB/KiBot#803]
We used the following suggestion from the issues #794 

**What do you want to achieve?**
We want to create an export with position data like in [your example](https://inti-cmnb.github.io/kibot_variants_arduprog_site/Browse/t1-navigate_Schematic_BoM.html#positional_bom_xlsx).
For the position data, symbols that consist of multiple units (D1A, D1B) should be exported correctly (Top and Bottom).

Do we need to configure the yaml file differently?

**Do you have some PCB/Schematic to use as example?**

[ecu-tw.zip](https://github.com/user-attachments/files/19649054/ecu-tw.zip)

The resulting position data is contained in the zip file.

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```# MacroFab compatible XYRS
# https://help.macrofab.com/knowledge/macrofab-required-design-files
kibot:
  version: 1

import:
  - file: KiBot-Filters.yaml  

preflight:
  run_erc: true
  update_xml: true
  run_drc: true
  check_zone_fills: true
  fill_zones: true
  ignore_unconnected: false
  draw_stackup: true
  update_stackup: true
  update_pcb_characteristics: true
  pcb_replace:
    date_command: date -d @`git log -1 --format='%at' -- $KIBOT_PCB_NAME` +%Y-%m-%d
  sch_replace:
    date_command: date -d @`git log -1 --format='%at' -- $KIBOT_PCB_NAME` +%Y-%m-%d

variants:
  - name: 'ECU-Place_Holder_ECU_ID_Variant'
    comment: 'Place_Holder_ECU_ID_Comment'
    type: kibom
    file_id: _ECU-Place_Holder_ECU_ID_Variant
    variant: ECU-Place_Holder_ECU_ID_Variant
    pre_transform: '_var_rename'
    exclude_filter: _none

outputs:
  - name: 'position_top'
    comment: "Pick and place file Top Layer, XYRS style"
    type: bom
    dir: PaP
    options:
      pre_transform: ['_kicost_rename', '_rot_footprint']
      dnf_filter: _only_smd
      output: '%f-top_pos%I%v.pos'
      units: millimeters
      group_fields: []
      sort_style: ref
      use_aux_axis_as_origin: true
      ignore_dnf: false
      footprint_populate_values: '0,1'
      footprint_type_values: '1,2,0'
      csv:
        separator: '	'
        hide_pcb_info: false
        hide_stats_info: false
        hide_header: false
      columns:
        - field: References
          name: Designator
        - field: Intranet_ID  
          name: ID
        - field: Footprint X
          name: PosX
        - field: Footprint Y
          name: PosY
        - field: Footprint Rot
          name: Rot
        - field: Footprint Side
          name: Side
        - field: Value
        - field: Footprint  
      exclude_filter: just_top

  - name: 'position_bottom'
    comment: "Pick and place file Bottom Layer, XYRS style"
    type: bom
    dir: PaP
    options:
      pre_transform: ['_kicost_rename', '_rot_footprint']
      dnf_filter: _only_smd
      output: '%f-bottom_pos%I%v.pos'
      units: millimeters
      group_fields: []
      sort_style: ref
      use_aux_axis_as_origin: true
      bottom_negative_x: true
      ignore_dnf: false
      footprint_populate_values: '0,1'
      footprint_type_values: '1,2,0'
      csv:
        separator: '	'
        hide_pcb_info: false
        hide_stats_info: false
        hide_header: false
      columns:
        - field: References
          name: Designator
        - field: Intranet_ID  
          name: ID
        - field: Footprint X
          name: PosX
        - field: Footprint Y
          name: PosY
        - field: Footprint Rot
          name: Rot
        - field: Footprint Side
          name: Side
        - field: Value
        - field: Footprint  
      exclude_filter: just_bottom


  - name: compress
    comment: "Compressed file containing output files"
    type: compress
    dir: PaP
    options:
      files:
      - from_output: 'position_top'
      - from_output: 'position_bottom'
```

**Environment (please complete the following information):**
Where are you running KiBot:
- GitLab CI
- kicad8_auto_full:1.8.2

**Comment by set-soft** [comment]
Try with the `latest` version (1.8.4).

Version 1.8.3 fixed some issues related to components with multiple units, see #741 (https://github.com/INTI-CMNB/KiBot/issues/741#issuecomment-2553295817)

Let me know if you get the correct result, I tried this:

```yaml
# https://help.macrofab.com/knowledge/macrofab-required-design-files
kibot:
  version: 1

filters:
  - name: just_top
    type: generic
    exclude_bottom: true

  - name: just_bottom
    type: generic
    exclude_top: true


variants:
  - name: 'ECU-Place_Holder_ECU_ID_Variant'
    comment: 'Place_Holder_ECU_ID_Comment'
    type: kibom
    file_id: _ECU-Place_Holder_ECU_ID_Variant
    variant: ECU-Place_Holder_ECU_ID_Variant
    pre_transform: '_var_rename'
    exclude_filter: _none

outputs:
  - name: 'position_top'
    comment: "Pick and place file Top Layer, XYRS style"
    type: bom
    dir: PaP
    options:
      pre_transform: ['_kicost_rename', '_rot_footprint']
      dnf_filter: _only_smd
      output: '%f-top_pos%I%v.pos'
      units: millimeters
      group_fields: []
      sort_style: ref
      use_aux_axis_as_origin: true
      ignore_dnf: false
      footprint_populate_values: '0,1'
      footprint_type_values: '1,2,0'
      csv:
        separator: '	'
        hide_pcb_info: false
        hide_stats_info: false
        hide_header: false
      columns:
        - field: References
          name: Designator
        - field: Intranet_ID  
          name: ID
        - field: Footprint X
          name: PosX
        - field: Footprint Y
          name: PosY
        - field: Footprint Rot
          name: Rot
        - field: Footprint Side
          name: Side
        - field: Value
        - field: Footprint  
      exclude_filter: just_top

  - name: 'position_bottom'
    comment: "Pick and place file Bottom Layer, XYRS style"
    type: bom
    dir: PaP
    options:
      pre_transform: ['_kicost_rename', '_rot_footprint']
      dnf_filter: _only_smd
      output: '%f-bottom_pos%I%v.pos'
      units: millimeters
      group_fields: []
      sort_style: ref
      use_aux_axis_as_origin: true
      bottom_negative_x: true
      ignore_dnf: false
      footprint_populate_values: '0,1'
      footprint_type_values: '1,2,0'
      csv:
        separator: '	'
        hide_pcb_info: false
        hide_stats_info: false
        hide_header: false
      columns:
        - field: References
          name: Designator
        - field: Intranet_ID  
          name: ID
        - field: Footprint X
          name: PosX
        - field: Footprint Y
          name: PosY
        - field: Footprint Rot
          name: Rot
        - field: Footprint Side
          name: Side
        - field: Value
        - field: Footprint  
      exclude_filter: just_bottom


  - name: compress
    comment: "Compressed file containing output files"
    type: compress
    dir: PaP
    options:
      files:
      - from_output: 'position_top'
      - from_output: 'position_bottom'
```

And got:

Top
```
Designator	ID	PosX	PosY	Rot	Side	Value	Footprint
D1	2398	21.7250	17.0000	180.0000	top	LED ge 1206	LED_1206_3216Metric
D2	1290	23.0000	10.5000	180.0000	top	G4-361 LED 5mm 5V gn	LED_D3.0mm_FlatTop
D3	2398	21.7250	4.5000	180.0000	top	LED ge 1206	LED_1206_3216Metric
D5	2082	27.0000	10.5000	180.0000	top	BAV99DW	SOT-363_SC-70-6
R1	5058	14.0000	17.0000	180.0000	top	1k 5% 500mW	R_Axial_DIN0204_L3.6mm_D1.6mm_P7.62mm_Horizontal
R2	5058	14.0000	10.5000	180.0000	top	1k 5% 500mW	R_Axial_DIN0204_L3.6mm_D1.6mm_P7.62mm_Horizontal
R3	5058	14.0000	4.5000	180.0000	top	1k 5% 500mW	R_Axial_DIN0204_L3.6mm_D1.6mm_P7.62mm_Horizontal
```

Bottom
```
Designator	ID	PosX	PosY	Rot	Side	Value	Footprint
D4	2082	-3.0000	10.5000	90.0000	bottom	BAV99DW	SOT-363_SC-70-6
```
