### ISSUE TITLE
[BUG] Color rings of THT 10 Meg resistors are displayed incorrectly after Blender rendering

### ISSUE THREAD

**Issue by 0x007E** [INTI-CMNB/KiBot#805]
**Problem description**
10 Meg THT-resistor color rings are not getting renderd correctly with blender in github-actions.

When rendering circuit boards with github-actions, the color rings of 10 Meg THT-resistors are displayed incorrectly. The image shows two 100 Megaohm resistors (R1/R2), but in the schematic and layout they have 10 Meg. I have tried it with 10M and 10Meg. Both do not work.

![Image](https://github.com/user-attachments/assets/f0a66fad-604e-4843-9db2-a9f3c6ad102b)

Project details can be found in the following [Github repository](https://github.com/0x007E/ebs).

I´m currently using `INTI-CMNB/KiBot@v2_dk7` to render the pcbs with following options:

``` yaml
  - name: 3D_top
    comment: "3D render from top (High Quality)"
    type: blender_export
    dir: './blender'
    options:
      render_options:
        transparent_background: true
        auto_crop: true
        samples: 20
      point_of_view:
        rotate_x: 0
        rotate_z: 0
      outputs:
        - output: 'top.%x'
        - type: render
```

> It may not really be a bug but some people may get confused if they see the renderd graphics does not match the layout plan.

Running KiBot on:
- github-actions
- ubuntu-latest
- `INTI-CMNB/KiBot@v2_dk7`
