### ISSUE TITLE
[BUG] pcb_print output misinterprets User.x layers

### ISSUE THREAD

**Issue by honzakutil** [INTI-CMNB/KiBot#808]
I have some text and tables in KiCad PCB editor in layers User.1, User.2, User.3 and User.4. I use KiBot and following piece of yaml configuration to print content of the User.x layers into the pdf file:

```
outputs:
  # PCB fabrication specification in PDF format
  - name: "pcb_specs"
    comment: "PCB fabrication specification"
    type: pcb_print
    dir: "outputs"
    options:
      output: "${board_name}${board_rev}_prints${pcb_prints}_fab-specs.%x"
      format: "PDF"
      force_edge_cuts: true
      forced_edge_cuts_color: "#777700"
      colored_pads: false
      colored_vias: false
      plot_sheet_reference: true
      scaling: 1
      pages:
        - title: "PCB fabrication specification"
          layers:
            - layer: "F.Cu"
              color: "#770000"
            - layer: "User.1"
              color: "#000000"
            - layer: "User.5"
              color: "#000000"
```

The example above will print, what is in User.1 and User.3, although it is told to print User.1 and User.5. After a while of experimenting, it seems that it follows pattern "(n-1)*2", as shown in table below:

| what I want to print | what I need to specify |
| ---                            | ---                                |
| User.1                      | User.1                           |
| User.2                      | User.3                           |
| User.3                      | User.5                           |
| User.4                      | User.7                           |

I used such configuration before with KiCad 8 and it worked, as expected. For example, following container worked correctly: `ghcr.io/inti-cmnb/kicad_auto_full:dev_k8_1.7.1-08f2b49_k8.0.2_d_sid_b3.5.1`.

To run the KiBot, I use Docker and WSL on the win11 machine.
Here is command that I use to start the docker: `docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY --env NO_AT_BRIDGE=1 --volume="./:/workdir:rw" ghcr.io/inti-cmnb/kicad9_auto:dev_1.8.4-1aaf885_k9.0.1_d_sid`

And here is info, that KiBot generates:
```
KiBot installation checker

Core:
Linux: 5.15.167.4 (Linux e247a51e0d42 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux)
  /usr/bin/uname
Python: 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0]
  /usr/lib/python3.11/os.py
  /usr/bin/python3
KiCad: 9.0.1
  /usr/lib/python3/dist-packages/pcbnew.py
  /usr/bin/kicad
Kibot: 1.8.4
  /usr/local/lib/python3.11/dist-packages/kibot/__main__.py
  /usr/local/bin/kibot

Modules:
Colorama: 0.4.6
  /usr/lib/python3/dist-packages/colorama/__init__.py
LXML: 4.9.2
  /usr/lib/python3/dist-packages/lxml/__init__.py
Lark: 1.1.5
  /usr/lib/python3/dist-packages/lark/__init__.py
PyYAML: 6.0.0 (6.0)
  /usr/lib/python3/dist-packages/yaml/__init__.py
QRCodeGen: Ok
  /usr/lib/python3/dist-packages/qrcodegen.py
Requests: 2.28.1
  /usr/lib/python3/dist-packages/requests/__init__.py
XLSXWriter: 3.0.2
  /usr/lib/python3/dist-packages/xlsxwriter/__init__.py
Xvfbwrapper: Ok
  /usr/lib/python3/dist-packages/xvfbwrapper.py
markdown2: 2.4.1
  /usr/lib/python3/dist-packages/markdown2.py
numpy: 1.24.2
  /usr/lib/python3/dist-packages/numpy/__init__.py

Tools:
Bash: 5.2.15 (GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu))
  /usr/bin/bash
Blender: Not available
  /usr/bin/bash
Ghostscript: 10.0.0 (10.00.0)
  /usr/bin/gs
Git: 2.39.5 (git version 2.39.5)
  /usr/bin/git
ImageMagick: 6.9.11.60 (Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org)
  /usr/bin/convert
Interactive HTML BoM: 2.10.0 (v2.10.0)
  /usr/bin/python3
KiBoM: 1.9.1 (KiBOM Version: 1.9.1)
  /usr/bin/KiBOM_CLI.py
KiCad Automation tools (kiauto): 2.3.6 (pcbnew_do 2.3.6 - Copyright 2018-2024, INTI/Productize SPRL - License: Apache)
  /usr/local/bin/pcbnew_do
KiCad PCB/SCH Diff (kidiff): 2.5.8 (kicad-diff.py 2.5.8 - Copyright 2020-2025, INTI/Salvador E. Tropea - License:)
  /usr/local/bin/kicad-diff.py
KiCost: 1.1.20 (KiCost v1.1.20)
  /usr/bin/kicost
KiKit: 1.7.2.1 (kikit, version 1.7.2-1)
  /usr/bin/kikit
OpenSCAD: 2021.1.0 (OpenSCAD version 2021.01)
  /usr/bin/openscad
Pandoc: Not available
  /usr/bin/openscad
RAR: 6.23.0 (RAR 6.23   Copyright (c) 1993-2023 Alexander Roshal   1 Aug 2023)
  /usr/bin/rar
RSVG tools: 2.54.7 (rsvg-convert version 2.54.7)
  /usr/bin/rsvg-convert
Xvfb: Ok (xvfb-run)
  /usr/bin/rsvg-convert

* Blender not installed or too old
  Install the `blender` package, i.e.: `sudo apt-get install blender`
  - Mandatory for `blender_export`

* Pandoc not installed or too old
  Install the `pandoc` package, i.e.: `sudo apt-get install pandoc`
  You should also install the following packages: texlive, texlive-latex-base, texlive-latex-recommended
  In CI/CD environments: the `kicad_auto_test` docker image contains it.
  - Optional to create PDF/ODF/DOCX files for `report`

Environment:
DISPLAY=:0
GIT_TERMINAL_PROMPT=0
HOME=/root
HOSTNAME=e247a51e0d42
INTERACTIVE_HTML_BOM_NO_DISPLAY=
KIBOT_ITERATION=2
KIBOT_REPO_HASH=1aaf885
KICAD6_3RD_PARTY=/root/.local/share/kicad/9.0/3rdparty
KICAD6_FOOTPRINT_DIR=/usr/share/kicad/footprints
KICAD6_SYMBOL_DIR=/usr/share/kicad/symbols
KICAD6_TEMPLATE_DIR=/usr/share/kicad/template
KICAD7_3RD_PARTY=/root/.local/share/kicad/9.0/3rdparty
KICAD7_FOOTPRINT_DIR=/usr/share/kicad/footprints
KICAD7_SYMBOL_DIR=/usr/share/kicad/symbols
KICAD7_TEMPLATE_DIR=/usr/share/kicad/template
KICAD8_3RD_PARTY=/root/.local/share/kicad/9.0/3rdparty
KICAD8_FOOTPRINT_DIR=/usr/share/kicad/footprints
KICAD8_SYMBOL_DIR=/usr/share/kicad/symbols
KICAD8_TEMPLATE_DIR=/usr/share/kicad/template
KICAD9_3RD_PARTY=/root/.local/share/kicad/9.0/3rdparty
KICAD9_FOOTPRINT_DIR=/usr/share/kicad/footprints
KICAD9_SYMBOL_DIR=/usr/share/kicad/symbols
KICAD9_TEMPLATE_DIR=/usr/share/kicad/template
KICAD_USER_TEMPLATE_DIR=/root/.local/share/kicad/9.0/template
KIPRJMOD=/workdir
KISYSMOD=/usr/share/kicad/footprints
LC_CTYPE=C.UTF-8
NO_AT_BRIDGE=1
OLDPWD=/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/workdir
SHLVL=1
TERM=xterm
TZ=Etc/UTC
_=/usr/local/bin/kibot

KiAuto:
This is KiAuto v2.3.6
Installed at: /usr/local/bin/pcbnew_do
Using kiauto module from: /usr/local/lib/python3.11/dist-packages/kiauto
Interpreted by Python: /usr/bin/python3 (v3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0])
Tools:
- kicad: /usr/bin/kicad (v9.0.1)
- xdotool: /usr/bin/xdotool
- recordmydesktop: /usr/bin/recordmydesktop
- xsltproc: /usr/bin/xsltproc
- xclip: /usr/bin/xclip
- convert: /usr/bin/convert

```
