### ISSUE TITLE
[HOW] Use blender export (problems with pcb2blender 2.17)

### ISSUE THREAD

**Issue by marcoscas** [INTI-CMNB/KiBot#816]
**What do you want to achieve?**
Firstly, I am new to KiBot. I have been trying to create a Blender export for several hours and am encountering a problem: the component pads are consistently positioned outside of the PCB. When I generate the pcb3D file directly from KiCad, it is correct; however, the file created with KiBot is always incorrect. I have tried numerous options but have been unable to generate a correct file. It appears to be a configuration issue, and I would like to ask if anyone has experienced the same problem.
One difference I noticed is that the KiCad output includes several files with the .toml extensión, which are readable with a text editor. However,, the KiBot output files have no extension and cannot be openend with a text editor.

**Do you have some PCB/Schematic to use as example?**
Attached is a sample project with the output generated from KiCad (test_3d_fromKicad) and from KiBot (test_3d_blender_export).

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml
kibot:
  version: 1

outputs:
  - name: '3d_export'
    comment: "Exports the PCB in blender format"
    type: blender_export
    options:
      render_options:
        transparent_background: true
        samples: 10
        #resolution_x: 1920
        #resolution_y: 1080
      point_of_view:
        rotate_x: 30
        rotate_z: -20
        # view: bottom
      outputs:
        - type: blender
        - type: render
```

**Environment (please complete the following information):**
I am using Tuxedo OS (Ubuntu 24.04) with Kicad installed from PPA.

**Additional context**
This behavior occurs in all of my projects, which leads me to believe there is an issue with my installation.

[test_3d.zip](https://github.com/user-attachments/files/20184760/test_3d.zip)
