### ISSUE TITLE
Scheme to PDF: custom title block not printed when variant is used

### ISSUE THREAD

**Issue by stream1972** [INTI-CMNB/KiBot#82]
Not a showstopper, but very strange issue. Our schematics have custom title block, which is referenced in project file using macro:
```ini
[schematic_editor]
version=1
PageLayoutDescrFile=$(KICAD_USER_TEMPLATE_DIR)/Proxy_landscape.kicad_wks
```

And macro is correctly configured in KiCad config `kicad_common`:
```ini
[EnvironmentVariables]
KICAD_SYMBOL_DIR=/usr/share/kicad/library
KICAD_TEMPLATE_DIR=/usr/share/kicad/template
KICAD_USER_TEMPLATE_DIR=/home/stream/Documents/KiCad/_Proxyma/template
KISYS3DMOD=/home/stream/Documents/KiCad/_Proxyma/modules/packages3d/Proxyma.3dshapes
KISYSMOD=/home/stream/Documents/KiCad/_Proxyma/modules
```

Simple output with default settings works just fine, generated PDF have our title block:
```yaml
outputs:
  - name: 'sch'
    comment: 'Scheme to PDF'
    type: pdf_sch_print
    dir: 'MiscOutput'
```
But when I try to add a variant, our custom title block is replaced by default KiCad title block:
```yaml
outputs:
  - name: 'sch'
    comment: 'Scheme to PDF'
    type: pdf_sch_print
    dir: 'MiscOutput'
    options:
      variant: std

variants:
  - name: 'std'
    type: kibom
    file_id: _STD
    variant: STD
```
