### ISSUE TITLE
[BUG] Kibom filter style not selectin components with multiple variants

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#823]
I have a component with a "Config" field for the "kibom" variant style.

The Config field has this value: "+flw,+bornier_lvl12_flw_clm,+FlwOnConn2".  Il also tried "+flw,bornier_lvl12_flw_clm,FlwOnConn2"

With a configuration like this, the component is not selected:
```yaml
  - name: example
    variant: connextscl,FlwOnConn2
    type: kibom
    pre_transform: [_var_rename]
```

After adding "flw", the component is selected.

```yaml
  - name: example
    variant: connextscl,flw,FlwOnConn2
    type: kibom
    pre_transform: [_var_rename]
```

This occurs with "ghcr.io/inti-cmnb/kicad9_auto_full:1.8.4" .
