### ISSUE TITLE
[Question] Error - No such file or directory when using Kibot in CI/CD

### ISSUE THREAD

**Issue by Kampi** [INTI-CMNB/KiBot#833]
**What do you want to achieve?**

I´m using this Kibot pipeline with CI/CD in Github:

```
kibot:
  version: 1

preflight:
  draw_stackup: true
  update_pcb_characteristics: true
  update_stackup: true

variants:
  - name: "Full"
    comment: "Full PCB"
    type: kibom

global:
  out_dir: "../production/Export-%D"
  date_format: "%Y-%m-%d"

outputs:
  - name: "Navigation results"
    comment: "Create navigation results page"
    type: navigate_results
    dir: overview

  - name: "Download datasheets"
    comment: "Download component datasheets"
    type: download_datasheets
    dir: docs/datasheets
    category: "documentation"

  - name: "Generate IBOM"
    comment: "Interactive Bill of Materials"
    type: ibom
    dir: docs
    category: "documentation"
    options:
      show_fabrication: true

  - name: "Print Schematics"
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: docs
    category: "documentation"
    options:
      output: Schematic.%x

  - name: "Board Top"
    comment: "Top layer view"
    type: pcbdraw
    dir: docs/images
    category: "documentation"
    options:
      format: png
      bottom: false
      output: "PCB_Top.%x"

  - name: "Board Bottom"
    comment: "Bottom layer view"
    type: pcbdraw
    dir: docs/images
    category: "documentation"
    options:
      format: png
      bottom: true
      output: "PCB_Bottom.%x"

  - name: "Generate Drill"
    comment: "Generate drill files"
    type: excellon
    dir: gerber
    category: "production"
    options:
      metric_units: true
      mirror_y_axis: false
      pth_and_npth_single_file: false
      left_digits: 0
      minimal_header: false
      use_aux_axis_as_origin: true
      route_mode_for_oval_holes: true
      zeros_format: "DECIMAL_FORMAT"

  - name: "Generate Gerbers"
    comment: "Generate Gerbers"
    type: gerber
    dir: gerber
    category: "production"
    options:
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15

      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false

    layers:
      - layer: F.Cu
        suffix: F_Cu
        description: Front copper
      - layer: Inner1
        suffix: Inner1
        description: 'Inner cooper layer'
      - layer: Inner2
        suffix: Inner2
        description: 'Inner copper layer'
      - layer: B.Cu
        suffix: B_Cu
        description: Bottom copper
      - layer: B.Paste
        suffix: B_Paste
        description: Bottom solder paste
      - layer: F.Paste
        suffix: F_Paste
        description: Front solder paste
      - layer: B.Silkscreen
        suffix: B_Silkscreen
        description: Bottom silkscreen (artwork)
      - layer: F.Silkscreen
        suffix: F_Silkscreen
        description: Front silkscreen (artwork)
      - layer: B.Mask
        suffix: B_Mask
        description: Bottom soldermask (negative)
      - layer: F.Mask
        suffix: F_Mask
        description: Front soldermask (negative)
      - layer: Edge.Cuts
        suffix: Edge_Cuts
        description: Board shape
      - layer: B.Courtyard
        suffix: B_Courtyard
        description: Bottom courtyard area
      - layer: F.Courtyard
        suffix: F_Courtyard
        description: Front courtyard area
      - layer: B.Fab
        suffix: B_Fab
        description: Bottom documentation
      - layer: F.Fab
        suffix: F_Fab
        description: Front documentation
      - layer: User.1
        suffix: User_1
        description: User layer 1

  - name: "Pick & Place"
    comment: "Pick & Place"
    type: position
    dir: centroid
    category: "production"
    options:
      format: ASCII
      only_smd: false

  - name: "PCB Specifications"
    comment: "PCB Specifications"
    type: pcb_print
    dir: docs
    category: "production"
    options:
      output: "PCB.pdf"
      format: PDF
      pages:
      - layers:
        - layer: Edge.Cuts
        - layer: User.1
        - layer: User.Drawings
        sheet: "PCB Specifications"
        monochrome: true

  - name: "Ref Top"
    comment: "Ref Top"
    type: pcb_print
    dir: docs
    category: "purchasing"
    options:
      output: "Ref_Top.%x"
      format: PDF
      pages:
      - layers:
        - layer: Edge.Cuts
        - layer: F.Fab
        sheet: "Ref-Top"
        monochrome: true

  - name: "Ref Bottom"
    comment: "Ref Bottom"
    type: pcb_print
    dir: docs
    category: "purchasing"
    options:
      output: "Ref_Bot.%x"
      format: PDF
      pages:
      - layers:
        - layer: Edge.Cuts
        - layer: B.Fab
        sheet: "Ref-Bottom"
        monochrome: true
        mirror: true

  - name: "Copy Other"
    comment: "Copy all other files for assembly"
    type: copy_files
    category: "purchasing"
    options:
      files:
        - source: ../production/Export-%D/docs/Ref_Bot.pdf
          dest: other
        - source: ../production/Export-%D/docs/Ref_Top.pdf
          dest: other
        - source: ../dev-kit/print/devit-print_top.png
          dest: other
        - source: ../dev-kit/print/devkit-print-bot.png
          dest: other

  - name: "BOM for PCBWay"
    comment: "BOM for PCBWay"
    type: bom
    dir: docs
    category: "purchasing"
    options:
      format: XLSX
      count_smd_tht: true
      output: "BOM_PCBWay.%x"
      ref_separator: ','
      columns:
        - field: Row
          name: Item
        - field: References
          name: Ref Des
        - field: Build Quantity
          name: Quantity
        - field: Mfr.
          name: Manufacturer
        - field: Mfr. No.
          name: Mfg Part#
        - field: Value
          name: Description / Value
        - field: Footprint
          name: Package
        - field: Footprint Type
          name: Type
        - field: Footprint Side
          name: Side
      xlsx:
        title: "%f BOM"
        hide_stats_info: false
        quote_all: true

  - name: "ZIP Gerber"
    comment: "ZIP Gerber"
    type: compress
    dir: .
    category: "purchasing"
    options:
      format: ZIP
      files:
        - source: gerber/**
      output: "Gerber_%D.%x"

  - name: "ZIP Centroid"
    comment: "ZIP Centroid"
    type: compress
    dir: .
    category: "purchasing"
    options:
      format: ZIP
      files:
        - source: centroid/**
      output: "Centroid_%D.%x"

  - name: "ZIP Other"
    comment: "ZIP Other"
    type: compress
    dir: .
    category: "purchasing"
    options:
      format: ZIP
      files:
        - source: other/**
      output: "Other_%D.%x"

  - name: "Step file"
    comment: "STEP file generation"
    type: step
    dir: cad
    category: "mechanical"

  - name: "3D rendering"
    comment: "3D rendering"
    type: render_3d
    dir: docs/images
    category: "documentation"
    options:
      ray_tracing: true
      rotate_x: 3
      rotate_z: -2
      output: "PCB_Rendering.%x"
```

and I get the error 

```
DEBUG:Expanding `Other_%D.%x` in PCB context for <kibot.out_compress.CompressOptions object at 0x7f1d8ed9c1d0> parent: 'ZIP Other' (ZIP Other) [compress] (kibot - optionable.py:493)
DEBUG:Expanded `Other_2025-05-28.zip` (kibot - optionable.py:539)
DEBUG:Collecting files (kibot - out_compress.py:252)
DEBUG:Expanding `/__w/ZSWatch-HW/ZSWatch-HW/dev-kit/../production/Full` in SCH context for <kibot.out_compress.CompressOptions object at 0x7f1d8ed9c1d0> parent: 'ZIP Other' (ZIP Other) [compress] (kibot - optionable.py:493)
DEBUG:Expanded `/__w/ZSWatch-HW/ZSWatch-HW/dev-kit/../production/Full` (kibot - optionable.py:539)
DEBUG:Expanding `other/**` in SCH context for other/** parent: <kibot.out_compress.CompressOptions object at 0x7f1d8ed9c1d0> (kibot - optionable.py:493)
DEBUG:Expanded `other/**` (kibot - optionable.py:539)
DEBUG:- Pattern other/** list of files: ['/__w/ZSWatch-HW/ZSWatch-HW/dev-kit/../production/Full/other/'] (kibot - out_compress.py:209)
DEBUG:Generating `/__w/ZSWatch-HW/ZSWatch-HW/production/Full/Other_2025-05-28.zip` archive (kibot - out_compress.py:255)
DEBUG:Adding /__w/ZSWatch-HW/ZSWatch-HW/production/Full/other as other (kibot - out_compress.py:113)
Traceback (most recent call last):
  File "/usr/bin/kibot", line 33, in <module>
    sys.exit(load_entry_point('kibot==1.8.4', 'console_scripts', 'kibot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 658, in main
    generate_outputs(args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 716, in generate_outputs
    _generate_outputs(targets, invert, skip_pre, cli_order, no_priority, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 706, in _generate_outputs
    run_output(out, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 607, in run_output
    out.run(get_output_dir(out.dir, out))
  File "/usr/lib/python3/dist-packages/kibot/out_base.py", line 217, in run
    self.options.run(target)
  File "/usr/lib/python3/dist-packages/kibot/out_compress.py", line 257, in run
    self.create_zip(output, files)
  File "/usr/lib/python3/dist-packages/kibot/out_compress.py", line 114, in create_zip
    zip.write(fname, dest)
  File "/usr/lib/python3.11/zipfile.py", line 1784, in write
    zinfo = ZipInfo.from_file(filename, arcname,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/zipfile.py", line 531, in from_file
    st = os.stat(filename)
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/__w/ZSWatch-HW/ZSWatch-HW/production/Full/other'
```

The strange thing is that the pipeline gets executed successfully when I run it in a Docker container on my Ubuntu. 

![Image](https://github.com/user-attachments/assets/b5bd143f-a693-443f-aeaa-1aaf7a2c836a)

I use the following Docker command

```
docker run --rm -it  --user $USER_ID:$GROUP_ID --env NO_AT_BRIDGE=1  --env DISPLAY=$DISPLAY --workdir="/home/$USER"     --volume=/tmp/.X11-unix:/tmp/.X11-unix --volume="/etc/group:/etc/group:to" --volume="/etc/passwd:/etc/passwd:to" --volume="/etc/shadow:/etc/shadow:to" --volume="/home/$USER:/home/$USER:rw" ghcr.io/inti-cmnb/kicad9_auto_full:latest /bin/bash
```

**Do you have some PCB/Schematic to use as example?**

- [KiCad project](https://github.com/Kampi/ZSWatch-HW/tree/3.0.0_Dev) for testing

**Environment (please complete the following information):**

- CI/CD Github
- Ubuntu 22.04 with Docker
