### ISSUE TITLE
[HOW] can I make part not appear to be silver

### ISSUE THREAD

**Issue by Bouni** [INTI-CMNB/KiBot#841]
**What do you want to achieve?**
I render my PCB sucessfully using blender_export. however, some components appear to be silver or some sort of metal. Can I somehow define a color that should be used for certian components?

**Do you have some PCB/Schematic to use as example?**
This is what I see in the 3D viewer in KiCAD

![Image](https://github.com/user-attachments/assets/f2269bcd-b90d-4d18-9ea3-018baae8fafa)

And this is what I get from the blender export

![Image](https://github.com/user-attachments/assets/2bf1f17f-e10c-40d0-b6fb-d47fc679400c)

K1 and the connector seem to be silver

**Do you have some configuration file (.kibot.yaml) that you are using?**
You can attach it or paste the content in the following section:
```yaml

  - name: "PCB 3D Blender image"
    comment: "3D render from top (High Quality)"
    type: blender_export
    options:
      render_options:
        background1: "#8FBCF7FF"
        background2: "#0B1E35FF"  
        samples: 20
        resolution_y: 1440
        resolution_x: 2560
      point_of_view:
        rotate_x: -5
      outputs:
        - type: render
          output: "Oberseite-3D.png"
```

**Environment (please complete the following information):**
Where are you running KiBot:
- Gitea actions, INTI-CMNB/KiBot@v2_k9
