### ISSUE TITLE
Running github actions locally & retrieving results.

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#97]
I am examinging the CI/CD workflow but I have to run the actions locally and there is a tool for that: [act](https://github.com/nektos/act).

That essentially works, but:
- the files from the artifact server are not readily available, 
- the files do not seem to be available "locally" (maybe I am not generating any result at this moment)
- INTI-CMNB/KiBot@v1 is cloned on every call, which seems to stall/take a long time when done repeatedly (maybe github is throthling this).  could this not be in the image?

I installed the latest version which allows running an artifact server locally. I also add  `-b` to use the local path rather than copying the files, hoping that I can get some result files.

```batch
act -b --artifact-server-path e:\help
```

I added an 'env' variable for the project name, this is ok according to the output.
This prepares the path to making this a file to include from anohter yaml.

```yaml
name: "KiCad CI/CD"

env:
  PROJECT: TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - .github/workflows/${{ env.PROJECT }}.yml
  pull_request:
    paths:
      - '*.sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - .github/workflows/${{ env.PROJECT }}.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fabrication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v1
      with:
        # Required - kibot config file
        config: ${{ env.PROJECT }}.yaml
        # optional - prefix to output defined in config
        dir: ${{ env.PROJECT }}.yaml
        # optional - schematic file
        schema: '${{ env.PROJECT }}.sch'
        # optional - PCB design file
        board: '${{ env.PROJECT }}.kicad_pcb'
    - name: Retrieve results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT }}
        path: |
          ${{ env.PROJECT }}
        if-no-files-found: warn
```

I have to determine why I do not get any result yet.  

Act is usefull when uploads to github/gitlab are not available options or to do the flow locally for other reasons.
